// Decompiled with JetBrains decompiler
// Type: Ekreta.Mobile.Core.Views.ExamsDetailPage
// Assembly: Ekreta.Mobile.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5AA13053-CF9F-480D-A76A-8A5D6C4EE194
// Assembly location: C:\fakepath\\Desktop\Ekreta.Mobile.Core.dll

using Ekreta.Mobile.Core.Extensions;
using Ekreta.Mobile.Core.ViewModels;
using FFImageLoading.Forms;
using MvvmCross.Forms.Presenters.Attributes;
using MvvmCross.Forms.Views;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Reflection;
using System.Xml;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.PlatformConfiguration.iOSSpecific;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Internals;

namespace Ekreta.Mobile.Core.Views
{
  [XamlFilePath("Views/ExamsDetailPage.xaml")]
  [MvxMasterDetailPagePresentation]
  [XamlCompilation]
  public class ExamsDetailPage : MvxContentPage<ExamsDetailViewModel>
  {
    public ExamsDetailPage()
    {
      base.\u002Ector();
      this.InitializeComponent();
    }

    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private void InitializeComponent()
    {
      ResourceLoader.ResourceLoadingQuery resourceLoadingQuery = new ResourceLoader.ResourceLoadingQuery();
      resourceLoadingQuery.set_AssemblyName(typeof (ExamsDetailPage).GetTypeInfo().Assembly.GetName());
      resourceLoadingQuery.set_ResourcePath("Views/ExamsDetailPage.xaml");
      resourceLoadingQuery.set_Instance((object) this);
      if (ResourceLoader.CanProvideContentFor(resourceLoadingQuery))
        this.__InitComponentRuntime();
      else if (XamlLoader.get_XamlFileProvider() != null && XamlLoader.get_XamlFileProvider()(((object) this).GetType()) != null)
      {
        this.__InitComponentRuntime();
      }
      else
      {
        TranslateExtension translateExtension1 = new TranslateExtension();
        StaticResourceExtension resourceExtension1 = new StaticResourceExtension();
        RowDefinition rowDefinition1 = new RowDefinition();
        RowDefinition rowDefinition2 = new RowDefinition();
        StaticResourceExtension resourceExtension2 = new StaticResourceExtension();
        RowDefinition rowDefinition3 = new RowDefinition();
        RowDefinition rowDefinition4 = new RowDefinition();
        StaticResourceExtension resourceExtension3 = new StaticResourceExtension();
        BindingExtension bindingExtension1 = new BindingExtension();
        Label label1 = new Label();
        StaticResourceExtension resourceExtension4 = new StaticResourceExtension();
        CachedImage cachedImage = new CachedImage();
        Grid grid1 = new Grid();
        StaticResourceExtension resourceExtension5 = new StaticResourceExtension();
        StaticResourceExtension resourceExtension6 = new StaticResourceExtension();
        TranslateExtension translateExtension2 = new TranslateExtension();
        Label label2 = new Label();
        StaticResourceExtension resourceExtension7 = new StaticResourceExtension();
        BindingExtension bindingExtension2 = new BindingExtension();
        Label label3 = new Label();
        StaticResourceExtension resourceExtension8 = new StaticResourceExtension();
        TranslateExtension translateExtension3 = new TranslateExtension();
        Label label4 = new Label();
        StaticResourceExtension resourceExtension9 = new StaticResourceExtension();
        BindingExtension bindingExtension3 = new BindingExtension();
        Label label5 = new Label();
        StaticResourceExtension resourceExtension10 = new StaticResourceExtension();
        TranslateExtension translateExtension4 = new TranslateExtension();
        Label label6 = new Label();
        StaticResourceExtension resourceExtension11 = new StaticResourceExtension();
        BindingExtension bindingExtension4 = new BindingExtension();
        Label label7 = new Label();
        StaticResourceExtension resourceExtension12 = new StaticResourceExtension();
        TranslateExtension translateExtension5 = new TranslateExtension();
        Label label8 = new Label();
        StaticResourceExtension resourceExtension13 = new StaticResourceExtension();
        BindingExtension bindingExtension5 = new BindingExtension();
        Label label9 = new Label();
        StaticResourceExtension resourceExtension14 = new StaticResourceExtension();
        TranslateExtension translateExtension6 = new TranslateExtension();
        Label label10 = new Label();
        StaticResourceExtension resourceExtension15 = new StaticResourceExtension();
        BindingExtension bindingExtension6 = new BindingExtension();
        Label label11 = new Label();
        StaticResourceExtension resourceExtension16 = new StaticResourceExtension();
        TranslateExtension translateExtension7 = new TranslateExtension();
        Label label12 = new Label();
        StaticResourceExtension resourceExtension17 = new StaticResourceExtension();
        BindingExtension bindingExtension7 = new BindingExtension();
        Label label13 = new Label();
        StaticResourceExtension resourceExtension18 = new StaticResourceExtension();
        TranslateExtension translateExtension8 = new TranslateExtension();
        Label label14 = new Label();
        StaticResourceExtension resourceExtension19 = new StaticResourceExtension();
        BindingExtension bindingExtension8 = new BindingExtension();
        Label label15 = new Label();
        StaticResourceExtension resourceExtension20 = new StaticResourceExtension();
        TranslateExtension translateExtension9 = new TranslateExtension();
        Label label16 = new Label();
        StaticResourceExtension resourceExtension21 = new StaticResourceExtension();
        BindingExtension bindingExtension9 = new BindingExtension();
        Label label17 = new Label();
        StackLayout stackLayout = new StackLayout();
        ScrollView scrollView = new ScrollView();
        Grid grid2 = new Grid();
        ExamsDetailPage examsDetailPage;
        NameScope nameScope = (NameScope) (NameScope.GetNameScope((BindableObject) (examsDetailPage = this)) ?? (INameScope) new NameScope());
        NameScope.SetNameScope((BindableObject) examsDetailPage, (INameScope) nameScope);
        translateExtension1.Text = "ExamsDetail_Page_Title";
        TranslateExtension translateExtension10 = translateExtension1;
        XamlServiceProvider xamlServiceProvider1 = new XamlServiceProvider();
        Type type1 = typeof (IProvideValueTarget);
        object[] objArray1 = new object[0 + 1];
        objArray1[0] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider1;
        object obj1 = (object) (valueTargetProvider1 = new SimpleValueTargetProvider(objArray1, (object) Page.TitleProperty, (INameScope) nameScope));
        xamlServiceProvider1.Add(type1, (object) valueTargetProvider1);
        xamlServiceProvider1.Add(typeof (IReferenceProvider), obj1);
        Type type2 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver1 = new XmlNamespaceResolver();
        namespaceResolver1.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver1.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver1.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver1.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver1.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver1.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver1.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver1.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver1.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver1 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver1, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider1.Add(type2, (object) xamlTypeResolver1);
        xamlServiceProvider1.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(13, 5)));
        object obj2 = ((IMarkupExtension) translateExtension10).ProvideValue((IServiceProvider) xamlServiceProvider1);
        ((Page) examsDetailPage).set_Title((string) obj2);
        ((BindableObject) examsDetailPage).SetValue((BindableProperty) Page.UseSafeAreaProperty, (object) true);
        resourceExtension1.set_Key("PageBackgroundColor");
        StaticResourceExtension resourceExtension22 = resourceExtension1;
        XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
        Type type3 = typeof (IProvideValueTarget);
        object[] objArray2 = new object[0 + 1];
        objArray2[0] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider2;
        object obj3 = (object) (valueTargetProvider2 = new SimpleValueTargetProvider(objArray2, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope));
        xamlServiceProvider2.Add(type3, (object) valueTargetProvider2);
        xamlServiceProvider2.Add(typeof (IReferenceProvider), obj3);
        Type type4 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver2 = new XmlNamespaceResolver();
        namespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver2.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver2.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver2.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver2.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver2.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver2.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver2.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver2 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver2, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider2.Add(type4, (object) xamlTypeResolver2);
        xamlServiceProvider2.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(16, 5)));
        object obj4 = ((IMarkupExtension) resourceExtension22).ProvideValue((IServiceProvider) xamlServiceProvider2);
        ((VisualElement) examsDetailPage).set_BackgroundColor((Color) obj4);
        ((BindableObject) rowDefinition1).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid2).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition1);
        ((BindableObject) rowDefinition2).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("3*"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid2).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition2);
        resourceExtension2.set_Key("DetailHeaderHolderStyle");
        StaticResourceExtension resourceExtension23 = resourceExtension2;
        XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
        Type type5 = typeof (IProvideValueTarget);
        object[] objArray3 = new object[0 + 3];
        objArray3[0] = (object) grid1;
        objArray3[1] = (object) grid2;
        objArray3[2] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider3;
        object obj5 = (object) (valueTargetProvider3 = new SimpleValueTargetProvider(objArray3, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider3.Add(type5, (object) valueTargetProvider3);
        xamlServiceProvider3.Add(typeof (IReferenceProvider), obj5);
        Type type6 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver3 = new XmlNamespaceResolver();
        namespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver3.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver3.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver3.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver3.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver3.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver3.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver3.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver3 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver3, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider3.Add(type6, (object) xamlTypeResolver3);
        xamlServiceProvider3.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(27, 15)));
        object obj6 = ((IMarkupExtension) resourceExtension23).ProvideValue((IServiceProvider) xamlServiceProvider3);
        ((NavigableElement) grid1).set_Style((Style) obj6);
        ((BindableObject) rowDefinition3).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid1).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition3);
        ((BindableObject) rowDefinition4).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("50"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid1).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition4);
        resourceExtension3.set_Key("DetailDataTitleStyle");
        StaticResourceExtension resourceExtension24 = resourceExtension3;
        XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
        Type type7 = typeof (IProvideValueTarget);
        object[] objArray4 = new object[0 + 4];
        objArray4[0] = (object) label1;
        objArray4[1] = (object) grid1;
        objArray4[2] = (object) grid2;
        objArray4[3] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider4;
        object obj7 = (object) (valueTargetProvider4 = new SimpleValueTargetProvider(objArray4, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider4.Add(type7, (object) valueTargetProvider4);
        xamlServiceProvider4.Add(typeof (IReferenceProvider), obj7);
        Type type8 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver4 = new XmlNamespaceResolver();
        namespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver4.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver4.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver4.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver4.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver4.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver4.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver4.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver4 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver4, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider4.Add(type8, (object) xamlTypeResolver4);
        xamlServiceProvider4.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(32, 20)));
        object obj8 = ((IMarkupExtension) resourceExtension24).ProvideValue((IServiceProvider) xamlServiceProvider4);
        ((NavigableElement) label1).set_Style((Style) obj8);
        bindingExtension1.set_Path("Exam.SzamonkeresMegnevezese");
        BindingBase bindingBase1 = ((IMarkupExtension<BindingBase>) bindingExtension1).ProvideValue((IServiceProvider) null);
        ((BindableObject) label1).SetBinding((BindableProperty) Label.TextProperty, bindingBase1);
        ((ICollection<View>) grid1.get_Children()).Add((View) label1);
        ((BindableObject) cachedImage).SetValue((BindableProperty) Grid.RowProperty, (object) 1);
        resourceExtension4.set_Key("DetailHeaderBottomCachedImageStyle");
        StaticResourceExtension resourceExtension25 = resourceExtension4;
        XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
        Type type9 = typeof (IProvideValueTarget);
        object[] objArray5 = new object[0 + 4];
        objArray5[0] = (object) cachedImage;
        objArray5[1] = (object) grid1;
        objArray5[2] = (object) grid2;
        objArray5[3] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider5;
        object obj9 = (object) (valueTargetProvider5 = new SimpleValueTargetProvider(objArray5, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider5.Add(type9, (object) valueTargetProvider5);
        xamlServiceProvider5.Add(typeof (IReferenceProvider), obj9);
        Type type10 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver5 = new XmlNamespaceResolver();
        namespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver5.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver5.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver5.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver5.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver5.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver5.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver5.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver5 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver5, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider5.Add(type10, (object) xamlTypeResolver5);
        xamlServiceProvider5.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(33, 54)));
        object obj10 = ((IMarkupExtension) resourceExtension25).ProvideValue((IServiceProvider) xamlServiceProvider5);
        ((NavigableElement) cachedImage).set_Style((Style) obj10);
        ((ICollection<View>) grid1.get_Children()).Add((View) cachedImage);
        ((ICollection<View>) grid2.get_Children()).Add((View) grid1);
        ((BindableObject) scrollView).SetValue((BindableProperty) Grid.RowProperty, (object) 1);
        resourceExtension5.set_Key("DetailContentHolderStyle");
        StaticResourceExtension resourceExtension26 = resourceExtension5;
        XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
        Type type11 = typeof (IProvideValueTarget);
        object[] objArray6 = new object[0 + 3];
        objArray6[0] = (object) scrollView;
        objArray6[1] = (object) grid2;
        objArray6[2] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider6;
        object obj11 = (object) (valueTargetProvider6 = new SimpleValueTargetProvider(objArray6, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider6.Add(type11, (object) valueTargetProvider6);
        xamlServiceProvider6.Add(typeof (IReferenceProvider), obj11);
        Type type12 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver6 = new XmlNamespaceResolver();
        namespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver6.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver6.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver6.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver6.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver6.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver6.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver6.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver6 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver6, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider6.Add(type12, (object) xamlTypeResolver6);
        xamlServiceProvider6.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(36, 34)));
        object obj12 = ((IMarkupExtension) resourceExtension26).ProvideValue((IServiceProvider) xamlServiceProvider6);
        ((NavigableElement) scrollView).set_Style((Style) obj12);
        resourceExtension6.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension27 = resourceExtension6;
        XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
        Type type13 = typeof (IProvideValueTarget);
        object[] objArray7 = new object[0 + 5];
        objArray7[0] = (object) label2;
        objArray7[1] = (object) stackLayout;
        objArray7[2] = (object) scrollView;
        objArray7[3] = (object) grid2;
        objArray7[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider7;
        object obj13 = (object) (valueTargetProvider7 = new SimpleValueTargetProvider(objArray7, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider7.Add(type13, (object) valueTargetProvider7);
        xamlServiceProvider7.Add(typeof (IReferenceProvider), obj13);
        Type type14 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver7 = new XmlNamespaceResolver();
        namespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver7.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver7.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver7.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver7.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver7.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver7.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver7.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver7 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver7, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider7.Add(type14, (object) xamlTypeResolver7);
        xamlServiceProvider7.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(38, 24)));
        object obj14 = ((IMarkupExtension) resourceExtension27).ProvideValue((IServiceProvider) xamlServiceProvider7);
        ((NavigableElement) label2).set_Style((Style) obj14);
        translateExtension2.Text = "Exam_Model_Datum";
        TranslateExtension translateExtension11 = translateExtension2;
        XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
        Type type15 = typeof (IProvideValueTarget);
        object[] objArray8 = new object[0 + 5];
        objArray8[0] = (object) label2;
        objArray8[1] = (object) stackLayout;
        objArray8[2] = (object) scrollView;
        objArray8[3] = (object) grid2;
        objArray8[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider8;
        object obj15 = (object) (valueTargetProvider8 = new SimpleValueTargetProvider(objArray8, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider8.Add(type15, (object) valueTargetProvider8);
        xamlServiceProvider8.Add(typeof (IReferenceProvider), obj15);
        Type type16 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver8 = new XmlNamespaceResolver();
        namespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver8.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver8.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver8.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver8.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver8.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver8.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver8.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver8 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver8, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider8.Add(type16, (object) xamlTypeResolver8);
        xamlServiceProvider8.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(38, 70)));
        object obj16 = ((IMarkupExtension) translateExtension11).ProvideValue((IServiceProvider) xamlServiceProvider8);
        label2.set_Text((string) obj16);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label2);
        resourceExtension7.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension28 = resourceExtension7;
        XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
        Type type17 = typeof (IProvideValueTarget);
        object[] objArray9 = new object[0 + 5];
        objArray9[0] = (object) label3;
        objArray9[1] = (object) stackLayout;
        objArray9[2] = (object) scrollView;
        objArray9[3] = (object) grid2;
        objArray9[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider9;
        object obj17 = (object) (valueTargetProvider9 = new SimpleValueTargetProvider(objArray9, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider9.Add(type17, (object) valueTargetProvider9);
        xamlServiceProvider9.Add(typeof (IReferenceProvider), obj17);
        Type type18 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver9 = new XmlNamespaceResolver();
        namespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver9.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver9.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver9.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver9.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver9.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver9.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver9.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver9 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver9, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider9.Add(type18, (object) xamlTypeResolver9);
        xamlServiceProvider9.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(39, 24)));
        object obj18 = ((IMarkupExtension) resourceExtension28).ProvideValue((IServiceProvider) xamlServiceProvider9);
        ((NavigableElement) label3).set_Style((Style) obj18);
        bindingExtension2.set_StringFormat("{0:d}");
        bindingExtension2.set_Path("Exam.DatumLocal");
        BindingBase bindingBase2 = ((IMarkupExtension<BindingBase>) bindingExtension2).ProvideValue((IServiceProvider) null);
        ((BindableObject) label3).SetBinding((BindableProperty) Label.TextProperty, bindingBase2);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label3);
        resourceExtension8.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension29 = resourceExtension8;
        XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
        Type type19 = typeof (IProvideValueTarget);
        object[] objArray10 = new object[0 + 5];
        objArray10[0] = (object) label4;
        objArray10[1] = (object) stackLayout;
        objArray10[2] = (object) scrollView;
        objArray10[3] = (object) grid2;
        objArray10[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider10;
        object obj19 = (object) (valueTargetProvider10 = new SimpleValueTargetProvider(objArray10, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider10.Add(type19, (object) valueTargetProvider10);
        xamlServiceProvider10.Add(typeof (IReferenceProvider), obj19);
        Type type20 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver10 = new XmlNamespaceResolver();
        namespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver10.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver10.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver10.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver10.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver10.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver10.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver10.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver10 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver10, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider10.Add(type20, (object) xamlTypeResolver10);
        xamlServiceProvider10.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(41, 24)));
        object obj20 = ((IMarkupExtension) resourceExtension29).ProvideValue((IServiceProvider) xamlServiceProvider10);
        ((NavigableElement) label4).set_Style((Style) obj20);
        translateExtension3.Text = "Exam_Model_HetNapja";
        TranslateExtension translateExtension12 = translateExtension3;
        XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
        Type type21 = typeof (IProvideValueTarget);
        object[] objArray11 = new object[0 + 5];
        objArray11[0] = (object) label4;
        objArray11[1] = (object) stackLayout;
        objArray11[2] = (object) scrollView;
        objArray11[3] = (object) grid2;
        objArray11[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider11;
        object obj21 = (object) (valueTargetProvider11 = new SimpleValueTargetProvider(objArray11, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider11.Add(type21, (object) valueTargetProvider11);
        xamlServiceProvider11.Add(typeof (IReferenceProvider), obj21);
        Type type22 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver11 = new XmlNamespaceResolver();
        namespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver11.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver11.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver11.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver11.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver11.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver11.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver11.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver11 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver11, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider11.Add(type22, (object) xamlTypeResolver11);
        xamlServiceProvider11.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(41, 70)));
        object obj22 = ((IMarkupExtension) translateExtension12).ProvideValue((IServiceProvider) xamlServiceProvider11);
        label4.set_Text((string) obj22);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label4);
        resourceExtension9.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension30 = resourceExtension9;
        XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
        Type type23 = typeof (IProvideValueTarget);
        object[] objArray12 = new object[0 + 5];
        objArray12[0] = (object) label5;
        objArray12[1] = (object) stackLayout;
        objArray12[2] = (object) scrollView;
        objArray12[3] = (object) grid2;
        objArray12[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider12;
        object obj23 = (object) (valueTargetProvider12 = new SimpleValueTargetProvider(objArray12, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider12.Add(type23, (object) valueTargetProvider12);
        xamlServiceProvider12.Add(typeof (IReferenceProvider), obj23);
        Type type24 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver12 = new XmlNamespaceResolver();
        namespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver12.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver12.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver12.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver12.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver12.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver12.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver12.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver12 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver12, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider12.Add(type24, (object) xamlTypeResolver12);
        xamlServiceProvider12.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(42, 24)));
        object obj24 = ((IMarkupExtension) resourceExtension30).ProvideValue((IServiceProvider) xamlServiceProvider12);
        ((NavigableElement) label5).set_Style((Style) obj24);
        bindingExtension3.set_Path("Exam.HetNapja");
        BindingBase bindingBase3 = ((IMarkupExtension<BindingBase>) bindingExtension3).ProvideValue((IServiceProvider) null);
        ((BindableObject) label5).SetBinding((BindableProperty) Label.TextProperty, bindingBase3);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label5);
        resourceExtension10.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension31 = resourceExtension10;
        XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
        Type type25 = typeof (IProvideValueTarget);
        object[] objArray13 = new object[0 + 5];
        objArray13[0] = (object) label6;
        objArray13[1] = (object) stackLayout;
        objArray13[2] = (object) scrollView;
        objArray13[3] = (object) grid2;
        objArray13[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider13;
        object obj25 = (object) (valueTargetProvider13 = new SimpleValueTargetProvider(objArray13, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider13.Add(type25, (object) valueTargetProvider13);
        xamlServiceProvider13.Add(typeof (IReferenceProvider), obj25);
        Type type26 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver13 = new XmlNamespaceResolver();
        namespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver13.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver13.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver13.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver13.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver13.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver13.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver13.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver13 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver13, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider13.Add(type26, (object) xamlTypeResolver13);
        xamlServiceProvider13.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(44, 24)));
        object obj26 = ((IMarkupExtension) resourceExtension31).ProvideValue((IServiceProvider) xamlServiceProvider13);
        ((NavigableElement) label6).set_Style((Style) obj26);
        translateExtension4.Text = "Exam_Model_Oraszam";
        TranslateExtension translateExtension13 = translateExtension4;
        XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
        Type type27 = typeof (IProvideValueTarget);
        object[] objArray14 = new object[0 + 5];
        objArray14[0] = (object) label6;
        objArray14[1] = (object) stackLayout;
        objArray14[2] = (object) scrollView;
        objArray14[3] = (object) grid2;
        objArray14[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider14;
        object obj27 = (object) (valueTargetProvider14 = new SimpleValueTargetProvider(objArray14, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider14.Add(type27, (object) valueTargetProvider14);
        xamlServiceProvider14.Add(typeof (IReferenceProvider), obj27);
        Type type28 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver14 = new XmlNamespaceResolver();
        namespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver14.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver14.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver14.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver14.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver14.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver14.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver14.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver14 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver14, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider14.Add(type28, (object) xamlTypeResolver14);
        xamlServiceProvider14.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(44, 70)));
        object obj28 = ((IMarkupExtension) translateExtension13).ProvideValue((IServiceProvider) xamlServiceProvider14);
        label6.set_Text((string) obj28);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label6);
        resourceExtension11.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension32 = resourceExtension11;
        XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
        Type type29 = typeof (IProvideValueTarget);
        object[] objArray15 = new object[0 + 5];
        objArray15[0] = (object) label7;
        objArray15[1] = (object) stackLayout;
        objArray15[2] = (object) scrollView;
        objArray15[3] = (object) grid2;
        objArray15[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider15;
        object obj29 = (object) (valueTargetProvider15 = new SimpleValueTargetProvider(objArray15, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider15.Add(type29, (object) valueTargetProvider15);
        xamlServiceProvider15.Add(typeof (IReferenceProvider), obj29);
        Type type30 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver15 = new XmlNamespaceResolver();
        namespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver15.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver15.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver15.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver15.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver15.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver15.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver15.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver15 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver15, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider15.Add(type30, (object) xamlTypeResolver15);
        xamlServiceProvider15.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(45, 24)));
        object obj30 = ((IMarkupExtension) resourceExtension32).ProvideValue((IServiceProvider) xamlServiceProvider15);
        ((NavigableElement) label7).set_Style((Style) obj30);
        bindingExtension4.set_Path("Exam.Oraszam");
        BindingBase bindingBase4 = ((IMarkupExtension<BindingBase>) bindingExtension4).ProvideValue((IServiceProvider) null);
        ((BindableObject) label7).SetBinding((BindableProperty) Label.TextProperty, bindingBase4);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label7);
        resourceExtension12.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension33 = resourceExtension12;
        XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
        Type type31 = typeof (IProvideValueTarget);
        object[] objArray16 = new object[0 + 5];
        objArray16[0] = (object) label8;
        objArray16[1] = (object) stackLayout;
        objArray16[2] = (object) scrollView;
        objArray16[3] = (object) grid2;
        objArray16[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider16;
        object obj31 = (object) (valueTargetProvider16 = new SimpleValueTargetProvider(objArray16, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider16.Add(type31, (object) valueTargetProvider16);
        xamlServiceProvider16.Add(typeof (IReferenceProvider), obj31);
        Type type32 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver16 = new XmlNamespaceResolver();
        namespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver16.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver16.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver16.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver16.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver16.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver16.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver16.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver16 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver16, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider16.Add(type32, (object) xamlTypeResolver16);
        xamlServiceProvider16.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(47, 24)));
        object obj32 = ((IMarkupExtension) resourceExtension33).ProvideValue((IServiceProvider) xamlServiceProvider16);
        ((NavigableElement) label8).set_Style((Style) obj32);
        translateExtension5.Text = "Exam_Model_Tantargy";
        TranslateExtension translateExtension14 = translateExtension5;
        XamlServiceProvider xamlServiceProvider17 = new XamlServiceProvider();
        Type type33 = typeof (IProvideValueTarget);
        object[] objArray17 = new object[0 + 5];
        objArray17[0] = (object) label8;
        objArray17[1] = (object) stackLayout;
        objArray17[2] = (object) scrollView;
        objArray17[3] = (object) grid2;
        objArray17[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider17;
        object obj33 = (object) (valueTargetProvider17 = new SimpleValueTargetProvider(objArray17, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider17.Add(type33, (object) valueTargetProvider17);
        xamlServiceProvider17.Add(typeof (IReferenceProvider), obj33);
        Type type34 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver17 = new XmlNamespaceResolver();
        namespaceResolver17.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver17.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver17.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver17.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver17.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver17.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver17.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver17.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver17.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver17 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver17, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider17.Add(type34, (object) xamlTypeResolver17);
        xamlServiceProvider17.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(47, 70)));
        object obj34 = ((IMarkupExtension) translateExtension14).ProvideValue((IServiceProvider) xamlServiceProvider17);
        label8.set_Text((string) obj34);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label8);
        resourceExtension13.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension34 = resourceExtension13;
        XamlServiceProvider xamlServiceProvider18 = new XamlServiceProvider();
        Type type35 = typeof (IProvideValueTarget);
        object[] objArray18 = new object[0 + 5];
        objArray18[0] = (object) label9;
        objArray18[1] = (object) stackLayout;
        objArray18[2] = (object) scrollView;
        objArray18[3] = (object) grid2;
        objArray18[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider18;
        object obj35 = (object) (valueTargetProvider18 = new SimpleValueTargetProvider(objArray18, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider18.Add(type35, (object) valueTargetProvider18);
        xamlServiceProvider18.Add(typeof (IReferenceProvider), obj35);
        Type type36 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver18 = new XmlNamespaceResolver();
        namespaceResolver18.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver18.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver18.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver18.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver18.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver18.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver18.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver18.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver18.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver18 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver18, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider18.Add(type36, (object) xamlTypeResolver18);
        xamlServiceProvider18.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(48, 24)));
        object obj36 = ((IMarkupExtension) resourceExtension34).ProvideValue((IServiceProvider) xamlServiceProvider18);
        ((NavigableElement) label9).set_Style((Style) obj36);
        bindingExtension5.set_Path("Exam.Tantargy");
        BindingBase bindingBase5 = ((IMarkupExtension<BindingBase>) bindingExtension5).ProvideValue((IServiceProvider) null);
        ((BindableObject) label9).SetBinding((BindableProperty) Label.TextProperty, bindingBase5);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label9);
        resourceExtension14.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension35 = resourceExtension14;
        XamlServiceProvider xamlServiceProvider19 = new XamlServiceProvider();
        Type type37 = typeof (IProvideValueTarget);
        object[] objArray19 = new object[0 + 5];
        objArray19[0] = (object) label10;
        objArray19[1] = (object) stackLayout;
        objArray19[2] = (object) scrollView;
        objArray19[3] = (object) grid2;
        objArray19[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider19;
        object obj37 = (object) (valueTargetProvider19 = new SimpleValueTargetProvider(objArray19, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider19.Add(type37, (object) valueTargetProvider19);
        xamlServiceProvider19.Add(typeof (IReferenceProvider), obj37);
        Type type38 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver19 = new XmlNamespaceResolver();
        namespaceResolver19.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver19.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver19.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver19.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver19.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver19.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver19.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver19.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver19.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver19 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver19, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider19.Add(type38, (object) xamlTypeResolver19);
        xamlServiceProvider19.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(50, 24)));
        object obj38 = ((IMarkupExtension) resourceExtension35).ProvideValue((IServiceProvider) xamlServiceProvider19);
        ((NavigableElement) label10).set_Style((Style) obj38);
        translateExtension6.Text = "Exam_Model_Tanar";
        TranslateExtension translateExtension15 = translateExtension6;
        XamlServiceProvider xamlServiceProvider20 = new XamlServiceProvider();
        Type type39 = typeof (IProvideValueTarget);
        object[] objArray20 = new object[0 + 5];
        objArray20[0] = (object) label10;
        objArray20[1] = (object) stackLayout;
        objArray20[2] = (object) scrollView;
        objArray20[3] = (object) grid2;
        objArray20[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider20;
        object obj39 = (object) (valueTargetProvider20 = new SimpleValueTargetProvider(objArray20, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider20.Add(type39, (object) valueTargetProvider20);
        xamlServiceProvider20.Add(typeof (IReferenceProvider), obj39);
        Type type40 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver20 = new XmlNamespaceResolver();
        namespaceResolver20.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver20.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver20.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver20.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver20.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver20.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver20.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver20.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver20.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver20 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver20, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider20.Add(type40, (object) xamlTypeResolver20);
        xamlServiceProvider20.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(50, 70)));
        object obj40 = ((IMarkupExtension) translateExtension15).ProvideValue((IServiceProvider) xamlServiceProvider20);
        label10.set_Text((string) obj40);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label10);
        resourceExtension15.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension36 = resourceExtension15;
        XamlServiceProvider xamlServiceProvider21 = new XamlServiceProvider();
        Type type41 = typeof (IProvideValueTarget);
        object[] objArray21 = new object[0 + 5];
        objArray21[0] = (object) label11;
        objArray21[1] = (object) stackLayout;
        objArray21[2] = (object) scrollView;
        objArray21[3] = (object) grid2;
        objArray21[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider21;
        object obj41 = (object) (valueTargetProvider21 = new SimpleValueTargetProvider(objArray21, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider21.Add(type41, (object) valueTargetProvider21);
        xamlServiceProvider21.Add(typeof (IReferenceProvider), obj41);
        Type type42 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver21 = new XmlNamespaceResolver();
        namespaceResolver21.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver21.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver21.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver21.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver21.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver21.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver21.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver21.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver21.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver21 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver21, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider21.Add(type42, (object) xamlTypeResolver21);
        xamlServiceProvider21.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(51, 24)));
        object obj42 = ((IMarkupExtension) resourceExtension36).ProvideValue((IServiceProvider) xamlServiceProvider21);
        ((NavigableElement) label11).set_Style((Style) obj42);
        bindingExtension6.set_Path("Exam.Tanar");
        BindingBase bindingBase6 = ((IMarkupExtension<BindingBase>) bindingExtension6).ProvideValue((IServiceProvider) null);
        ((BindableObject) label11).SetBinding((BindableProperty) Label.TextProperty, bindingBase6);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label11);
        resourceExtension16.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension37 = resourceExtension16;
        XamlServiceProvider xamlServiceProvider22 = new XamlServiceProvider();
        Type type43 = typeof (IProvideValueTarget);
        object[] objArray22 = new object[0 + 5];
        objArray22[0] = (object) label12;
        objArray22[1] = (object) stackLayout;
        objArray22[2] = (object) scrollView;
        objArray22[3] = (object) grid2;
        objArray22[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider22;
        object obj43 = (object) (valueTargetProvider22 = new SimpleValueTargetProvider(objArray22, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider22.Add(type43, (object) valueTargetProvider22);
        xamlServiceProvider22.Add(typeof (IReferenceProvider), obj43);
        Type type44 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver22 = new XmlNamespaceResolver();
        namespaceResolver22.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver22.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver22.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver22.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver22.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver22.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver22.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver22.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver22.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver22 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver22, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider22.Add(type44, (object) xamlTypeResolver22);
        xamlServiceProvider22.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(53, 24)));
        object obj44 = ((IMarkupExtension) resourceExtension37).ProvideValue((IServiceProvider) xamlServiceProvider22);
        ((NavigableElement) label12).set_Style((Style) obj44);
        translateExtension7.Text = "Exam_Model_SzamonkeresMegnevezese";
        TranslateExtension translateExtension16 = translateExtension7;
        XamlServiceProvider xamlServiceProvider23 = new XamlServiceProvider();
        Type type45 = typeof (IProvideValueTarget);
        object[] objArray23 = new object[0 + 5];
        objArray23[0] = (object) label12;
        objArray23[1] = (object) stackLayout;
        objArray23[2] = (object) scrollView;
        objArray23[3] = (object) grid2;
        objArray23[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider23;
        object obj45 = (object) (valueTargetProvider23 = new SimpleValueTargetProvider(objArray23, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider23.Add(type45, (object) valueTargetProvider23);
        xamlServiceProvider23.Add(typeof (IReferenceProvider), obj45);
        Type type46 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver23 = new XmlNamespaceResolver();
        namespaceResolver23.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver23.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver23.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver23.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver23.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver23.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver23.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver23.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver23.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver23 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver23, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider23.Add(type46, (object) xamlTypeResolver23);
        xamlServiceProvider23.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(53, 70)));
        object obj46 = ((IMarkupExtension) translateExtension16).ProvideValue((IServiceProvider) xamlServiceProvider23);
        label12.set_Text((string) obj46);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label12);
        resourceExtension17.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension38 = resourceExtension17;
        XamlServiceProvider xamlServiceProvider24 = new XamlServiceProvider();
        Type type47 = typeof (IProvideValueTarget);
        object[] objArray24 = new object[0 + 5];
        objArray24[0] = (object) label13;
        objArray24[1] = (object) stackLayout;
        objArray24[2] = (object) scrollView;
        objArray24[3] = (object) grid2;
        objArray24[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider24;
        object obj47 = (object) (valueTargetProvider24 = new SimpleValueTargetProvider(objArray24, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider24.Add(type47, (object) valueTargetProvider24);
        xamlServiceProvider24.Add(typeof (IReferenceProvider), obj47);
        Type type48 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver24 = new XmlNamespaceResolver();
        namespaceResolver24.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver24.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver24.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver24.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver24.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver24.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver24.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver24.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver24.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver24 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver24, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider24.Add(type48, (object) xamlTypeResolver24);
        xamlServiceProvider24.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(54, 24)));
        object obj48 = ((IMarkupExtension) resourceExtension38).ProvideValue((IServiceProvider) xamlServiceProvider24);
        ((NavigableElement) label13).set_Style((Style) obj48);
        bindingExtension7.set_Path("Exam.SzamonkeresMegnevezese");
        BindingBase bindingBase7 = ((IMarkupExtension<BindingBase>) bindingExtension7).ProvideValue((IServiceProvider) null);
        ((BindableObject) label13).SetBinding((BindableProperty) Label.TextProperty, bindingBase7);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label13);
        resourceExtension18.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension39 = resourceExtension18;
        XamlServiceProvider xamlServiceProvider25 = new XamlServiceProvider();
        Type type49 = typeof (IProvideValueTarget);
        object[] objArray25 = new object[0 + 5];
        objArray25[0] = (object) label14;
        objArray25[1] = (object) stackLayout;
        objArray25[2] = (object) scrollView;
        objArray25[3] = (object) grid2;
        objArray25[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider25;
        object obj49 = (object) (valueTargetProvider25 = new SimpleValueTargetProvider(objArray25, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider25.Add(type49, (object) valueTargetProvider25);
        xamlServiceProvider25.Add(typeof (IReferenceProvider), obj49);
        Type type50 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver25 = new XmlNamespaceResolver();
        namespaceResolver25.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver25.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver25.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver25.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver25.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver25.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver25.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver25.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver25.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver25 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver25, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider25.Add(type50, (object) xamlTypeResolver25);
        xamlServiceProvider25.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(56, 24)));
        object obj50 = ((IMarkupExtension) resourceExtension39).ProvideValue((IServiceProvider) xamlServiceProvider25);
        ((NavigableElement) label14).set_Style((Style) obj50);
        translateExtension8.Text = "Exam_Model_SzamonkeresModja";
        TranslateExtension translateExtension17 = translateExtension8;
        XamlServiceProvider xamlServiceProvider26 = new XamlServiceProvider();
        Type type51 = typeof (IProvideValueTarget);
        object[] objArray26 = new object[0 + 5];
        objArray26[0] = (object) label14;
        objArray26[1] = (object) stackLayout;
        objArray26[2] = (object) scrollView;
        objArray26[3] = (object) grid2;
        objArray26[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider26;
        object obj51 = (object) (valueTargetProvider26 = new SimpleValueTargetProvider(objArray26, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider26.Add(type51, (object) valueTargetProvider26);
        xamlServiceProvider26.Add(typeof (IReferenceProvider), obj51);
        Type type52 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver26 = new XmlNamespaceResolver();
        namespaceResolver26.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver26.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver26.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver26.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver26.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver26.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver26.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver26.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver26.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver26 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver26, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider26.Add(type52, (object) xamlTypeResolver26);
        xamlServiceProvider26.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(56, 70)));
        object obj52 = ((IMarkupExtension) translateExtension17).ProvideValue((IServiceProvider) xamlServiceProvider26);
        label14.set_Text((string) obj52);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label14);
        resourceExtension19.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension40 = resourceExtension19;
        XamlServiceProvider xamlServiceProvider27 = new XamlServiceProvider();
        Type type53 = typeof (IProvideValueTarget);
        object[] objArray27 = new object[0 + 5];
        objArray27[0] = (object) label15;
        objArray27[1] = (object) stackLayout;
        objArray27[2] = (object) scrollView;
        objArray27[3] = (object) grid2;
        objArray27[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider27;
        object obj53 = (object) (valueTargetProvider27 = new SimpleValueTargetProvider(objArray27, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider27.Add(type53, (object) valueTargetProvider27);
        xamlServiceProvider27.Add(typeof (IReferenceProvider), obj53);
        Type type54 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver27 = new XmlNamespaceResolver();
        namespaceResolver27.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver27.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver27.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver27.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver27.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver27.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver27.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver27.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver27.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver27 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver27, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider27.Add(type54, (object) xamlTypeResolver27);
        xamlServiceProvider27.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(57, 24)));
        object obj54 = ((IMarkupExtension) resourceExtension40).ProvideValue((IServiceProvider) xamlServiceProvider27);
        ((NavigableElement) label15).set_Style((Style) obj54);
        bindingExtension8.set_Path("Exam.SzamonkeresModja");
        BindingBase bindingBase8 = ((IMarkupExtension<BindingBase>) bindingExtension8).ProvideValue((IServiceProvider) null);
        ((BindableObject) label15).SetBinding((BindableProperty) Label.TextProperty, bindingBase8);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label15);
        resourceExtension20.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension41 = resourceExtension20;
        XamlServiceProvider xamlServiceProvider28 = new XamlServiceProvider();
        Type type55 = typeof (IProvideValueTarget);
        object[] objArray28 = new object[0 + 5];
        objArray28[0] = (object) label16;
        objArray28[1] = (object) stackLayout;
        objArray28[2] = (object) scrollView;
        objArray28[3] = (object) grid2;
        objArray28[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider28;
        object obj55 = (object) (valueTargetProvider28 = new SimpleValueTargetProvider(objArray28, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider28.Add(type55, (object) valueTargetProvider28);
        xamlServiceProvider28.Add(typeof (IReferenceProvider), obj55);
        Type type56 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver28 = new XmlNamespaceResolver();
        namespaceResolver28.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver28.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver28.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver28.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver28.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver28.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver28.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver28.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver28.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver28 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver28, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider28.Add(type56, (object) xamlTypeResolver28);
        xamlServiceProvider28.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(59, 24)));
        object obj56 = ((IMarkupExtension) resourceExtension41).ProvideValue((IServiceProvider) xamlServiceProvider28);
        ((NavigableElement) label16).set_Style((Style) obj56);
        translateExtension9.Text = "Exam_Model_BejelentesDatuma";
        TranslateExtension translateExtension18 = translateExtension9;
        XamlServiceProvider xamlServiceProvider29 = new XamlServiceProvider();
        Type type57 = typeof (IProvideValueTarget);
        object[] objArray29 = new object[0 + 5];
        objArray29[0] = (object) label16;
        objArray29[1] = (object) stackLayout;
        objArray29[2] = (object) scrollView;
        objArray29[3] = (object) grid2;
        objArray29[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider29;
        object obj57 = (object) (valueTargetProvider29 = new SimpleValueTargetProvider(objArray29, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider29.Add(type57, (object) valueTargetProvider29);
        xamlServiceProvider29.Add(typeof (IReferenceProvider), obj57);
        Type type58 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver29 = new XmlNamespaceResolver();
        namespaceResolver29.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver29.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver29.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver29.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver29.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver29.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver29.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver29.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver29.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver29 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver29, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider29.Add(type58, (object) xamlTypeResolver29);
        xamlServiceProvider29.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(59, 70)));
        object obj58 = ((IMarkupExtension) translateExtension18).ProvideValue((IServiceProvider) xamlServiceProvider29);
        label16.set_Text((string) obj58);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label16);
        resourceExtension21.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension42 = resourceExtension21;
        XamlServiceProvider xamlServiceProvider30 = new XamlServiceProvider();
        Type type59 = typeof (IProvideValueTarget);
        object[] objArray30 = new object[0 + 5];
        objArray30[0] = (object) label17;
        objArray30[1] = (object) stackLayout;
        objArray30[2] = (object) scrollView;
        objArray30[3] = (object) grid2;
        objArray30[4] = (object) examsDetailPage;
        SimpleValueTargetProvider valueTargetProvider30;
        object obj59 = (object) (valueTargetProvider30 = new SimpleValueTargetProvider(objArray30, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider30.Add(type59, (object) valueTargetProvider30);
        xamlServiceProvider30.Add(typeof (IReferenceProvider), obj59);
        Type type60 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver30 = new XmlNamespaceResolver();
        namespaceResolver30.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver30.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver30.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver30.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver30.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver30.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver30.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver30.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver30.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver30 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver30, typeof (ExamsDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider30.Add(type60, (object) xamlTypeResolver30);
        xamlServiceProvider30.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(60, 24)));
        object obj60 = ((IMarkupExtension) resourceExtension42).ProvideValue((IServiceProvider) xamlServiceProvider30);
        ((NavigableElement) label17).set_Style((Style) obj60);
        bindingExtension9.set_StringFormat("{0:d}");
        bindingExtension9.set_Path("Exam.BejelentesDatumaLocal");
        BindingBase bindingBase9 = ((IMarkupExtension<BindingBase>) bindingExtension9).ProvideValue((IServiceProvider) null);
        ((BindableObject) label17).SetBinding((BindableProperty) Label.TextProperty, bindingBase9);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label17);
        scrollView.set_Content((View) stackLayout);
        ((ICollection<View>) grid2.get_Children()).Add((View) scrollView);
        ((BindableObject) examsDetailPage).SetValue((BindableProperty) ContentPage.ContentProperty, (object) grid2);
      }
    }

    private void __InitComponentRuntime()
    {
      Xamarin.Forms.Xaml.Extensions.LoadFromXaml<ExamsDetailPage>((M0) this, typeof (ExamsDetailPage));
    }
  }
}
