// Decompiled with JetBrains decompiler
// Type: Ekreta.Mobile.Core.Views.HomeWorksPage
// Assembly: Ekreta.Mobile.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5AA13053-CF9F-480D-A76A-8A5D6C4EE194
// Assembly location: C:\fakepath\\Desktop\Ekreta.Mobile.Core.dll

using Ekreta.Mobile.Core.Controls;
using Ekreta.Mobile.Core.Extensions;
using Ekreta.Mobile.Core.ViewModels;
using FFImageLoading.Forms;
using ImageCircle.Forms.Plugin.Abstractions;
using MvvmCross.Forms.Presenters.Attributes;
using MvvmCross.Forms.Views;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Reflection;
using System.Xml;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Internals;

namespace Ekreta.Mobile.Core.Views
{
  [MvxMasterDetailPagePresentation]
  [XamlFilePath("Views/HomeWorksPage.xaml")]
  [XamlCompilation]
  public class HomeWorksPage : MvxContentPage<HomeWorksViewModel>
  {
    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private MvxContentPage<HomeWorksViewModel> Page;

    public HomeWorksPage()
    {
      base.\u002Ector();
      this.InitializeComponent();
    }

    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private void InitializeComponent()
    {
      ResourceLoader.ResourceLoadingQuery resourceLoadingQuery = new ResourceLoader.ResourceLoadingQuery();
      resourceLoadingQuery.set_AssemblyName(typeof (HomeWorksPage).GetTypeInfo().Assembly.GetName());
      resourceLoadingQuery.set_ResourcePath("Views/HomeWorksPage.xaml");
      resourceLoadingQuery.set_Instance((object) this);
      if (ResourceLoader.CanProvideContentFor(resourceLoadingQuery))
        this.__InitComponentRuntime();
      else if (XamlLoader.get_XamlFileProvider() != null && XamlLoader.get_XamlFileProvider()(((object) this).GetType()) != null)
      {
        this.__InitComponentRuntime();
      }
      else
      {
        TranslateExtension translateExtension1 = new TranslateExtension();
        StaticResourceExtension resourceExtension1 = new StaticResourceExtension();
        BindingExtension bindingExtension1 = new BindingExtension();
        StaticResourceExtension resourceExtension2 = new StaticResourceExtension();
        BindingExtension bindingExtension2 = new BindingExtension();
        BindableToolbarItem bindableToolbarItem = new BindableToolbarItem();
        BindingExtension bindingExtension3 = new BindingExtension();
        TranslateExtension translateExtension2 = new TranslateExtension();
        Setter setter1 = new Setter();
        DataTrigger dataTrigger1 = new DataTrigger(typeof (MvxContentPage));
        BindingExtension bindingExtension4 = new BindingExtension();
        TranslateExtension translateExtension3 = new TranslateExtension();
        Setter setter2 = new Setter();
        DataTrigger dataTrigger2 = new DataTrigger(typeof (MvxContentPage));
        BindingExtension bindingExtension5 = new BindingExtension();
        TranslateExtension translateExtension4 = new TranslateExtension();
        Setter setter3 = new Setter();
        DataTrigger dataTrigger3 = new DataTrigger(typeof (MvxContentPage));
        RowDefinition rowDefinition1 = new RowDefinition();
        RowDefinition rowDefinition2 = new RowDefinition();
        RowDefinition rowDefinition3 = new RowDefinition();
        StaticResourceExtension resourceExtension3 = new StaticResourceExtension();
        ColumnDefinition columnDefinition1 = new ColumnDefinition();
        ColumnDefinition columnDefinition2 = new ColumnDefinition();
        ColumnDefinition columnDefinition3 = new ColumnDefinition();
        BindingExtension bindingExtension6 = new BindingExtension();
        TapGestureRecognizer gestureRecognizer1 = new TapGestureRecognizer();
        CachedImage cachedImage1 = new CachedImage();
        StaticResourceExtension resourceExtension4 = new StaticResourceExtension();
        BindingExtension bindingExtension7 = new BindingExtension();
        Label label1 = new Label();
        StaticResourceExtension resourceExtension5 = new StaticResourceExtension();
        Label label2 = new Label();
        StaticResourceExtension resourceExtension6 = new StaticResourceExtension();
        BindingExtension bindingExtension8 = new BindingExtension();
        Label label3 = new Label();
        StackLayout stackLayout = new StackLayout();
        BindingExtension bindingExtension9 = new BindingExtension();
        BindingExtension bindingExtension10 = new BindingExtension();
        TapGestureRecognizer gestureRecognizer2 = new TapGestureRecognizer();
        CachedImage cachedImage2 = new CachedImage();
        Grid grid1 = new Grid();
        BindingExtension bindingExtension11 = new BindingExtension();
        StaticResourceExtension resourceExtension7 = new StaticResourceExtension();
        TranslateExtension translateExtension5 = new TranslateExtension();
        Label label4 = new Label();
        BindingExtension bindingExtension12 = new BindingExtension();
        Setter setter4 = new Setter();
        DataTrigger dataTrigger4 = new DataTrigger(typeof (Grid));
        StaticResourceExtension resourceExtension8 = new StaticResourceExtension();
        BindingExtension bindingExtension13 = new BindingExtension();
        ReferenceExtension referenceExtension1 = new ReferenceExtension();
        BindingExtension bindingExtension14 = new BindingExtension();
        DataTemplate dataTemplate1 = new DataTemplate();
        ListView listView = new ListView((ListViewCachingStrategy) 1);
        BindingExtension bindingExtension15 = new BindingExtension();
        Setter setter5 = new Setter();
        DataTrigger dataTrigger5 = new DataTrigger(typeof (Grid));
        BindingExtension bindingExtension16 = new BindingExtension();
        Setter setter6 = new Setter();
        DataTrigger dataTrigger6 = new DataTrigger(typeof (Grid));
        TranslateExtension translateExtension6 = new TranslateExtension();
        BindingExtension bindingExtension17 = new BindingExtension();
        EmptyView emptyView = new EmptyView();
        Grid grid2 = new Grid();
        BindingExtension bindingExtension18 = new BindingExtension();
        Setter setter7 = new Setter();
        DataTrigger dataTrigger7 = new DataTrigger(typeof (Grid));
        BindingExtension bindingExtension19 = new BindingExtension();
        BindingExtension bindingExtension20 = new BindingExtension();
        ErrorView errorView = new ErrorView();
        Grid grid3 = new Grid();
        Grid grid4 = new Grid();
        StaticResourceExtension resourceExtension9 = new StaticResourceExtension();
        BindingExtension bindingExtension21 = new BindingExtension();
        StaticResourceExtension resourceExtension10 = new StaticResourceExtension();
        CircleImage circleImage = new CircleImage();
        BindingExtension bindingExtension22 = new BindingExtension();
        BindingExtension bindingExtension23 = new BindingExtension();
        ActivityIndicator activityIndicator = new ActivityIndicator();
        Grid grid5 = new Grid();
        Grid grid6 = new Grid();
        HomeWorksPage homeWorksPage;
        NameScope nameScope = (NameScope) (NameScope.GetNameScope((BindableObject) (homeWorksPage = this)) ?? (INameScope) new NameScope());
        NameScope.SetNameScope((BindableObject) homeWorksPage, (INameScope) nameScope);
        ((INameScope) nameScope).RegisterName("Page", (object) homeWorksPage);
        if (((Element) homeWorksPage).get_StyleId() == null)
          ((Element) homeWorksPage).set_StyleId("Page");
        this.Page = (MvxContentPage<HomeWorksViewModel>) homeWorksPage;
        translateExtension1.Text = "HomeWorks_Page_Title";
        TranslateExtension translateExtension7 = translateExtension1;
        XamlServiceProvider xamlServiceProvider1 = new XamlServiceProvider();
        Type type1 = typeof (IProvideValueTarget);
        object[] objArray1 = new object[0 + 1];
        objArray1[0] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider1;
        object obj1 = (object) (valueTargetProvider1 = new SimpleValueTargetProvider(objArray1, (object) Xamarin.Forms.Page.TitleProperty, (INameScope) nameScope));
        xamlServiceProvider1.Add(type1, (object) valueTargetProvider1);
        xamlServiceProvider1.Add(typeof (IReferenceProvider), obj1);
        Type type2 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver1 = new XmlNamespaceResolver();
        namespaceResolver1.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver1.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver1.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver1.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver1.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver1.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver1.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver1.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver1.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver1.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver1.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver1 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver1, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider1.Add(type2, (object) xamlTypeResolver1);
        xamlServiceProvider1.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(16, 5)));
        object obj2 = ((IMarkupExtension) translateExtension7).ProvideValue((IServiceProvider) xamlServiceProvider1);
        ((Xamarin.Forms.Page) homeWorksPage).set_Title((string) obj2);
        ((BindableObject) homeWorksPage).SetValue((BindableProperty) Xamarin.Forms.PlatformConfiguration.iOSSpecific.Page.UseSafeAreaProperty, (object) true);
        resourceExtension1.set_Key("PageBackgroundColor");
        StaticResourceExtension resourceExtension11 = resourceExtension1;
        XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
        Type type3 = typeof (IProvideValueTarget);
        object[] objArray2 = new object[0 + 1];
        objArray2[0] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider2;
        object obj3 = (object) (valueTargetProvider2 = new SimpleValueTargetProvider(objArray2, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope));
        xamlServiceProvider2.Add(type3, (object) valueTargetProvider2);
        xamlServiceProvider2.Add(typeof (IReferenceProvider), obj3);
        Type type4 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver2 = new XmlNamespaceResolver();
        namespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver2.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver2.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver2.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver2.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver2.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver2.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver2.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver2.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver2.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver2 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver2, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider2.Add(type4, (object) xamlTypeResolver2);
        xamlServiceProvider2.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(19, 5)));
        object obj4 = ((IMarkupExtension) resourceExtension11).ProvideValue((IServiceProvider) xamlServiceProvider2);
        ((VisualElement) homeWorksPage).set_BackgroundColor((Color) obj4);
        bindingExtension1.set_Path("FilterDoneHomeWorksCommand");
        BindingBase bindingBase1 = ((IMarkupExtension<BindingBase>) bindingExtension1).ProvideValue((IServiceProvider) null);
        ((BindableObject) bindableToolbarItem).SetBinding((BindableProperty) MenuItem.CommandProperty, bindingBase1);
        resourceExtension2.set_Key("FilterStateToImageSourceConverter");
        StaticResourceExtension resourceExtension12 = resourceExtension2;
        XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
        Type type5 = typeof (IProvideValueTarget);
        object[] objArray3 = new object[0 + 3];
        objArray3[0] = (object) bindingExtension2;
        objArray3[1] = (object) bindableToolbarItem;
        objArray3[2] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider3;
        object obj5 = (object) (valueTargetProvider3 = new SimpleValueTargetProvider(objArray3, (object) typeof (BindingExtension).GetRuntimeProperty("Converter"), (INameScope) nameScope));
        xamlServiceProvider3.Add(type5, (object) valueTargetProvider3);
        xamlServiceProvider3.Add(typeof (IReferenceProvider), obj5);
        Type type6 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver3 = new XmlNamespaceResolver();
        namespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver3.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver3.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver3.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver3.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver3.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver3.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver3.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver3.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver3.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver3 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver3, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider3.Add(type6, (object) xamlTypeResolver3);
        xamlServiceProvider3.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(27, 13)));
        object obj6 = ((IMarkupExtension) resourceExtension12).ProvideValue((IServiceProvider) xamlServiceProvider3);
        bindingExtension2.set_Converter((IValueConverter) obj6);
        bindingExtension2.set_Path("DoneHomeWorkFilterIsActive");
        BindingBase bindingBase2 = ((IMarkupExtension<BindingBase>) bindingExtension2).ProvideValue((IServiceProvider) null);
        ((BindableObject) bindableToolbarItem).SetBinding((BindableProperty) MenuItem.IconImageSourceProperty, bindingBase2);
        ((BindableObject) bindableToolbarItem).SetValue(BindableToolbarItem.IsVisibleProperty, (object) true);
        ((ICollection<ToolbarItem>) ((Xamarin.Forms.Page) homeWorksPage).get_ToolbarItems()).Add((ToolbarItem) bindableToolbarItem);
        bindingExtension3.set_Path("HasInternetConnection");
        BindingBase bindingBase3 = ((IMarkupExtension<BindingBase>) bindingExtension3).ProvideValue((IServiceProvider) null);
        dataTrigger1.set_Binding(bindingBase3);
        dataTrigger1.set_Value((object) "True");
        setter1.set_Property((BindableProperty) Xamarin.Forms.Page.TitleProperty);
        translateExtension2.Text = "HomeWorks_Page_Title";
        TranslateExtension translateExtension8 = translateExtension2;
        XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
        Type type7 = typeof (IProvideValueTarget);
        object[] objArray4 = new object[0 + 3];
        objArray4[0] = (object) setter1;
        objArray4[1] = (object) dataTrigger1;
        objArray4[2] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider4;
        object obj7 = (object) (valueTargetProvider4 = new SimpleValueTargetProvider(objArray4, (object) typeof (Setter).GetRuntimeProperty("Value"), (INameScope) nameScope));
        xamlServiceProvider4.Add(type7, (object) valueTargetProvider4);
        xamlServiceProvider4.Add(typeof (IReferenceProvider), obj7);
        Type type8 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver4 = new XmlNamespaceResolver();
        namespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver4.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver4.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver4.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver4.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver4.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver4.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver4.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver4.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver4.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver4 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver4, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider4.Add(type8, (object) xamlTypeResolver4);
        xamlServiceProvider4.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(35, 38)));
        object obj8 = ((IMarkupExtension) translateExtension8).ProvideValue((IServiceProvider) xamlServiceProvider4);
        setter1.set_Value(obj8);
        ((ICollection<Setter>) dataTrigger1.get_Setters()).Add(setter1);
        ((ICollection<TriggerBase>) ((BindableObject) homeWorksPage).GetValue((BindableProperty) VisualElement.TriggersProperty)).Add((TriggerBase) dataTrigger1);
        bindingExtension4.set_Path("HasInternetConnection");
        BindingBase bindingBase4 = ((IMarkupExtension<BindingBase>) bindingExtension4).ProvideValue((IServiceProvider) null);
        dataTrigger2.set_Binding(bindingBase4);
        dataTrigger2.set_Value((object) "False");
        setter2.set_Property((BindableProperty) Xamarin.Forms.Page.TitleProperty);
        translateExtension3.Text = "HomeWorks_Page_Offline_Title";
        TranslateExtension translateExtension9 = translateExtension3;
        XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
        Type type9 = typeof (IProvideValueTarget);
        object[] objArray5 = new object[0 + 3];
        objArray5[0] = (object) setter2;
        objArray5[1] = (object) dataTrigger2;
        objArray5[2] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider5;
        object obj9 = (object) (valueTargetProvider5 = new SimpleValueTargetProvider(objArray5, (object) typeof (Setter).GetRuntimeProperty("Value"), (INameScope) nameScope));
        xamlServiceProvider5.Add(type9, (object) valueTargetProvider5);
        xamlServiceProvider5.Add(typeof (IReferenceProvider), obj9);
        Type type10 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver5 = new XmlNamespaceResolver();
        namespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver5.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver5.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver5.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver5.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver5.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver5.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver5.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver5.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver5.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver5 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver5, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider5.Add(type10, (object) xamlTypeResolver5);
        xamlServiceProvider5.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(41, 38)));
        object obj10 = ((IMarkupExtension) translateExtension9).ProvideValue((IServiceProvider) xamlServiceProvider5);
        setter2.set_Value(obj10);
        ((ICollection<Setter>) dataTrigger2.get_Setters()).Add(setter2);
        ((ICollection<TriggerBase>) ((BindableObject) homeWorksPage).GetValue((BindableProperty) VisualElement.TriggersProperty)).Add((TriggerBase) dataTrigger2);
        bindingExtension5.set_Path("IsOffline");
        BindingBase bindingBase5 = ((IMarkupExtension<BindingBase>) bindingExtension5).ProvideValue((IServiceProvider) null);
        dataTrigger3.set_Binding(bindingBase5);
        dataTrigger3.set_Value((object) "True");
        setter3.set_Property((BindableProperty) Xamarin.Forms.Page.TitleProperty);
        translateExtension4.Text = "HomeWorks_Page_Offline_Title";
        TranslateExtension translateExtension10 = translateExtension4;
        XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
        Type type11 = typeof (IProvideValueTarget);
        object[] objArray6 = new object[0 + 3];
        objArray6[0] = (object) setter3;
        objArray6[1] = (object) dataTrigger3;
        objArray6[2] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider6;
        object obj11 = (object) (valueTargetProvider6 = new SimpleValueTargetProvider(objArray6, (object) typeof (Setter).GetRuntimeProperty("Value"), (INameScope) nameScope));
        xamlServiceProvider6.Add(type11, (object) valueTargetProvider6);
        xamlServiceProvider6.Add(typeof (IReferenceProvider), obj11);
        Type type12 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver6 = new XmlNamespaceResolver();
        namespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver6.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver6.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver6.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver6.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver6.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver6.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver6.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver6.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver6.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver6 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver6, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider6.Add(type12, (object) xamlTypeResolver6);
        xamlServiceProvider6.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(47, 38)));
        object obj12 = ((IMarkupExtension) translateExtension10).ProvideValue((IServiceProvider) xamlServiceProvider6);
        setter3.set_Value(obj12);
        ((ICollection<Setter>) dataTrigger3.get_Setters()).Add(setter3);
        ((ICollection<TriggerBase>) ((BindableObject) homeWorksPage).GetValue((BindableProperty) VisualElement.TriggersProperty)).Add((TriggerBase) dataTrigger3);
        ((BindableObject) rowDefinition1).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid6).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition1);
        ((BindableObject) rowDefinition2).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid6).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition2);
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid6).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition3);
        resourceExtension3.set_Key("NavigationArrowContentHolderMargin");
        StaticResourceExtension resourceExtension13 = resourceExtension3;
        XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
        Type type13 = typeof (IProvideValueTarget);
        object[] objArray7 = new object[0 + 3];
        objArray7[0] = (object) grid1;
        objArray7[1] = (object) grid6;
        objArray7[2] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider7;
        object obj13 = (object) (valueTargetProvider7 = new SimpleValueTargetProvider(objArray7, (object) View.MarginProperty, (INameScope) nameScope));
        xamlServiceProvider7.Add(type13, (object) valueTargetProvider7);
        xamlServiceProvider7.Add(typeof (IReferenceProvider), obj13);
        Type type14 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver7 = new XmlNamespaceResolver();
        namespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver7.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver7.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver7.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver7.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver7.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver7.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver7.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver7.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver7.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver7 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver7, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider7.Add(type14, (object) xamlTypeResolver7);
        xamlServiceProvider7.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(57, 15)));
        object obj14 = ((IMarkupExtension) resourceExtension13).ProvideValue((IServiceProvider) xamlServiceProvider7);
        ((View) grid1).set_Margin((Thickness) obj14);
        ((BindableObject) columnDefinition1).SetValue((BindableProperty) ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<ColumnDefinition>) ((BindableObject) grid1).GetValue((BindableProperty) Grid.ColumnDefinitionsProperty)).Add(columnDefinition1);
        ((BindableObject) columnDefinition2).SetValue((BindableProperty) ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
        ((DefinitionCollection<ColumnDefinition>) ((BindableObject) grid1).GetValue((BindableProperty) Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
        ((BindableObject) columnDefinition3).SetValue((BindableProperty) ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<ColumnDefinition>) ((BindableObject) grid1).GetValue((BindableProperty) Grid.ColumnDefinitionsProperty)).Add(columnDefinition3);
        ((BindableObject) cachedImage1).SetValue((BindableProperty) Grid.ColumnProperty, (object) 0);
        ((BindableObject) cachedImage1).SetValue((BindableProperty) CachedImage.DownsampleToViewSizeProperty, (object) true);
        ((BindableObject) cachedImage1).SetValue((BindableProperty) VisualElement.HeightRequestProperty, (object) 40.0);
        ((BindableObject) cachedImage1).SetValue((BindableProperty) CachedImage.SourceProperty, new ImageSourceConverter().ConvertFromInvariantString("resource://Ekreta.Mobile.Core.Images.ArrowLeft.png?assembly=Ekreta.Mobile.Core"));
        ((BindableObject) cachedImage1).SetValue((BindableProperty) VisualElement.WidthRequestProperty, (object) 40.0);
        bindingExtension6.set_Path("PreviousWeekCommand");
        BindingBase bindingBase6 = ((IMarkupExtension<BindingBase>) bindingExtension6).ProvideValue((IServiceProvider) null);
        ((BindableObject) gestureRecognizer1).SetBinding((BindableProperty) TapGestureRecognizer.CommandProperty, bindingBase6);
        ((ICollection<IGestureRecognizer>) ((View) cachedImage1).get_GestureRecognizers()).Add((IGestureRecognizer) gestureRecognizer1);
        ((ICollection<View>) grid1.get_Children()).Add((View) cachedImage1);
        ((BindableObject) stackLayout).SetValue((BindableProperty) Grid.ColumnProperty, (object) 1);
        ((BindableObject) stackLayout).SetValue((BindableProperty) View.HorizontalOptionsProperty, (object) (LayoutOptions) LayoutOptions.Center);
        ((BindableObject) stackLayout).SetValue((BindableProperty) StackLayout.OrientationProperty, (object) (StackOrientation) 1);
        ((BindableObject) stackLayout).SetValue((BindableProperty) View.VerticalOptionsProperty, (object) (LayoutOptions) LayoutOptions.Center);
        resourceExtension4.set_Key("ListItemGroupTitleStyle");
        StaticResourceExtension resourceExtension14 = resourceExtension4;
        XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
        Type type15 = typeof (IProvideValueTarget);
        object[] objArray8 = new object[0 + 5];
        objArray8[0] = (object) label1;
        objArray8[1] = (object) stackLayout;
        objArray8[2] = (object) grid1;
        objArray8[3] = (object) grid6;
        objArray8[4] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider8;
        object obj15 = (object) (valueTargetProvider8 = new SimpleValueTargetProvider(objArray8, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider8.Add(type15, (object) valueTargetProvider8);
        xamlServiceProvider8.Add(typeof (IReferenceProvider), obj15);
        Type type16 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver8 = new XmlNamespaceResolver();
        namespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver8.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver8.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver8.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver8.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver8.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver8.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver8.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver8.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver8.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver8 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver8, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider8.Add(type16, (object) xamlTypeResolver8);
        xamlServiceProvider8.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(80, 24)));
        object obj16 = ((IMarkupExtension) resourceExtension14).ProvideValue((IServiceProvider) xamlServiceProvider8);
        ((NavigableElement) label1).set_Style((Style) obj16);
        bindingExtension7.set_StringFormat("{0:MMM dd.}");
        bindingExtension7.set_Path("FirstDayOfWeek");
        BindingBase bindingBase7 = ((IMarkupExtension<BindingBase>) bindingExtension7).ProvideValue((IServiceProvider) null);
        ((BindableObject) label1).SetBinding((BindableProperty) Label.TextProperty, bindingBase7);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label1);
        resourceExtension5.set_Key("ListItemGroupTitleStyle");
        StaticResourceExtension resourceExtension15 = resourceExtension5;
        XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
        Type type17 = typeof (IProvideValueTarget);
        object[] objArray9 = new object[0 + 5];
        objArray9[0] = (object) label2;
        objArray9[1] = (object) stackLayout;
        objArray9[2] = (object) grid1;
        objArray9[3] = (object) grid6;
        objArray9[4] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider9;
        object obj17 = (object) (valueTargetProvider9 = new SimpleValueTargetProvider(objArray9, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider9.Add(type17, (object) valueTargetProvider9);
        xamlServiceProvider9.Add(typeof (IReferenceProvider), obj17);
        Type type18 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver9 = new XmlNamespaceResolver();
        namespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver9.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver9.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver9.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver9.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver9.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver9.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver9.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver9.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver9.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver9 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver9, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider9.Add(type18, (object) xamlTypeResolver9);
        xamlServiceProvider9.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(81, 24)));
        object obj18 = ((IMarkupExtension) resourceExtension15).ProvideValue((IServiceProvider) xamlServiceProvider9);
        ((NavigableElement) label2).set_Style((Style) obj18);
        ((BindableObject) label2).SetValue((BindableProperty) Label.TextProperty, (object) " - ");
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label2);
        resourceExtension6.set_Key("ListItemGroupTitleStyle");
        StaticResourceExtension resourceExtension16 = resourceExtension6;
        XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
        Type type19 = typeof (IProvideValueTarget);
        object[] objArray10 = new object[0 + 5];
        objArray10[0] = (object) label3;
        objArray10[1] = (object) stackLayout;
        objArray10[2] = (object) grid1;
        objArray10[3] = (object) grid6;
        objArray10[4] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider10;
        object obj19 = (object) (valueTargetProvider10 = new SimpleValueTargetProvider(objArray10, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider10.Add(type19, (object) valueTargetProvider10);
        xamlServiceProvider10.Add(typeof (IReferenceProvider), obj19);
        Type type20 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver10 = new XmlNamespaceResolver();
        namespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver10.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver10.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver10.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver10.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver10.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver10.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver10.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver10.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver10.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver10 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver10, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider10.Add(type20, (object) xamlTypeResolver10);
        xamlServiceProvider10.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(82, 24)));
        object obj20 = ((IMarkupExtension) resourceExtension16).ProvideValue((IServiceProvider) xamlServiceProvider10);
        ((NavigableElement) label3).set_Style((Style) obj20);
        bindingExtension8.set_StringFormat("{0:MMM dd.}");
        bindingExtension8.set_Path("LastDayOfWeekDisplay");
        BindingBase bindingBase8 = ((IMarkupExtension<BindingBase>) bindingExtension8).ProvideValue((IServiceProvider) null);
        ((BindableObject) label3).SetBinding((BindableProperty) Label.TextProperty, bindingBase8);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label3);
        ((ICollection<View>) grid1.get_Children()).Add((View) stackLayout);
        ((BindableObject) cachedImage2).SetValue((BindableProperty) Grid.ColumnProperty, (object) 2);
        ((BindableObject) cachedImage2).SetValue((BindableProperty) CachedImage.DownsampleToViewSizeProperty, (object) true);
        ((BindableObject) cachedImage2).SetValue((BindableProperty) VisualElement.HeightRequestProperty, (object) 40.0);
        bindingExtension9.set_Path("HasNextWeek");
        BindingBase bindingBase9 = ((IMarkupExtension<BindingBase>) bindingExtension9).ProvideValue((IServiceProvider) null);
        ((BindableObject) cachedImage2).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase9);
        ((BindableObject) cachedImage2).SetValue((BindableProperty) CachedImage.SourceProperty, new ImageSourceConverter().ConvertFromInvariantString("resource://Ekreta.Mobile.Core.Images.ArrowRight.png?assembly=Ekreta.Mobile.Core"));
        ((BindableObject) cachedImage2).SetValue((BindableProperty) VisualElement.WidthRequestProperty, (object) 40.0);
        bindingExtension10.set_Path("NextWeekCommand");
        BindingBase bindingBase10 = ((IMarkupExtension<BindingBase>) bindingExtension10).ProvideValue((IServiceProvider) null);
        ((BindableObject) gestureRecognizer2).SetBinding((BindableProperty) TapGestureRecognizer.CommandProperty, bindingBase10);
        ((ICollection<IGestureRecognizer>) ((View) cachedImage2).get_GestureRecognizers()).Add((IGestureRecognizer) gestureRecognizer2);
        ((ICollection<View>) grid1.get_Children()).Add((View) cachedImage2);
        ((ICollection<View>) grid6.get_Children()).Add((View) grid1);
        ((BindableObject) label4).SetValue((BindableProperty) Grid.RowProperty, (object) 1);
        Label label5 = label4;
        // ISSUE: variable of the null type
        __Null fontSizeProperty = Label.FontSizeProperty;
        FontSizeConverter fontSizeConverter = new FontSizeConverter();
        XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
        Type type21 = typeof (IProvideValueTarget);
        object[] objArray11 = new object[0 + 3];
        objArray11[0] = (object) label4;
        objArray11[1] = (object) grid6;
        objArray11[2] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider11;
        object obj21 = (object) (valueTargetProvider11 = new SimpleValueTargetProvider(objArray11, (object) Label.FontSizeProperty, (INameScope) nameScope));
        xamlServiceProvider11.Add(type21, (object) valueTargetProvider11);
        xamlServiceProvider11.Add(typeof (IReferenceProvider), obj21);
        Type type22 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver11 = new XmlNamespaceResolver();
        namespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver11.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver11.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver11.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver11.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver11.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver11.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver11.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver11.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver11.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver11 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver11, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider11.Add(type22, (object) xamlTypeResolver11);
        xamlServiceProvider11.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(99, 13)));
        object obj22 = ((IExtendedTypeConverter) fontSizeConverter).ConvertFromInvariantString("12", (IServiceProvider) xamlServiceProvider11);
        ((BindableObject) label5).SetValue((BindableProperty) fontSizeProperty, obj22);
        ((BindableObject) label4).SetValue((BindableProperty) Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
        bindingExtension11.set_Path("DoneHomeWorkFilterIsActive");
        BindingBase bindingBase11 = ((IMarkupExtension<BindingBase>) bindingExtension11).ProvideValue((IServiceProvider) null);
        ((BindableObject) label4).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase11);
        resourceExtension7.set_Key("ListItemGroupTitleStyle");
        StaticResourceExtension resourceExtension17 = resourceExtension7;
        XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
        Type type23 = typeof (IProvideValueTarget);
        object[] objArray12 = new object[0 + 3];
        objArray12[0] = (object) label4;
        objArray12[1] = (object) grid6;
        objArray12[2] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider12;
        object obj23 = (object) (valueTargetProvider12 = new SimpleValueTargetProvider(objArray12, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider12.Add(type23, (object) valueTargetProvider12);
        xamlServiceProvider12.Add(typeof (IReferenceProvider), obj23);
        Type type24 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver12 = new XmlNamespaceResolver();
        namespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver12.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver12.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver12.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver12.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver12.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver12.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver12.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver12.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver12.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver12 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver12, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider12.Add(type24, (object) xamlTypeResolver12);
        xamlServiceProvider12.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(102, 13)));
        object obj24 = ((IMarkupExtension) resourceExtension17).ProvideValue((IServiceProvider) xamlServiceProvider12);
        ((NavigableElement) label4).set_Style((Style) obj24);
        translateExtension5.Text = "HomeWorks_Page_Filter_Active";
        TranslateExtension translateExtension11 = translateExtension5;
        XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
        Type type25 = typeof (IProvideValueTarget);
        object[] objArray13 = new object[0 + 3];
        objArray13[0] = (object) label4;
        objArray13[1] = (object) grid6;
        objArray13[2] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider13;
        object obj25 = (object) (valueTargetProvider13 = new SimpleValueTargetProvider(objArray13, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider13.Add(type25, (object) valueTargetProvider13);
        xamlServiceProvider13.Add(typeof (IReferenceProvider), obj25);
        Type type26 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver13 = new XmlNamespaceResolver();
        namespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver13.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver13.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver13.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver13.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver13.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver13.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver13.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver13.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver13.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver13 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver13, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider13.Add(type26, (object) xamlTypeResolver13);
        xamlServiceProvider13.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(103, 13)));
        object obj26 = ((IMarkupExtension) translateExtension11).ProvideValue((IServiceProvider) xamlServiceProvider13);
        label4.set_Text((string) obj26);
        ((ICollection<View>) grid6.get_Children()).Add((View) label4);
        ((BindableObject) grid4).SetValue((BindableProperty) Grid.RowProperty, (object) 2);
        bindingExtension12.set_Path("IsLoading");
        BindingBase bindingBase12 = ((IMarkupExtension<BindingBase>) bindingExtension12).ProvideValue((IServiceProvider) null);
        dataTrigger4.set_Binding(bindingBase12);
        dataTrigger4.set_Value((object) "True");
        setter4.set_Property((BindableProperty) VisualElement.IsVisibleProperty);
        setter4.set_Value((object) "False");
        setter4.set_Value(new VisualElement.VisibilityConverter().ConvertFromInvariantString("False"));
        ((ICollection<Setter>) dataTrigger4.get_Setters()).Add(setter4);
        ((ICollection<TriggerBase>) ((BindableObject) grid4).GetValue((BindableProperty) VisualElement.TriggersProperty)).Add((TriggerBase) dataTrigger4);
        ((BindableObject) listView).SetValue((BindableProperty) VisualElement.BackgroundColorProperty, (object) (Color) Color.Transparent);
        resourceExtension8.set_Key("ListViewGroupHeaderTemplate");
        StaticResourceExtension resourceExtension18 = resourceExtension8;
        XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
        Type type27 = typeof (IProvideValueTarget);
        object[] objArray14 = new object[0 + 4];
        objArray14[0] = (object) listView;
        objArray14[1] = (object) grid4;
        objArray14[2] = (object) grid6;
        objArray14[3] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider14;
        object obj27 = (object) (valueTargetProvider14 = new SimpleValueTargetProvider(objArray14, (object) ListView.GroupHeaderTemplateProperty, (INameScope) nameScope));
        xamlServiceProvider14.Add(type27, (object) valueTargetProvider14);
        xamlServiceProvider14.Add(typeof (IReferenceProvider), obj27);
        Type type28 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver14 = new XmlNamespaceResolver();
        namespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver14.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver14.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver14.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver14.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver14.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver14.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver14.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver14.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver14.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver14 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver14, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider14.Add(type28, (object) xamlTypeResolver14);
        xamlServiceProvider14.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(117, 17)));
        object obj28 = ((IMarkupExtension) resourceExtension18).ProvideValue((IServiceProvider) xamlServiceProvider14);
        listView.set_GroupHeaderTemplate((DataTemplate) obj28);
        ((BindableObject) listView).SetValue((BindableProperty) ListView.HasUnevenRowsProperty, (object) true);
        ((BindableObject) listView).SetValue((BindableProperty) ListView.IsGroupingEnabledProperty, (object) true);
        bindingExtension13.set_Path("HomeWorks");
        BindingBase bindingBase13 = ((IMarkupExtension<BindingBase>) bindingExtension13).ProvideValue((IServiceProvider) null);
        ((BindableObject) listView).SetBinding((BindableProperty) ItemsView<Cell>.ItemsSourceProperty, bindingBase13);
        bindingExtension14.set_Mode((BindingMode) 1);
        referenceExtension1.set_Name("Page");
        ReferenceExtension referenceExtension2 = referenceExtension1;
        XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
        Type type29 = typeof (IProvideValueTarget);
        object[] objArray15 = new object[0 + 5];
        objArray15[0] = (object) bindingExtension14;
        objArray15[1] = (object) listView;
        objArray15[2] = (object) grid4;
        objArray15[3] = (object) grid6;
        objArray15[4] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider15;
        object obj29 = (object) (valueTargetProvider15 = new SimpleValueTargetProvider(objArray15, (object) typeof (BindingExtension).GetRuntimeProperty("Source"), (INameScope) nameScope));
        xamlServiceProvider15.Add(type29, (object) valueTargetProvider15);
        xamlServiceProvider15.Add(typeof (IReferenceProvider), obj29);
        Type type30 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver15 = new XmlNamespaceResolver();
        namespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver15.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver15.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver15.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver15.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver15.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver15.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver15.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver15.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver15.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver15 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver15, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider15.Add(type30, (object) xamlTypeResolver15);
        xamlServiceProvider15.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(121, 17)));
        object obj30 = ((IMarkupExtension) referenceExtension2).ProvideValue((IServiceProvider) xamlServiceProvider15);
        bindingExtension14.set_Source(obj30);
        bindingExtension14.set_Path("ViewModel.SelectedItem");
        BindingBase bindingBase14 = ((IMarkupExtension<BindingBase>) bindingExtension14).ProvideValue((IServiceProvider) null);
        ((BindableObject) listView).SetBinding((BindableProperty) ListView.SelectedItemProperty, bindingBase14);
        DataTemplate dataTemplate2 = dataTemplate1;
        // ISSUE: object of a compiler-generated type is created
        // ISSUE: variable of a compiler-generated type
        HomeWorksPage.\u003CInitializeComponent\u003E_anonXamlCDataTemplate_18 xamlCdataTemplate18 = new HomeWorksPage.\u003CInitializeComponent\u003E_anonXamlCDataTemplate_18();
        object[] objArray16 = new object[0 + 5];
        objArray16[0] = (object) dataTemplate1;
        objArray16[1] = (object) listView;
        objArray16[2] = (object) grid4;
        objArray16[3] = (object) grid6;
        objArray16[4] = (object) homeWorksPage;
        // ISSUE: reference to a compiler-generated field
        xamlCdataTemplate18.parentValues = objArray16;
        // ISSUE: reference to a compiler-generated field
        xamlCdataTemplate18.root = homeWorksPage;
        // ISSUE: reference to a compiler-generated method
        Func<object> func = new Func<object>(xamlCdataTemplate18.LoadDataTemplate);
        ((IDataTemplate) dataTemplate2).set_LoadTemplate(func);
        ((BindableObject) listView).SetValue((BindableProperty) ItemsView<Cell>.ItemTemplateProperty, (object) dataTemplate1);
        ((ICollection<View>) grid4.get_Children()).Add((View) listView);
        ((BindableObject) grid2).SetValue((BindableProperty) VisualElement.InputTransparentProperty, (object) true);
        ((BindableObject) grid2).SetValue((BindableProperty) VisualElement.IsVisibleProperty, new VisualElement.VisibilityConverter().ConvertFromInvariantString("True"));
        bindingExtension15.set_Path("IsLoading");
        BindingBase bindingBase15 = ((IMarkupExtension<BindingBase>) bindingExtension15).ProvideValue((IServiceProvider) null);
        dataTrigger5.set_Binding(bindingBase15);
        dataTrigger5.set_Value((object) "False");
        setter5.set_Property((BindableProperty) VisualElement.IsVisibleProperty);
        setter5.set_Value((object) "True");
        setter5.set_Value(new VisualElement.VisibilityConverter().ConvertFromInvariantString("True"));
        ((ICollection<Setter>) dataTrigger5.get_Setters()).Add(setter5);
        ((ICollection<TriggerBase>) ((BindableObject) grid2).GetValue((BindableProperty) VisualElement.TriggersProperty)).Add((TriggerBase) dataTrigger5);
        bindingExtension16.set_Path("IsError");
        BindingBase bindingBase16 = ((IMarkupExtension<BindingBase>) bindingExtension16).ProvideValue((IServiceProvider) null);
        dataTrigger6.set_Binding(bindingBase16);
        dataTrigger6.set_Value((object) "True");
        setter6.set_Property((BindableProperty) VisualElement.IsVisibleProperty);
        setter6.set_Value((object) "False");
        setter6.set_Value(new VisualElement.VisibilityConverter().ConvertFromInvariantString("False"));
        ((ICollection<Setter>) dataTrigger6.get_Setters()).Add(setter6);
        ((ICollection<TriggerBase>) ((BindableObject) grid2).GetValue((BindableProperty) VisualElement.TriggersProperty)).Add((TriggerBase) dataTrigger6);
        translateExtension6.Text = "HomeWorks_ListIsEmpty";
        TranslateExtension translateExtension12 = translateExtension6;
        XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
        Type type31 = typeof (IProvideValueTarget);
        object[] objArray17 = new object[0 + 5];
        objArray17[0] = (object) emptyView;
        objArray17[1] = (object) grid2;
        objArray17[2] = (object) grid4;
        objArray17[3] = (object) grid6;
        objArray17[4] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider16;
        object obj31 = (object) (valueTargetProvider16 = new SimpleValueTargetProvider(objArray17, (object) EmptyView.TitleProperty, (INameScope) nameScope));
        xamlServiceProvider16.Add(type31, (object) valueTargetProvider16);
        xamlServiceProvider16.Add(typeof (IReferenceProvider), obj31);
        Type type32 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver16 = new XmlNamespaceResolver();
        namespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver16.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver16.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver16.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver16.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver16.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver16.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver16.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver16.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver16.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver16 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver16, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider16.Add(type32, (object) xamlTypeResolver16);
        xamlServiceProvider16.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(196, 21)));
        object obj32 = ((IMarkupExtension) translateExtension12).ProvideValue((IServiceProvider) xamlServiceProvider16);
        emptyView.Title = (string) obj32;
        ((BindableObject) emptyView).SetValue((BindableProperty) View.MarginProperty, (object) new Thickness(0.0, -12.0, 0.0, 0.0));
        bindingExtension17.set_Path("HomeWorks.Count");
        BindingBase bindingBase17 = ((IMarkupExtension<BindingBase>) bindingExtension17).ProvideValue((IServiceProvider) null);
        ((BindableObject) emptyView).SetBinding((BindableProperty) BindableObject.BindingContextProperty, bindingBase17);
        ((BindableObject) emptyView).SetValue(EmptyView.ImageProperty, (object) "resource://Ekreta.Mobile.Core.Images.KretaMan_smile.png?assembly=Ekreta.Mobile.Core");
        ((BindableObject) emptyView).SetValue(EmptyView.IsSubtitleVisibleProperty, (object) false);
        ((ICollection<View>) grid2.get_Children()).Add((View) emptyView);
        ((ICollection<View>) grid4.get_Children()).Add((View) grid2);
        ((BindableObject) grid3).SetValue((BindableProperty) VisualElement.IsVisibleProperty, new VisualElement.VisibilityConverter().ConvertFromInvariantString("False"));
        bindingExtension18.set_Path("IsError");
        BindingBase bindingBase18 = ((IMarkupExtension<BindingBase>) bindingExtension18).ProvideValue((IServiceProvider) null);
        dataTrigger7.set_Binding(bindingBase18);
        dataTrigger7.set_Value((object) "True");
        setter7.set_Property((BindableProperty) VisualElement.IsVisibleProperty);
        setter7.set_Value((object) "True");
        setter7.set_Value(new VisualElement.VisibilityConverter().ConvertFromInvariantString("True"));
        ((ICollection<Setter>) dataTrigger7.get_Setters()).Add(setter7);
        ((ICollection<TriggerBase>) ((BindableObject) grid3).GetValue((BindableProperty) VisualElement.TriggersProperty)).Add((TriggerBase) dataTrigger7);
        bindingExtension19.set_Path("ErrorTitle");
        BindingBase bindingBase19 = ((IMarkupExtension<BindingBase>) bindingExtension19).ProvideValue((IServiceProvider) null);
        ((BindableObject) errorView).SetBinding(ErrorView.TitleProperty, bindingBase19);
        ((BindableObject) errorView).SetValue((BindableProperty) View.MarginProperty, (object) new Thickness(0.0, -12.0, 0.0, 0.0));
        bindingExtension20.set_Path("ErrorSubtitle");
        BindingBase bindingBase20 = ((IMarkupExtension<BindingBase>) bindingExtension20).ProvideValue((IServiceProvider) null);
        ((BindableObject) errorView).SetBinding(ErrorView.SubtitleProperty, bindingBase20);
        ((ICollection<View>) grid3.get_Children()).Add((View) errorView);
        ((ICollection<View>) grid4.get_Children()).Add((View) grid3);
        ((ICollection<View>) grid6.get_Children()).Add((View) grid4);
        ((BindableObject) grid5).SetValue((BindableProperty) Grid.RowSpanProperty, (object) 2);
        resourceExtension9.set_Key("OverlayColor");
        StaticResourceExtension resourceExtension19 = resourceExtension9;
        XamlServiceProvider xamlServiceProvider17 = new XamlServiceProvider();
        Type type33 = typeof (IProvideValueTarget);
        object[] objArray18 = new object[0 + 3];
        objArray18[0] = (object) grid5;
        objArray18[1] = (object) grid6;
        objArray18[2] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider17;
        object obj33 = (object) (valueTargetProvider17 = new SimpleValueTargetProvider(objArray18, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope));
        xamlServiceProvider17.Add(type33, (object) valueTargetProvider17);
        xamlServiceProvider17.Add(typeof (IReferenceProvider), obj33);
        Type type34 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver17 = new XmlNamespaceResolver();
        namespaceResolver17.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver17.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver17.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver17.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver17.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver17.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver17.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver17.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver17.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver17.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver17.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver17 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver17, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider17.Add(type34, (object) xamlTypeResolver17);
        xamlServiceProvider17.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(219, 13)));
        object obj34 = ((IMarkupExtension) resourceExtension19).ProvideValue((IServiceProvider) xamlServiceProvider17);
        ((VisualElement) grid5).set_BackgroundColor((Color) obj34);
        bindingExtension21.set_Path("IsLoading");
        BindingBase bindingBase21 = ((IMarkupExtension<BindingBase>) bindingExtension21).ProvideValue((IServiceProvider) null);
        ((BindableObject) grid5).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase21);
        ((BindableObject) circleImage).SetValue((BindableProperty) CircleImage.FillColorProperty, (object) (Color) Color.White);
        resourceExtension10.set_Key("ListItemIconStyle");
        StaticResourceExtension resourceExtension20 = resourceExtension10;
        XamlServiceProvider xamlServiceProvider18 = new XamlServiceProvider();
        Type type35 = typeof (IProvideValueTarget);
        object[] objArray19 = new object[0 + 4];
        objArray19[0] = (object) circleImage;
        objArray19[1] = (object) grid5;
        objArray19[2] = (object) grid6;
        objArray19[3] = (object) homeWorksPage;
        SimpleValueTargetProvider valueTargetProvider18;
        object obj35 = (object) (valueTargetProvider18 = new SimpleValueTargetProvider(objArray19, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider18.Add(type35, (object) valueTargetProvider18);
        xamlServiceProvider18.Add(typeof (IReferenceProvider), obj35);
        Type type36 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver18 = new XmlNamespaceResolver();
        namespaceResolver18.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver18.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver18.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver18.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver18.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver18.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver18.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver18.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver18.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver18.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver18.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver18 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver18, typeof (HomeWorksPage).GetTypeInfo().Assembly);
        xamlServiceProvider18.Add(type36, (object) xamlTypeResolver18);
        xamlServiceProvider18.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(221, 56)));
        object obj36 = ((IMarkupExtension) resourceExtension20).ProvideValue((IServiceProvider) xamlServiceProvider18);
        ((NavigableElement) circleImage).set_Style((Style) obj36);
        ((ICollection<View>) grid5.get_Children()).Add((View) circleImage);
        bindingExtension22.set_Path("IsLoading");
        BindingBase bindingBase22 = ((IMarkupExtension<BindingBase>) bindingExtension22).ProvideValue((IServiceProvider) null);
        ((BindableObject) activityIndicator).SetBinding((BindableProperty) ActivityIndicator.IsRunningProperty, bindingBase22);
        bindingExtension23.set_Path("IsLoading");
        BindingBase bindingBase23 = ((IMarkupExtension<BindingBase>) bindingExtension23).ProvideValue((IServiceProvider) null);
        ((BindableObject) activityIndicator).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase23);
        ((ICollection<View>) grid5.get_Children()).Add((View) activityIndicator);
        ((ICollection<View>) grid6.get_Children()).Add((View) grid5);
        ((BindableObject) homeWorksPage).SetValue((BindableProperty) ContentPage.ContentProperty, (object) grid6);
      }
    }

    private void __InitComponentRuntime()
    {
      Xamarin.Forms.Xaml.Extensions.LoadFromXaml<HomeWorksPage>((M0) this, typeof (HomeWorksPage));
      this.Page = (MvxContentPage<HomeWorksViewModel>) NameScopeExtensions.FindByName<MvxContentPage<HomeWorksViewModel>>((Element) this, "Page");
    }
  }
}
