// Decompiled with JetBrains decompiler
// Type: Ekreta.Mobile.Core.Views.MasterPage
// Assembly: Ekreta.Mobile.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5AA13053-CF9F-480D-A76A-8A5D6C4EE194
// Assembly location: C:\fakepath\\Desktop\Ekreta.Mobile.Core.dll

using Ekreta.Mobile.Core.Extensions;
using Ekreta.Mobile.Core.ViewModels;
using ImageCircle.Forms.Plugin.Abstractions;
using MvvmCross.Forms.Presenters.Attributes;
using MvvmCross.Forms.Views;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Reflection;
using System.Xml;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.PlatformConfiguration;
using Xamarin.Forms.PlatformConfiguration.iOSSpecific;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Internals;

namespace Ekreta.Mobile.Core.Views
{
  [XamlCompilation]
  [MvxMasterDetailPagePresentation]
  [XamlFilePath("Views/MasterPage.xaml")]
  public class MasterPage : MvxContentPage<MasterViewModel>
  {
    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private MvxContentPage<MasterViewModel> View;
    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private Grid MainGrid;
    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private Grid TitleGrid;

    public MasterPage()
    {
      base.\u002Ector();
      this.InitializeComponent();
    }

    protected virtual void OnAppearing()
    {
      ((MvxContentPage) this).OnAppearing();
      Thickness thickness = Page.SafeAreaInsets((IPlatformElementConfiguration<iOS, Page>) ((Page) this).On<iOS>());
      ((Layout) this.MainGrid).set_Padding(new Thickness(0.0, 0.0, 0.0, ((Thickness) ref thickness).get_Bottom()));
      ((Layout) this.TitleGrid).set_Padding(new Thickness(0.0, ((Thickness) ref thickness).get_Top(), 0.0, 0.0));
    }

    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private void InitializeComponent()
    {
      ResourceLoader.ResourceLoadingQuery resourceLoadingQuery = new ResourceLoader.ResourceLoadingQuery();
      resourceLoadingQuery.set_AssemblyName(typeof (MasterPage).GetTypeInfo().Assembly.GetName());
      resourceLoadingQuery.set_ResourcePath("Views/MasterPage.xaml");
      resourceLoadingQuery.set_Instance((object) this);
      if (ResourceLoader.CanProvideContentFor(resourceLoadingQuery))
        this.__InitComponentRuntime();
      else if (XamlLoader.get_XamlFileProvider() != null && XamlLoader.get_XamlFileProvider()(((object) this).GetType()) != null)
      {
        this.__InitComponentRuntime();
      }
      else
      {
        TranslateExtension translateExtension1 = new TranslateExtension();
        RowDefinition rowDefinition1 = new RowDefinition();
        RowDefinition rowDefinition2 = new RowDefinition();
        RowDefinition rowDefinition3 = new RowDefinition();
        DynamicResourceExtension resourceExtension1 = new DynamicResourceExtension();
        RowDefinition rowDefinition4 = new RowDefinition();
        StaticResourceExtension resourceExtension2 = new StaticResourceExtension();
        BindingExtension bindingExtension1 = new BindingExtension();
        StaticResourceExtension resourceExtension3 = new StaticResourceExtension();
        Label label1 = new Label();
        BindingExtension bindingExtension2 = new BindingExtension();
        StaticResourceExtension resourceExtension4 = new StaticResourceExtension();
        Label label2 = new Label();
        StaticResourceExtension resourceExtension5 = new StaticResourceExtension();
        TranslateExtension translateExtension2 = new TranslateExtension();
        StaticResourceExtension resourceExtension6 = new StaticResourceExtension();
        BindingExtension bindingExtension3 = new BindingExtension();
        TapGestureRecognizer gestureRecognizer1 = new TapGestureRecognizer();
        Label label3 = new Label();
        BindingExtension bindingExtension4 = new BindingExtension();
        Setter setter1 = new Setter();
        VisualState visualState1 = new VisualState();
        Setter setter2 = new Setter();
        VisualState visualState2 = new VisualState();
        VisualStateGroup visualStateGroup = new VisualStateGroup();
        Button button1 = new Button();
        Grid grid1 = new Grid();
        StackLayout stackLayout1 = new StackLayout();
        BindingExtension bindingExtension5 = new BindingExtension();
        TapGestureRecognizer gestureRecognizer2 = new TapGestureRecognizer();
        Image image = new Image();
        Grid grid2 = new Grid();
        BindingExtension bindingExtension6 = new BindingExtension();
        BindingExtension bindingExtension7 = new BindingExtension();
        DataTemplate dataTemplate1 = new DataTemplate();
        ListView listView = new ListView((ListViewCachingStrategy) 1);
        StaticResourceExtension resourceExtension7 = new StaticResourceExtension();
        StaticResourceExtension resourceExtension8 = new StaticResourceExtension();
        BindingExtension bindingExtension8 = new BindingExtension();
        Label label4 = new Label();
        StackLayout stackLayout2 = new StackLayout();
        StaticResourceExtension resourceExtension9 = new StaticResourceExtension();
        BindingExtension bindingExtension9 = new BindingExtension();
        StaticResourceExtension resourceExtension10 = new StaticResourceExtension();
        CircleImage circleImage = new CircleImage();
        BindingExtension bindingExtension10 = new BindingExtension();
        ActivityIndicator activityIndicator = new ActivityIndicator();
        Grid grid3 = new Grid();
        Grid grid4 = new Grid();
        MasterPage masterPage;
        NameScope nameScope1 = (NameScope) (NameScope.GetNameScope((BindableObject) (masterPage = this)) ?? (INameScope) new NameScope());
        NameScope.SetNameScope((BindableObject) masterPage, (INameScope) nameScope1);
        ((INameScope) nameScope1).RegisterName("View", (object) masterPage);
        if (((Element) masterPage).get_StyleId() == null)
          ((Element) masterPage).set_StyleId("View");
        ((INameScope) nameScope1).RegisterName("MainGrid", (object) grid4);
        if (((Element) grid4).get_StyleId() == null)
          ((Element) grid4).set_StyleId("MainGrid");
        ((INameScope) nameScope1).RegisterName("TitleGrid", (object) grid2);
        if (((Element) grid2).get_StyleId() == null)
          ((Element) grid2).set_StyleId("TitleGrid");
        NameScope nameScope2;
        ((INameScope) (nameScope2 = new NameScope())).RegisterName("CommonStates", (object) visualStateGroup);
        ((INameScope) nameScope2).RegisterName("Normal", (object) visualState1);
        ((INameScope) nameScope2).RegisterName("Pressed", (object) visualState2);
        this.View = (MvxContentPage<MasterViewModel>) masterPage;
        this.MainGrid = grid4;
        this.TitleGrid = grid2;
        translateExtension1.Text = "Page_Main_Title";
        TranslateExtension translateExtension3 = translateExtension1;
        XamlServiceProvider xamlServiceProvider1 = new XamlServiceProvider();
        Type type1 = typeof (IProvideValueTarget);
        object[] objArray1 = new object[0 + 1];
        objArray1[0] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider1;
        object obj1 = (object) (valueTargetProvider1 = new SimpleValueTargetProvider(objArray1, (object) Page.TitleProperty, (INameScope) nameScope1));
        xamlServiceProvider1.Add(type1, (object) valueTargetProvider1);
        xamlServiceProvider1.Add(typeof (IReferenceProvider), obj1);
        Type type2 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver1 = new XmlNamespaceResolver();
        namespaceResolver1.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver1.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver1.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver1.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver1.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver1.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver1.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver1.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver1.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver1 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver1, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider1.Add(type2, (object) xamlTypeResolver1);
        xamlServiceProvider1.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(14, 5)));
        object obj2 = ((IMarkupExtension) translateExtension3).ProvideValue((IServiceProvider) xamlServiceProvider1);
        ((Page) masterPage).set_Title((string) obj2);
        ((BindableObject) masterPage).SetValue((BindableProperty) Page.IconProperty, new FileImageSourceConverter().ConvertFromInvariantString("hamburger_menu_icon.png"));
        ((BindableObject) rowDefinition1).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid4).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition1);
        ((BindableObject) rowDefinition2).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid4).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition2);
        ((BindableObject) rowDefinition3).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid4).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition3);
        ((BindableObject) grid2).SetValue((BindableProperty) Grid.RowProperty, (object) 0);
        resourceExtension1.set_Key("AccentColor");
        DynamicResourceExtension resourceExtension11 = resourceExtension1;
        XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
        Type type3 = typeof (IProvideValueTarget);
        object[] objArray2 = new object[0 + 3];
        objArray2[0] = (object) grid2;
        objArray2[1] = (object) grid4;
        objArray2[2] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider2;
        object obj3 = (object) (valueTargetProvider2 = new SimpleValueTargetProvider(objArray2, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope1));
        xamlServiceProvider2.Add(type3, (object) valueTargetProvider2);
        xamlServiceProvider2.Add(typeof (IReferenceProvider), obj3);
        Type type4 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver2 = new XmlNamespaceResolver();
        namespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver2.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver2.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver2.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver2.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver2.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver2.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver2.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver2 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver2, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider2.Add(type4, (object) xamlTypeResolver2);
        xamlServiceProvider2.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(30, 13)));
        DynamicResource dynamicResource = ((IMarkupExtension<DynamicResource>) resourceExtension11).ProvideValue((IServiceProvider) xamlServiceProvider2);
        ((IDynamicResourceHandler) grid2).SetDynamicResource((BindableProperty) VisualElement.BackgroundColorProperty, dynamicResource.get_Key());
        ((BindableObject) rowDefinition4).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid2).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition4);
        ((BindableObject) stackLayout1).SetValue((BindableProperty) Layout.PaddingProperty, (object) new Thickness(16.0, 16.0, 30.0, 16.0));
        ((BindableObject) stackLayout1).SetValue((BindableProperty) Xamarin.Forms.View.VerticalOptionsProperty, (object) (LayoutOptions) LayoutOptions.End);
        resourceExtension2.set_Key("TitleLabelStyle");
        StaticResourceExtension resourceExtension12 = resourceExtension2;
        XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
        Type type5 = typeof (IProvideValueTarget);
        object[] objArray3 = new object[0 + 5];
        objArray3[0] = (object) label1;
        objArray3[1] = (object) stackLayout1;
        objArray3[2] = (object) grid2;
        objArray3[3] = (object) grid4;
        objArray3[4] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider3;
        object obj4 = (object) (valueTargetProvider3 = new SimpleValueTargetProvider(objArray3, (object) VisualElement.StyleProperty, (INameScope) nameScope1));
        xamlServiceProvider3.Add(type5, (object) valueTargetProvider3);
        xamlServiceProvider3.Add(typeof (IReferenceProvider), obj4);
        Type type6 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver3 = new XmlNamespaceResolver();
        namespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver3.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver3.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver3.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver3.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver3.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver3.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver3.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver3 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver3, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider3.Add(type6, (object) xamlTypeResolver3);
        xamlServiceProvider3.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(36, 21)));
        object obj5 = ((IMarkupExtension) resourceExtension12).ProvideValue((IServiceProvider) xamlServiceProvider3);
        ((NavigableElement) label1).set_Style((Style) obj5);
        bindingExtension1.set_Path("Student.DisplayName");
        BindingBase bindingBase1 = ((IMarkupExtension<BindingBase>) bindingExtension1).ProvideValue((IServiceProvider) null);
        ((BindableObject) label1).SetBinding((BindableProperty) Label.TextProperty, bindingBase1);
        resourceExtension3.set_Key("AccentContrastColor");
        StaticResourceExtension resourceExtension13 = resourceExtension3;
        XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
        Type type7 = typeof (IProvideValueTarget);
        object[] objArray4 = new object[0 + 5];
        objArray4[0] = (object) label1;
        objArray4[1] = (object) stackLayout1;
        objArray4[2] = (object) grid2;
        objArray4[3] = (object) grid4;
        objArray4[4] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider4;
        object obj6 = (object) (valueTargetProvider4 = new SimpleValueTargetProvider(objArray4, (object) Label.TextColorProperty, (INameScope) nameScope1));
        xamlServiceProvider4.Add(type7, (object) valueTargetProvider4);
        xamlServiceProvider4.Add(typeof (IReferenceProvider), obj6);
        Type type8 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver4 = new XmlNamespaceResolver();
        namespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver4.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver4.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver4.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver4.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver4.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver4.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver4.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver4 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver4, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider4.Add(type8, (object) xamlTypeResolver4);
        xamlServiceProvider4.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(38, 21)));
        object obj7 = ((IMarkupExtension) resourceExtension13).ProvideValue((IServiceProvider) xamlServiceProvider4);
        label1.set_TextColor((Color) obj7);
        ((ICollection<Xamarin.Forms.View>) ((Layout<Xamarin.Forms.View>) stackLayout1).get_Children()).Add((Xamarin.Forms.View) label1);
        bindingExtension2.set_Path("Role");
        BindingBase bindingBase2 = ((IMarkupExtension<BindingBase>) bindingExtension2).ProvideValue((IServiceProvider) null);
        ((BindableObject) label2).SetBinding((BindableProperty) Label.TextProperty, bindingBase2);
        resourceExtension4.set_Key("AccentContrastColor");
        StaticResourceExtension resourceExtension14 = resourceExtension4;
        XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
        Type type9 = typeof (IProvideValueTarget);
        object[] objArray5 = new object[0 + 5];
        objArray5[0] = (object) label2;
        objArray5[1] = (object) stackLayout1;
        objArray5[2] = (object) grid2;
        objArray5[3] = (object) grid4;
        objArray5[4] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider5;
        object obj8 = (object) (valueTargetProvider5 = new SimpleValueTargetProvider(objArray5, (object) Label.TextColorProperty, (INameScope) nameScope1));
        xamlServiceProvider5.Add(type9, (object) valueTargetProvider5);
        xamlServiceProvider5.Add(typeof (IReferenceProvider), obj8);
        Type type10 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver5 = new XmlNamespaceResolver();
        namespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver5.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver5.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver5.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver5.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver5.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver5.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver5.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver5 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver5, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider5.Add(type10, (object) xamlTypeResolver5);
        xamlServiceProvider5.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(39, 46)));
        object obj9 = ((IMarkupExtension) resourceExtension14).ProvideValue((IServiceProvider) xamlServiceProvider5);
        label2.set_TextColor((Color) obj9);
        ((ICollection<Xamarin.Forms.View>) ((Layout<Xamarin.Forms.View>) stackLayout1).get_Children()).Add((Xamarin.Forms.View) label2);
        resourceExtension5.set_Key("AccentContrastColor");
        StaticResourceExtension resourceExtension15 = resourceExtension5;
        XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
        Type type11 = typeof (IProvideValueTarget);
        object[] objArray6 = new object[0 + 6];
        objArray6[0] = (object) label3;
        objArray6[1] = (object) grid1;
        objArray6[2] = (object) stackLayout1;
        objArray6[3] = (object) grid2;
        objArray6[4] = (object) grid4;
        objArray6[5] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider6;
        object obj10 = (object) (valueTargetProvider6 = new SimpleValueTargetProvider(objArray6, (object) VisualElement.StyleProperty, (INameScope) nameScope1));
        xamlServiceProvider6.Add(type11, (object) valueTargetProvider6);
        xamlServiceProvider6.Add(typeof (IReferenceProvider), obj10);
        Type type12 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver6 = new XmlNamespaceResolver();
        namespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver6.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver6.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver6.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver6.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver6.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver6.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver6.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver6 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver6, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider6.Add(type12, (object) xamlTypeResolver6);
        xamlServiceProvider6.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(43, 25)));
        object obj11 = ((IMarkupExtension) resourceExtension15).ProvideValue((IServiceProvider) xamlServiceProvider6);
        ((NavigableElement) label3).set_Style((Style) obj11);
        translateExtension2.Text = "MenuItem_Profiles_Title";
        TranslateExtension translateExtension4 = translateExtension2;
        XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
        Type type13 = typeof (IProvideValueTarget);
        object[] objArray7 = new object[0 + 6];
        objArray7[0] = (object) label3;
        objArray7[1] = (object) grid1;
        objArray7[2] = (object) stackLayout1;
        objArray7[3] = (object) grid2;
        objArray7[4] = (object) grid4;
        objArray7[5] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider7;
        object obj12 = (object) (valueTargetProvider7 = new SimpleValueTargetProvider(objArray7, (object) Label.TextProperty, (INameScope) nameScope1));
        xamlServiceProvider7.Add(type13, (object) valueTargetProvider7);
        xamlServiceProvider7.Add(typeof (IReferenceProvider), obj12);
        Type type14 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver7 = new XmlNamespaceResolver();
        namespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver7.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver7.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver7.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver7.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver7.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver7.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver7.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver7 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver7, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider7.Add(type14, (object) xamlTypeResolver7);
        xamlServiceProvider7.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(44, 25)));
        object obj13 = ((IMarkupExtension) translateExtension4).ProvideValue((IServiceProvider) xamlServiceProvider7);
        label3.set_Text((string) obj13);
        resourceExtension6.set_Key("AccentContrastColor");
        StaticResourceExtension resourceExtension16 = resourceExtension6;
        XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
        Type type15 = typeof (IProvideValueTarget);
        object[] objArray8 = new object[0 + 6];
        objArray8[0] = (object) label3;
        objArray8[1] = (object) grid1;
        objArray8[2] = (object) stackLayout1;
        objArray8[3] = (object) grid2;
        objArray8[4] = (object) grid4;
        objArray8[5] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider8;
        object obj14 = (object) (valueTargetProvider8 = new SimpleValueTargetProvider(objArray8, (object) Label.TextColorProperty, (INameScope) nameScope1));
        xamlServiceProvider8.Add(type15, (object) valueTargetProvider8);
        xamlServiceProvider8.Add(typeof (IReferenceProvider), obj14);
        Type type16 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver8 = new XmlNamespaceResolver();
        namespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver8.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver8.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver8.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver8.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver8.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver8.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver8.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver8 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver8, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider8.Add(type16, (object) xamlTypeResolver8);
        xamlServiceProvider8.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(45, 25)));
        object obj15 = ((IMarkupExtension) resourceExtension16).ProvideValue((IServiceProvider) xamlServiceProvider8);
        label3.set_TextColor((Color) obj15);
        bindingExtension3.set_Path("ShowProfilesCommand");
        BindingBase bindingBase3 = ((IMarkupExtension<BindingBase>) bindingExtension3).ProvideValue((IServiceProvider) null);
        ((BindableObject) gestureRecognizer1).SetBinding((BindableProperty) TapGestureRecognizer.CommandProperty, bindingBase3);
        ((ICollection<IGestureRecognizer>) ((Xamarin.Forms.View) label3).get_GestureRecognizers()).Add((IGestureRecognizer) gestureRecognizer1);
        ((ICollection<Xamarin.Forms.View>) grid1.get_Children()).Add((Xamarin.Forms.View) label3);
        ((BindableObject) button1).SetValue((BindableProperty) Xamarin.Forms.View.MarginProperty, (object) new Thickness(0.0, 0.0, 60.0, 0.0));
        bindingExtension4.set_Path("ShowProfilesCommand");
        BindingBase bindingBase4 = ((IMarkupExtension<BindingBase>) bindingExtension4).ProvideValue((IServiceProvider) null);
        ((BindableObject) button1).SetBinding((BindableProperty) Button.CommandProperty, bindingBase4);
        Button button2 = button1;
        // ISSUE: variable of the null type
        __Null fontSizeProperty = Button.FontSizeProperty;
        FontSizeConverter fontSizeConverter = new FontSizeConverter();
        XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
        Type type17 = typeof (IProvideValueTarget);
        object[] objArray9 = new object[0 + 6];
        objArray9[0] = (object) button1;
        objArray9[1] = (object) grid1;
        objArray9[2] = (object) stackLayout1;
        objArray9[3] = (object) grid2;
        objArray9[4] = (object) grid4;
        objArray9[5] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider9;
        object obj16 = (object) (valueTargetProvider9 = new SimpleValueTargetProvider(objArray9, (object) Button.FontSizeProperty, (INameScope) nameScope1));
        xamlServiceProvider9.Add(type17, (object) valueTargetProvider9);
        xamlServiceProvider9.Add(typeof (IReferenceProvider), obj16);
        Type type18 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver9 = new XmlNamespaceResolver();
        namespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver9.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver9.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver9.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver9.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver9.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver9.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver9.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver9 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver9, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider9.Add(type18, (object) xamlTypeResolver9);
        xamlServiceProvider9.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(54, 25)));
        object obj17 = ((IExtendedTypeConverter) fontSizeConverter).ConvertFromInvariantString("Small", (IServiceProvider) xamlServiceProvider9);
        ((BindableObject) button2).SetValue((BindableProperty) fontSizeProperty, obj17);
        ((BindableObject) button1).SetValue((BindableProperty) VisualElement.HeightRequestProperty, (object) 30.0);
        ((BindableObject) button1).SetValue((BindableProperty) VisualElement.OpacityProperty, (object) 0.2);
        ((BindableObject) button1).SetValue((BindableProperty) Button.TextProperty, (object) "");
        ((BindableObject) button1).SetValue((BindableProperty) Xamarin.Forms.View.VerticalOptionsProperty, (object) (LayoutOptions) LayoutOptions.Start);
        visualStateGroup.set_Name("CommonStates");
        visualState1.set_Name("Normal");
        setter1.set_Property((BindableProperty) VisualElement.BackgroundColorProperty);
        setter1.set_Value((object) "Transparent");
        setter1.set_Value((object) (Color) Color.Transparent);
        ((ICollection<Setter>) visualState1.get_Setters()).Add(setter1);
        ((ICollection<VisualState>) visualStateGroup.get_States()).Add(visualState1);
        visualState2.set_Name("Pressed");
        setter2.set_Property((BindableProperty) VisualElement.BackgroundColorProperty);
        setter2.set_Value((object) "#33ADD3");
        setter2.set_Value((object) new Color(0.200000002980232, 0.678431391716003, 0.82745099067688, 1.0));
        ((ICollection<Setter>) visualState2.get_Setters()).Add(setter2);
        ((ICollection<VisualState>) visualStateGroup.get_States()).Add(visualState2);
        ((ICollection<VisualStateGroup>) ((BindableObject) button1).GetValue((BindableProperty) VisualStateManager.VisualStateGroupsProperty)).Add(visualStateGroup);
        ((ICollection<Xamarin.Forms.View>) grid1.get_Children()).Add((Xamarin.Forms.View) button1);
        ((ICollection<Xamarin.Forms.View>) ((Layout<Xamarin.Forms.View>) stackLayout1).get_Children()).Add((Xamarin.Forms.View) grid1);
        ((ICollection<Xamarin.Forms.View>) grid2.get_Children()).Add((Xamarin.Forms.View) stackLayout1);
        ((BindableObject) image).SetValue((BindableProperty) Xamarin.Forms.View.HorizontalOptionsProperty, (object) (LayoutOptions) LayoutOptions.End);
        ((BindableObject) image).SetValue((BindableProperty) Image.SourceProperty, new ImageSourceConverter().ConvertFromInvariantString("ic_profilerefresh.png"));
        ((BindableObject) image).SetValue((BindableProperty) Xamarin.Forms.View.VerticalOptionsProperty, (object) (LayoutOptions) LayoutOptions.Center);
        bindingExtension5.set_Path("RefreshProfileCommand");
        BindingBase bindingBase5 = ((IMarkupExtension<BindingBase>) bindingExtension5).ProvideValue((IServiceProvider) null);
        ((BindableObject) gestureRecognizer2).SetBinding((BindableProperty) TapGestureRecognizer.CommandProperty, bindingBase5);
        ((ICollection<IGestureRecognizer>) ((Xamarin.Forms.View) image).get_GestureRecognizers()).Add((IGestureRecognizer) gestureRecognizer2);
        ((ICollection<Xamarin.Forms.View>) grid2.get_Children()).Add((Xamarin.Forms.View) image);
        ((ICollection<Xamarin.Forms.View>) grid4.get_Children()).Add((Xamarin.Forms.View) grid2);
        ((BindableObject) listView).SetValue((BindableProperty) Grid.RowProperty, (object) 1);
        bindingExtension6.set_Path("MenuItems");
        BindingBase bindingBase6 = ((IMarkupExtension<BindingBase>) bindingExtension6).ProvideValue((IServiceProvider) null);
        ((BindableObject) listView).SetBinding((BindableProperty) ItemsView<Cell>.ItemsSourceProperty, bindingBase6);
        bindingExtension7.set_Mode((BindingMode) 1);
        bindingExtension7.set_Path("SelectedMenuItem");
        BindingBase bindingBase7 = ((IMarkupExtension<BindingBase>) bindingExtension7).ProvideValue((IServiceProvider) null);
        ((BindableObject) listView).SetBinding((BindableProperty) ListView.SelectedItemProperty, bindingBase7);
        ((BindableObject) listView).SetValue((BindableProperty) ListView.SeparatorVisibilityProperty, (object) (SeparatorVisibility) 1);
        DataTemplate dataTemplate2 = dataTemplate1;
        // ISSUE: object of a compiler-generated type is created
        // ISSUE: variable of a compiler-generated type
        MasterPage.\u003CInitializeComponent\u003E_anonXamlCDataTemplate_27 xamlCdataTemplate27 = new MasterPage.\u003CInitializeComponent\u003E_anonXamlCDataTemplate_27();
        object[] objArray10 = new object[0 + 4];
        objArray10[0] = (object) dataTemplate1;
        objArray10[1] = (object) listView;
        objArray10[2] = (object) grid4;
        objArray10[3] = (object) masterPage;
        // ISSUE: reference to a compiler-generated field
        xamlCdataTemplate27.parentValues = objArray10;
        // ISSUE: reference to a compiler-generated field
        xamlCdataTemplate27.root = masterPage;
        // ISSUE: reference to a compiler-generated method
        Func<object> func = new Func<object>(xamlCdataTemplate27.LoadDataTemplate);
        ((IDataTemplate) dataTemplate2).set_LoadTemplate(func);
        ((BindableObject) listView).SetValue((BindableProperty) ItemsView<Cell>.ItemTemplateProperty, (object) dataTemplate1);
        ((ICollection<Xamarin.Forms.View>) grid4.get_Children()).Add((Xamarin.Forms.View) listView);
        ((BindableObject) stackLayout2).SetValue((BindableProperty) Grid.RowProperty, (object) 2);
        resourceExtension7.set_Key("ContentPadding");
        StaticResourceExtension resourceExtension17 = resourceExtension7;
        XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
        Type type19 = typeof (IProvideValueTarget);
        object[] objArray11 = new object[0 + 3];
        objArray11[0] = (object) stackLayout2;
        objArray11[1] = (object) grid4;
        objArray11[2] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider10;
        object obj18 = (object) (valueTargetProvider10 = new SimpleValueTargetProvider(objArray11, (object) Layout.PaddingProperty, (INameScope) nameScope1));
        xamlServiceProvider10.Add(type19, (object) valueTargetProvider10);
        xamlServiceProvider10.Add(typeof (IReferenceProvider), obj18);
        Type type20 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver10 = new XmlNamespaceResolver();
        namespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver10.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver10.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver10.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver10.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver10.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver10.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver10.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver10 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver10, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider10.Add(type20, (object) xamlTypeResolver10);
        xamlServiceProvider10.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(147, 35)));
        object obj19 = ((IMarkupExtension) resourceExtension17).ProvideValue((IServiceProvider) xamlServiceProvider10);
        ((Layout) stackLayout2).set_Padding((Thickness) obj19);
        resourceExtension8.set_Key("ListItemDescriptionStyle");
        StaticResourceExtension resourceExtension18 = resourceExtension8;
        XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
        Type type21 = typeof (IProvideValueTarget);
        object[] objArray12 = new object[0 + 4];
        objArray12[0] = (object) label4;
        objArray12[1] = (object) stackLayout2;
        objArray12[2] = (object) grid4;
        objArray12[3] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider11;
        object obj20 = (object) (valueTargetProvider11 = new SimpleValueTargetProvider(objArray12, (object) VisualElement.StyleProperty, (INameScope) nameScope1));
        xamlServiceProvider11.Add(type21, (object) valueTargetProvider11);
        xamlServiceProvider11.Add(typeof (IReferenceProvider), obj20);
        Type type22 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver11 = new XmlNamespaceResolver();
        namespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver11.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver11.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver11.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver11.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver11.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver11.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver11.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver11 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver11, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider11.Add(type22, (object) xamlTypeResolver11);
        xamlServiceProvider11.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(148, 20)));
        object obj21 = ((IMarkupExtension) resourceExtension18).ProvideValue((IServiceProvider) xamlServiceProvider11);
        ((NavigableElement) label4).set_Style((Style) obj21);
        bindingExtension8.set_Path("AppVersion");
        BindingBase bindingBase8 = ((IMarkupExtension<BindingBase>) bindingExtension8).ProvideValue((IServiceProvider) null);
        ((BindableObject) label4).SetBinding((BindableProperty) Label.TextProperty, bindingBase8);
        ((ICollection<Xamarin.Forms.View>) ((Layout<Xamarin.Forms.View>) stackLayout2).get_Children()).Add((Xamarin.Forms.View) label4);
        ((ICollection<Xamarin.Forms.View>) grid4.get_Children()).Add((Xamarin.Forms.View) stackLayout2);
        ((BindableObject) grid3).SetValue((BindableProperty) Grid.RowProperty, (object) 0);
        ((BindableObject) grid3).SetValue((BindableProperty) Grid.RowSpanProperty, (object) 3);
        resourceExtension9.set_Key("OverlayColor");
        StaticResourceExtension resourceExtension19 = resourceExtension9;
        XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
        Type type23 = typeof (IProvideValueTarget);
        object[] objArray13 = new object[0 + 3];
        objArray13[0] = (object) grid3;
        objArray13[1] = (object) grid4;
        objArray13[2] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider12;
        object obj22 = (object) (valueTargetProvider12 = new SimpleValueTargetProvider(objArray13, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope1));
        xamlServiceProvider12.Add(type23, (object) valueTargetProvider12);
        xamlServiceProvider12.Add(typeof (IReferenceProvider), obj22);
        Type type24 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver12 = new XmlNamespaceResolver();
        namespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver12.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver12.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver12.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver12.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver12.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver12.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver12.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver12 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver12, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider12.Add(type24, (object) xamlTypeResolver12);
        xamlServiceProvider12.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(153, 13)));
        object obj23 = ((IMarkupExtension) resourceExtension19).ProvideValue((IServiceProvider) xamlServiceProvider12);
        ((VisualElement) grid3).set_BackgroundColor((Color) obj23);
        bindingExtension9.set_Path("IsLoading");
        BindingBase bindingBase9 = ((IMarkupExtension<BindingBase>) bindingExtension9).ProvideValue((IServiceProvider) null);
        ((BindableObject) grid3).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase9);
        ((BindableObject) circleImage).SetValue((BindableProperty) CircleImage.FillColorProperty, (object) (Color) Color.White);
        resourceExtension10.set_Key("ListItemIconStyle");
        StaticResourceExtension resourceExtension20 = resourceExtension10;
        XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
        Type type25 = typeof (IProvideValueTarget);
        object[] objArray14 = new object[0 + 4];
        objArray14[0] = (object) circleImage;
        objArray14[1] = (object) grid3;
        objArray14[2] = (object) grid4;
        objArray14[3] = (object) masterPage;
        SimpleValueTargetProvider valueTargetProvider13;
        object obj24 = (object) (valueTargetProvider13 = new SimpleValueTargetProvider(objArray14, (object) VisualElement.StyleProperty, (INameScope) nameScope1));
        xamlServiceProvider13.Add(type25, (object) valueTargetProvider13);
        xamlServiceProvider13.Add(typeof (IReferenceProvider), obj24);
        Type type26 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver13 = new XmlNamespaceResolver();
        namespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver13.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver13.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver13.Add("ffimageloading", "clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms");
        namespaceResolver13.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver13.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver13.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver13.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver13 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver13, typeof (MasterPage).GetTypeInfo().Assembly);
        xamlServiceProvider13.Add(type26, (object) xamlTypeResolver13);
        xamlServiceProvider13.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(155, 56)));
        object obj25 = ((IMarkupExtension) resourceExtension20).ProvideValue((IServiceProvider) xamlServiceProvider13);
        ((NavigableElement) circleImage).set_Style((Style) obj25);
        ((ICollection<Xamarin.Forms.View>) grid3.get_Children()).Add((Xamarin.Forms.View) circleImage);
        bindingExtension10.set_Path("IsLoading");
        BindingBase bindingBase10 = ((IMarkupExtension<BindingBase>) bindingExtension10).ProvideValue((IServiceProvider) null);
        ((BindableObject) activityIndicator).SetBinding((BindableProperty) ActivityIndicator.IsRunningProperty, bindingBase10);
        ((ICollection<Xamarin.Forms.View>) grid3.get_Children()).Add((Xamarin.Forms.View) activityIndicator);
        ((ICollection<Xamarin.Forms.View>) grid4.get_Children()).Add((Xamarin.Forms.View) grid3);
        ((BindableObject) masterPage).SetValue((BindableProperty) ContentPage.ContentProperty, (object) grid4);
      }
    }

    private void __InitComponentRuntime()
    {
      Xamarin.Forms.Xaml.Extensions.LoadFromXaml<MasterPage>((M0) this, typeof (MasterPage));
      this.View = (MvxContentPage<MasterViewModel>) NameScopeExtensions.FindByName<MvxContentPage<MasterViewModel>>((Element) this, "View");
      this.MainGrid = (Grid) NameScopeExtensions.FindByName<Grid>((Element) this, "MainGrid");
      this.TitleGrid = (Grid) NameScopeExtensions.FindByName<Grid>((Element) this, "TitleGrid");
    }
  }
}
