// Decompiled with JetBrains decompiler
// Type: Ekreta.Mobile.Core.Views.MessageDetailPage
// Assembly: Ekreta.Mobile.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5AA13053-CF9F-480D-A76A-8A5D6C4EE194
// Assembly location: C:\fakepath\\Desktop\Ekreta.Mobile.Core.dll

using Ekreta.Mobile.Core.Extensions;
using Ekreta.Mobile.Core.Models.Uzenetek;
using Ekreta.Mobile.Core.ViewModels;
using FFImageLoading.Forms;
using ImageCircle.Forms.Plugin.Abstractions;
using MvvmCross.Forms.Presenters.Attributes;
using MvvmCross.Forms.Views;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Windows.Input;
using System.Xml;
using Xamarin.Essentials;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.PlatformConfiguration.iOSSpecific;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Internals;

namespace Ekreta.Mobile.Core.Views
{
  [XamlCompilation]
  [MvxMasterDetailPagePresentation]
  [XamlFilePath("Views/MessageDetailPage.xaml")]
  public class MessageDetailPage : MvxContentPage<MessageDetailViewModel>
  {
    private const string http = "http";
    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private Label CsatolmanyokLabel;
    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private StackLayout CsatolmanyokBox;

    public MessageDetailPage()
    {
      base.\u002Ector();
      this.InitializeComponent();
    }

    protected virtual void OnViewModelSet()
    {
      ((MvxContentPage) this).OnViewModelSet();
      this.RefreshCsatolmanyLinks();
    }

    private void RefreshCsatolmanyLinks()
    {
      ((ICollection<View>) ((Layout<View>) this.CsatolmanyokBox).get_Children()).Clear();
      List<Csatolmany> csatolmanyok = this.get_ViewModel()?.PostaladaElem?.Uzenet?.Csatolmanyok;
      if (csatolmanyok == null || !csatolmanyok.Any<Csatolmany>())
        ((VisualElement) this.CsatolmanyokLabel).set_IsVisible(false);
      else
        csatolmanyok.ForEach((Action<Csatolmany>) (csatolmany =>
        {
          StackLayout stackLayout1 = new StackLayout();
          ((VisualElement) stackLayout1).set_BackgroundColor(Color.FromHex("#F8F8F8"));
          stackLayout1.set_Orientation((StackOrientation) 1);
          ((View) stackLayout1).set_HorizontalOptions((LayoutOptions) LayoutOptions.Fill);
          StackLayout stackLayout2 = stackLayout1;
          Label label1 = new Label();
          label1.set_Text(csatolmany.FajlNev);
          label1.set_FontSize(Device.GetNamedSize((NamedSize) 3, typeof (Label)));
          ((VisualElement) label1).set_BackgroundColor((Color) Color.Transparent);
          label1.set_TextColor((Color) Application.get_Current().get_Resources().get_Item("AccentColor"));
          ((View) label1).set_HorizontalOptions((LayoutOptions) LayoutOptions.StartAndExpand);
          ((View) label1).set_Margin(new Thickness(0.0, 10.0));
          label1.set_HorizontalTextAlignment((TextAlignment) 1);
          Label label2 = label1;
          CachedImage cachedImage1 = new CachedImage();
          cachedImage1.set_DownsampleHeight(48.0);
          ((VisualElement) cachedImage1).set_HeightRequest(48.0);
          ((VisualElement) cachedImage1).set_MinimumWidthRequest(48.0);
          ((VisualElement) cachedImage1).set_WidthRequest(48.0);
          cachedImage1.set_DownsampleToViewSize(true);
          cachedImage1.set_Source(ImageSource.op_Implicit("ic_file_download.png"));
          ((View) cachedImage1).set_HorizontalOptions((LayoutOptions) LayoutOptions.EndAndExpand);
          ((View) cachedImage1).set_VerticalOptions((LayoutOptions) LayoutOptions.Center);
          CachedImage cachedImage2 = cachedImage1;
          ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label2);
          ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) cachedImage2);
          IList<IGestureRecognizer> gestureRecognizers = ((View) stackLayout2).get_GestureRecognizers();
          TapGestureRecognizer gestureRecognizer = new TapGestureRecognizer();
          gestureRecognizer.set_Command((ICommand) this.get_ViewModel().DownloadCsatolmany);
          gestureRecognizer.set_CommandParameter((object) csatolmany);
          ((ICollection<IGestureRecognizer>) gestureRecognizers).Add((IGestureRecognizer) gestureRecognizer);
          Frame frame = new Frame();
          frame.set_HasShadow(false);
          ((ContentView) frame).set_Content((View) stackLayout2);
          ((Layout) frame).set_Padding(new Thickness(0.0, 0.0, 0.0, 0.0));
          ((View) frame).set_Margin(new Thickness(0.0, 4.0));
          frame.set_CornerRadius(0.0f);
          ((ICollection<View>) ((Layout<View>) this.CsatolmanyokBox).get_Children()).Add((View) frame);
        }));
    }

    private async void WebView_OnNavigating(object sender, WebNavigatingEventArgs e)
    {
      try
      {
        string url = ((WebNavigationEventArgs) e).get_Url();
        if (!url.StartsWith("http"))
          return;
        e.set_Cancel(true);
        await Launcher.OpenAsync(new Uri(url));
      }
      catch (Exception ex)
      {
        Console.WriteLine((object) ex);
      }
    }

    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private void InitializeComponent()
    {
      ResourceLoader.ResourceLoadingQuery resourceLoadingQuery = new ResourceLoader.ResourceLoadingQuery();
      resourceLoadingQuery.set_AssemblyName(typeof (MessageDetailPage).GetTypeInfo().Assembly.GetName());
      resourceLoadingQuery.set_ResourcePath("Views/MessageDetailPage.xaml");
      resourceLoadingQuery.set_Instance((object) this);
      if (ResourceLoader.CanProvideContentFor(resourceLoadingQuery))
        this.__InitComponentRuntime();
      else if (XamlLoader.get_XamlFileProvider() != null && XamlLoader.get_XamlFileProvider()(((object) this).GetType()) != null)
      {
        this.__InitComponentRuntime();
      }
      else
      {
        BindingExtension bindingExtension1 = new BindingExtension();
        StaticResourceExtension resourceExtension1 = new StaticResourceExtension();
        StaticResourceExtension resourceExtension2 = new StaticResourceExtension();
        StaticResourceExtension resourceExtension3 = new StaticResourceExtension();
        TranslateExtension translateExtension1 = new TranslateExtension();
        Label label1 = new Label();
        StaticResourceExtension resourceExtension4 = new StaticResourceExtension();
        BindingExtension bindingExtension2 = new BindingExtension();
        Label label2 = new Label();
        StaticResourceExtension resourceExtension5 = new StaticResourceExtension();
        TranslateExtension translateExtension2 = new TranslateExtension();
        Label label3 = new Label();
        StaticResourceExtension resourceExtension6 = new StaticResourceExtension();
        BindingExtension bindingExtension3 = new BindingExtension();
        Label label4 = new Label();
        StaticResourceExtension resourceExtension7 = new StaticResourceExtension();
        TranslateExtension translateExtension3 = new TranslateExtension();
        Label label5 = new Label();
        StaticResourceExtension resourceExtension8 = new StaticResourceExtension();
        BindingExtension bindingExtension4 = new BindingExtension();
        Label label6 = new Label();
        StaticResourceExtension resourceExtension9 = new StaticResourceExtension();
        TranslateExtension translateExtension4 = new TranslateExtension();
        Label label7 = new Label();
        StackLayout stackLayout1 = new StackLayout();
        StaticResourceExtension resourceExtension10 = new StaticResourceExtension();
        TranslateExtension translateExtension5 = new TranslateExtension();
        Label label8 = new Label();
        BindingExtension bindingExtension5 = new BindingExtension();
        TranslateExtension translateExtension6 = new TranslateExtension();
        Label label9 = new Label();
        BindingExtension bindingExtension6 = new BindingExtension();
        TranslateExtension translateExtension7 = new TranslateExtension();
        Label label10 = new Label();
        BindingExtension bindingExtension7 = new BindingExtension();
        WebView webView = new WebView();
        StackLayout stackLayout2 = new StackLayout();
        StaticResourceExtension resourceExtension11 = new StaticResourceExtension();
        BindingExtension bindingExtension8 = new BindingExtension();
        StaticResourceExtension resourceExtension12 = new StaticResourceExtension();
        CircleImage circleImage = new CircleImage();
        BindingExtension bindingExtension9 = new BindingExtension();
        ActivityIndicator activityIndicator = new ActivityIndicator();
        Grid grid1 = new Grid();
        Grid grid2 = new Grid();
        ScrollView scrollView = new ScrollView();
        MessageDetailPage messageDetailPage;
        NameScope nameScope = (NameScope) (NameScope.GetNameScope((BindableObject) (messageDetailPage = this)) ?? (INameScope) new NameScope());
        NameScope.SetNameScope((BindableObject) messageDetailPage, (INameScope) nameScope);
        ((INameScope) nameScope).RegisterName("CsatolmanyokLabel", (object) label7);
        if (((Element) label7).get_StyleId() == null)
          ((Element) label7).set_StyleId("CsatolmanyokLabel");
        ((INameScope) nameScope).RegisterName("CsatolmanyokBox", (object) stackLayout1);
        if (((Element) stackLayout1).get_StyleId() == null)
          ((Element) stackLayout1).set_StyleId("CsatolmanyokBox");
        this.CsatolmanyokLabel = label7;
        this.CsatolmanyokBox = stackLayout1;
        bindingExtension1.set_Path("TitleIncludeConnectivityState");
        BindingBase bindingBase1 = ((IMarkupExtension<BindingBase>) bindingExtension1).ProvideValue((IServiceProvider) null);
        ((BindableObject) messageDetailPage).SetBinding((BindableProperty) Page.TitleProperty, bindingBase1);
        ((BindableObject) messageDetailPage).SetValue((BindableProperty) Page.UseSafeAreaProperty, (object) true);
        resourceExtension1.set_Key("PageBackgroundColor");
        StaticResourceExtension resourceExtension13 = resourceExtension1;
        XamlServiceProvider xamlServiceProvider1 = new XamlServiceProvider();
        Type type1 = typeof (IProvideValueTarget);
        object[] objArray1 = new object[0 + 1];
        objArray1[0] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider1;
        object obj1 = (object) (valueTargetProvider1 = new SimpleValueTargetProvider(objArray1, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope));
        xamlServiceProvider1.Add(type1, (object) valueTargetProvider1);
        xamlServiceProvider1.Add(typeof (IReferenceProvider), obj1);
        Type type2 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver1 = new XmlNamespaceResolver();
        namespaceResolver1.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver1.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver1.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver1.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver1.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver1.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver1.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver1.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver1.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver1.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver1 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver1, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider1.Add(type2, (object) xamlTypeResolver1);
        xamlServiceProvider1.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(17, 5)));
        object obj2 = ((IMarkupExtension) resourceExtension13).ProvideValue((IServiceProvider) xamlServiceProvider1);
        ((VisualElement) messageDetailPage).set_BackgroundColor((Color) obj2);
        resourceExtension2.set_Key("DetailContentHolderStyle");
        StaticResourceExtension resourceExtension14 = resourceExtension2;
        XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
        Type type3 = typeof (IProvideValueTarget);
        object[] objArray2 = new object[0 + 2];
        objArray2[0] = (object) scrollView;
        objArray2[1] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider2;
        object obj3 = (object) (valueTargetProvider2 = new SimpleValueTargetProvider(objArray2, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider2.Add(type3, (object) valueTargetProvider2);
        xamlServiceProvider2.Add(typeof (IReferenceProvider), obj3);
        Type type4 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver2 = new XmlNamespaceResolver();
        namespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver2.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver2.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver2.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver2.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver2.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver2.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver2.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver2.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver2 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver2, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider2.Add(type4, (object) xamlTypeResolver2);
        xamlServiceProvider2.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(22, 17)));
        object obj4 = ((IMarkupExtension) resourceExtension14).ProvideValue((IServiceProvider) xamlServiceProvider2);
        ((NavigableElement) scrollView).set_Style((Style) obj4);
        resourceExtension3.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension15 = resourceExtension3;
        XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
        Type type5 = typeof (IProvideValueTarget);
        object[] objArray3 = new object[0 + 5];
        objArray3[0] = (object) label1;
        objArray3[1] = (object) stackLayout2;
        objArray3[2] = (object) grid2;
        objArray3[3] = (object) scrollView;
        objArray3[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider3;
        object obj5 = (object) (valueTargetProvider3 = new SimpleValueTargetProvider(objArray3, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider3.Add(type5, (object) valueTargetProvider3);
        xamlServiceProvider3.Add(typeof (IReferenceProvider), obj5);
        Type type6 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver3 = new XmlNamespaceResolver();
        namespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver3.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver3.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver3.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver3.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver3.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver3.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver3.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver3.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver3 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver3, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider3.Add(type6, (object) xamlTypeResolver3);
        xamlServiceProvider3.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(25, 24)));
        object obj6 = ((IMarkupExtension) resourceExtension15).ProvideValue((IServiceProvider) xamlServiceProvider3);
        ((NavigableElement) label1).set_Style((Style) obj6);
        translateExtension1.Text = "Uzenet_Felado_Title";
        TranslateExtension translateExtension8 = translateExtension1;
        XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
        Type type7 = typeof (IProvideValueTarget);
        object[] objArray4 = new object[0 + 5];
        objArray4[0] = (object) label1;
        objArray4[1] = (object) stackLayout2;
        objArray4[2] = (object) grid2;
        objArray4[3] = (object) scrollView;
        objArray4[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider4;
        object obj7 = (object) (valueTargetProvider4 = new SimpleValueTargetProvider(objArray4, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider4.Add(type7, (object) valueTargetProvider4);
        xamlServiceProvider4.Add(typeof (IReferenceProvider), obj7);
        Type type8 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver4 = new XmlNamespaceResolver();
        namespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver4.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver4.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver4.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver4.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver4.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver4.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver4.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver4.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver4 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver4, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider4.Add(type8, (object) xamlTypeResolver4);
        xamlServiceProvider4.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(25, 70)));
        object obj8 = ((IMarkupExtension) translateExtension8).ProvideValue((IServiceProvider) xamlServiceProvider4);
        label1.set_Text((string) obj8);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label1);
        ((BindableObject) label2).SetValue((BindableProperty) View.MarginProperty, (object) new Thickness(6.0, 0.0, 0.0, 8.0));
        ((BindableObject) label2).SetValue((BindableProperty) VisualElement.BackgroundColorProperty, (object) new Color(0.972549021244049, 0.972549021244049, 0.972549021244049, 1.0));
        resourceExtension4.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension16 = resourceExtension4;
        XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
        Type type9 = typeof (IProvideValueTarget);
        object[] objArray5 = new object[0 + 5];
        objArray5[0] = (object) label2;
        objArray5[1] = (object) stackLayout2;
        objArray5[2] = (object) grid2;
        objArray5[3] = (object) scrollView;
        objArray5[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider5;
        object obj9 = (object) (valueTargetProvider5 = new SimpleValueTargetProvider(objArray5, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider5.Add(type9, (object) valueTargetProvider5);
        xamlServiceProvider5.Add(typeof (IReferenceProvider), obj9);
        Type type10 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver5 = new XmlNamespaceResolver();
        namespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver5.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver5.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver5.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver5.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver5.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver5.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver5.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver5.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver5 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver5, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider5.Add(type10, (object) xamlTypeResolver5);
        xamlServiceProvider5.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(29, 21)));
        object obj10 = ((IMarkupExtension) resourceExtension16).ProvideValue((IServiceProvider) xamlServiceProvider5);
        ((NavigableElement) label2).set_Style((Style) obj10);
        bindingExtension2.set_StringFormat("{0:d}");
        bindingExtension2.set_Path("PostaladaElem.Uzenet.FeladoNevWithTitulus");
        BindingBase bindingBase2 = ((IMarkupExtension<BindingBase>) bindingExtension2).ProvideValue((IServiceProvider) null);
        ((BindableObject) label2).SetBinding((BindableProperty) Label.TextProperty, bindingBase2);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label2);
        resourceExtension5.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension17 = resourceExtension5;
        XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
        Type type11 = typeof (IProvideValueTarget);
        object[] objArray6 = new object[0 + 5];
        objArray6[0] = (object) label3;
        objArray6[1] = (object) stackLayout2;
        objArray6[2] = (object) grid2;
        objArray6[3] = (object) scrollView;
        objArray6[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider6;
        object obj11 = (object) (valueTargetProvider6 = new SimpleValueTargetProvider(objArray6, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider6.Add(type11, (object) valueTargetProvider6);
        xamlServiceProvider6.Add(typeof (IReferenceProvider), obj11);
        Type type12 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver6 = new XmlNamespaceResolver();
        namespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver6.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver6.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver6.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver6.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver6.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver6.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver6.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver6.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver6 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver6, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider6.Add(type12, (object) xamlTypeResolver6);
        xamlServiceProvider6.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(32, 24)));
        object obj12 = ((IMarkupExtension) resourceExtension17).ProvideValue((IServiceProvider) xamlServiceProvider6);
        ((NavigableElement) label3).set_Style((Style) obj12);
        translateExtension2.Text = "Uzenet_Cimzettek_Title";
        TranslateExtension translateExtension9 = translateExtension2;
        XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
        Type type13 = typeof (IProvideValueTarget);
        object[] objArray7 = new object[0 + 5];
        objArray7[0] = (object) label3;
        objArray7[1] = (object) stackLayout2;
        objArray7[2] = (object) grid2;
        objArray7[3] = (object) scrollView;
        objArray7[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider7;
        object obj13 = (object) (valueTargetProvider7 = new SimpleValueTargetProvider(objArray7, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider7.Add(type13, (object) valueTargetProvider7);
        xamlServiceProvider7.Add(typeof (IReferenceProvider), obj13);
        Type type14 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver7 = new XmlNamespaceResolver();
        namespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver7.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver7.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver7.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver7.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver7.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver7.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver7.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver7.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver7 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver7, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider7.Add(type14, (object) xamlTypeResolver7);
        xamlServiceProvider7.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(32, 70)));
        object obj14 = ((IMarkupExtension) translateExtension9).ProvideValue((IServiceProvider) xamlServiceProvider7);
        label3.set_Text((string) obj14);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label3);
        ((BindableObject) label4).SetValue((BindableProperty) View.MarginProperty, (object) new Thickness(6.0, 0.0, 0.0, 8.0));
        ((BindableObject) label4).SetValue((BindableProperty) VisualElement.BackgroundColorProperty, (object) new Color(0.972549021244049, 0.972549021244049, 0.972549021244049, 1.0));
        resourceExtension6.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension18 = resourceExtension6;
        XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
        Type type15 = typeof (IProvideValueTarget);
        object[] objArray8 = new object[0 + 5];
        objArray8[0] = (object) label4;
        objArray8[1] = (object) stackLayout2;
        objArray8[2] = (object) grid2;
        objArray8[3] = (object) scrollView;
        objArray8[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider8;
        object obj15 = (object) (valueTargetProvider8 = new SimpleValueTargetProvider(objArray8, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider8.Add(type15, (object) valueTargetProvider8);
        xamlServiceProvider8.Add(typeof (IReferenceProvider), obj15);
        Type type16 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver8 = new XmlNamespaceResolver();
        namespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver8.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver8.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver8.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver8.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver8.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver8.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver8.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver8.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver8 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver8, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider8.Add(type16, (object) xamlTypeResolver8);
        xamlServiceProvider8.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(36, 21)));
        object obj16 = ((IMarkupExtension) resourceExtension18).ProvideValue((IServiceProvider) xamlServiceProvider8);
        ((NavigableElement) label4).set_Style((Style) obj16);
        bindingExtension3.set_Path("Cimzettek");
        BindingBase bindingBase3 = ((IMarkupExtension<BindingBase>) bindingExtension3).ProvideValue((IServiceProvider) null);
        ((BindableObject) label4).SetBinding((BindableProperty) Label.TextProperty, bindingBase3);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label4);
        resourceExtension7.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension19 = resourceExtension7;
        XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
        Type type17 = typeof (IProvideValueTarget);
        object[] objArray9 = new object[0 + 5];
        objArray9[0] = (object) label5;
        objArray9[1] = (object) stackLayout2;
        objArray9[2] = (object) grid2;
        objArray9[3] = (object) scrollView;
        objArray9[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider9;
        object obj17 = (object) (valueTargetProvider9 = new SimpleValueTargetProvider(objArray9, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider9.Add(type17, (object) valueTargetProvider9);
        xamlServiceProvider9.Add(typeof (IReferenceProvider), obj17);
        Type type18 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver9 = new XmlNamespaceResolver();
        namespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver9.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver9.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver9.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver9.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver9.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver9.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver9.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver9.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver9 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver9, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider9.Add(type18, (object) xamlTypeResolver9);
        xamlServiceProvider9.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(39, 24)));
        object obj18 = ((IMarkupExtension) resourceExtension19).ProvideValue((IServiceProvider) xamlServiceProvider9);
        ((NavigableElement) label5).set_Style((Style) obj18);
        translateExtension3.Text = "Uzenet_Targy_Title";
        TranslateExtension translateExtension10 = translateExtension3;
        XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
        Type type19 = typeof (IProvideValueTarget);
        object[] objArray10 = new object[0 + 5];
        objArray10[0] = (object) label5;
        objArray10[1] = (object) stackLayout2;
        objArray10[2] = (object) grid2;
        objArray10[3] = (object) scrollView;
        objArray10[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider10;
        object obj19 = (object) (valueTargetProvider10 = new SimpleValueTargetProvider(objArray10, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider10.Add(type19, (object) valueTargetProvider10);
        xamlServiceProvider10.Add(typeof (IReferenceProvider), obj19);
        Type type20 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver10 = new XmlNamespaceResolver();
        namespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver10.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver10.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver10.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver10.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver10.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver10.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver10.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver10.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver10 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver10, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider10.Add(type20, (object) xamlTypeResolver10);
        xamlServiceProvider10.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(39, 70)));
        object obj20 = ((IMarkupExtension) translateExtension10).ProvideValue((IServiceProvider) xamlServiceProvider10);
        label5.set_Text((string) obj20);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label5);
        ((BindableObject) label6).SetValue((BindableProperty) View.MarginProperty, (object) new Thickness(6.0, 0.0, 0.0, 8.0));
        ((BindableObject) label6).SetValue((BindableProperty) VisualElement.BackgroundColorProperty, (object) new Color(0.972549021244049, 0.972549021244049, 0.972549021244049, 1.0));
        resourceExtension8.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension20 = resourceExtension8;
        XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
        Type type21 = typeof (IProvideValueTarget);
        object[] objArray11 = new object[0 + 5];
        objArray11[0] = (object) label6;
        objArray11[1] = (object) stackLayout2;
        objArray11[2] = (object) grid2;
        objArray11[3] = (object) scrollView;
        objArray11[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider11;
        object obj21 = (object) (valueTargetProvider11 = new SimpleValueTargetProvider(objArray11, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider11.Add(type21, (object) valueTargetProvider11);
        xamlServiceProvider11.Add(typeof (IReferenceProvider), obj21);
        Type type22 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver11 = new XmlNamespaceResolver();
        namespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver11.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver11.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver11.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver11.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver11.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver11.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver11.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver11.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver11 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver11, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider11.Add(type22, (object) xamlTypeResolver11);
        xamlServiceProvider11.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(43, 21)));
        object obj22 = ((IMarkupExtension) resourceExtension20).ProvideValue((IServiceProvider) xamlServiceProvider11);
        ((NavigableElement) label6).set_Style((Style) obj22);
        bindingExtension4.set_Path("PostaladaElem.Uzenet.Targy");
        BindingBase bindingBase4 = ((IMarkupExtension<BindingBase>) bindingExtension4).ProvideValue((IServiceProvider) null);
        ((BindableObject) label6).SetBinding((BindableProperty) Label.TextProperty, bindingBase4);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label6);
        resourceExtension9.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension21 = resourceExtension9;
        XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
        Type type23 = typeof (IProvideValueTarget);
        object[] objArray12 = new object[0 + 5];
        objArray12[0] = (object) label7;
        objArray12[1] = (object) stackLayout2;
        objArray12[2] = (object) grid2;
        objArray12[3] = (object) scrollView;
        objArray12[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider12;
        object obj23 = (object) (valueTargetProvider12 = new SimpleValueTargetProvider(objArray12, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider12.Add(type23, (object) valueTargetProvider12);
        xamlServiceProvider12.Add(typeof (IReferenceProvider), obj23);
        Type type24 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver12 = new XmlNamespaceResolver();
        namespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver12.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver12.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver12.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver12.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver12.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver12.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver12.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver12.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver12 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver12, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider12.Add(type24, (object) xamlTypeResolver12);
        xamlServiceProvider12.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(48, 21)));
        object obj24 = ((IMarkupExtension) resourceExtension21).ProvideValue((IServiceProvider) xamlServiceProvider12);
        ((NavigableElement) label7).set_Style((Style) obj24);
        translateExtension4.Text = "Uzenet_Csatolmanyok_Title";
        TranslateExtension translateExtension11 = translateExtension4;
        XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
        Type type25 = typeof (IProvideValueTarget);
        object[] objArray13 = new object[0 + 5];
        objArray13[0] = (object) label7;
        objArray13[1] = (object) stackLayout2;
        objArray13[2] = (object) grid2;
        objArray13[3] = (object) scrollView;
        objArray13[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider13;
        object obj25 = (object) (valueTargetProvider13 = new SimpleValueTargetProvider(objArray13, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider13.Add(type25, (object) valueTargetProvider13);
        xamlServiceProvider13.Add(typeof (IReferenceProvider), obj25);
        Type type26 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver13 = new XmlNamespaceResolver();
        namespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver13.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver13.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver13.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver13.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver13.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver13.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver13.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver13.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver13 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver13, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider13.Add(type26, (object) xamlTypeResolver13);
        xamlServiceProvider13.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(49, 21)));
        object obj26 = ((IMarkupExtension) translateExtension11).ProvideValue((IServiceProvider) xamlServiceProvider13);
        label7.set_Text((string) obj26);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label7);
        ((BindableObject) stackLayout1).SetValue((BindableProperty) View.MarginProperty, (object) new Thickness(6.0, 0.0, 0.0, 8.0));
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) stackLayout1);
        resourceExtension10.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension22 = resourceExtension10;
        XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
        Type type27 = typeof (IProvideValueTarget);
        object[] objArray14 = new object[0 + 5];
        objArray14[0] = (object) label8;
        objArray14[1] = (object) stackLayout2;
        objArray14[2] = (object) grid2;
        objArray14[3] = (object) scrollView;
        objArray14[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider14;
        object obj27 = (object) (valueTargetProvider14 = new SimpleValueTargetProvider(objArray14, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider14.Add(type27, (object) valueTargetProvider14);
        xamlServiceProvider14.Add(typeof (IReferenceProvider), obj27);
        Type type28 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver14 = new XmlNamespaceResolver();
        namespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver14.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver14.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver14.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver14.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver14.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver14.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver14.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver14.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver14 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver14, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider14.Add(type28, (object) xamlTypeResolver14);
        xamlServiceProvider14.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(52, 24)));
        object obj28 = ((IMarkupExtension) resourceExtension22).ProvideValue((IServiceProvider) xamlServiceProvider14);
        ((NavigableElement) label8).set_Style((Style) obj28);
        translateExtension5.Text = "Uzenet_Szoveg_Title";
        TranslateExtension translateExtension12 = translateExtension5;
        XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
        Type type29 = typeof (IProvideValueTarget);
        object[] objArray15 = new object[0 + 5];
        objArray15[0] = (object) label8;
        objArray15[1] = (object) stackLayout2;
        objArray15[2] = (object) grid2;
        objArray15[3] = (object) scrollView;
        objArray15[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider15;
        object obj29 = (object) (valueTargetProvider15 = new SimpleValueTargetProvider(objArray15, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider15.Add(type29, (object) valueTargetProvider15);
        xamlServiceProvider15.Add(typeof (IReferenceProvider), obj29);
        Type type30 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver15 = new XmlNamespaceResolver();
        namespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver15.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver15.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver15.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver15.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver15.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver15.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver15.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver15.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver15 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver15, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider15.Add(type30, (object) xamlTypeResolver15);
        xamlServiceProvider15.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(52, 70)));
        object obj30 = ((IMarkupExtension) translateExtension12).ProvideValue((IServiceProvider) xamlServiceProvider15);
        label8.set_Text((string) obj30);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label8);
        ((BindableObject) label9).SetValue((BindableProperty) View.MarginProperty, (object) new Thickness(6.0, 0.0, 0.0, 0.0));
        bindingExtension5.set_Path("IsPossibliTruncated");
        BindingBase bindingBase5 = ((IMarkupExtension<BindingBase>) bindingExtension5).ProvideValue((IServiceProvider) null);
        ((BindableObject) label9).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase5);
        translateExtension6.Text = "MessageDetailViewMessageMayTruncated_Title";
        TranslateExtension translateExtension13 = translateExtension6;
        XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
        Type type31 = typeof (IProvideValueTarget);
        object[] objArray16 = new object[0 + 5];
        objArray16[0] = (object) label9;
        objArray16[1] = (object) stackLayout2;
        objArray16[2] = (object) grid2;
        objArray16[3] = (object) scrollView;
        objArray16[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider16;
        object obj31 = (object) (valueTargetProvider16 = new SimpleValueTargetProvider(objArray16, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider16.Add(type31, (object) valueTargetProvider16);
        xamlServiceProvider16.Add(typeof (IReferenceProvider), obj31);
        Type type32 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver16 = new XmlNamespaceResolver();
        namespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver16.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver16.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver16.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver16.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver16.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver16.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver16.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver16.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver16 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver16, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider16.Add(type32, (object) xamlTypeResolver16);
        xamlServiceProvider16.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(57, 21)));
        object obj32 = ((IMarkupExtension) translateExtension13).ProvideValue((IServiceProvider) xamlServiceProvider16);
        label9.set_Text((string) obj32);
        ((BindableObject) label9).SetValue((BindableProperty) Label.TextColorProperty, (object) (Color) Color.Red);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label9);
        ((BindableObject) label10).SetValue((BindableProperty) View.MarginProperty, (object) new Thickness(6.0, 0.0, 0.0, 8.0));
        bindingExtension6.set_Path("IsPossibliTruncated");
        BindingBase bindingBase6 = ((IMarkupExtension<BindingBase>) bindingExtension6).ProvideValue((IServiceProvider) null);
        ((BindableObject) label10).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase6);
        translateExtension7.Text = "MessageDetailViewMessageMayTruncated";
        TranslateExtension translateExtension14 = translateExtension7;
        XamlServiceProvider xamlServiceProvider17 = new XamlServiceProvider();
        Type type33 = typeof (IProvideValueTarget);
        object[] objArray17 = new object[0 + 5];
        objArray17[0] = (object) label10;
        objArray17[1] = (object) stackLayout2;
        objArray17[2] = (object) grid2;
        objArray17[3] = (object) scrollView;
        objArray17[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider17;
        object obj33 = (object) (valueTargetProvider17 = new SimpleValueTargetProvider(objArray17, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider17.Add(type33, (object) valueTargetProvider17);
        xamlServiceProvider17.Add(typeof (IReferenceProvider), obj33);
        Type type34 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver17 = new XmlNamespaceResolver();
        namespaceResolver17.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver17.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver17.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver17.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver17.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver17.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver17.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver17.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver17.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver17.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver17 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver17, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider17.Add(type34, (object) xamlTypeResolver17);
        xamlServiceProvider17.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(63, 21)));
        object obj34 = ((IMarkupExtension) translateExtension14).ProvideValue((IServiceProvider) xamlServiceProvider17);
        label10.set_Text((string) obj34);
        ((BindableObject) label10).SetValue((BindableProperty) Label.TextColorProperty, (object) (Color) Color.Red);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) label10);
        ((BindableObject) webView).SetValue((BindableProperty) View.MarginProperty, (object) new Thickness(6.0, 0.0, 0.0, 8.0));
        ((BindableObject) webView).SetValue((BindableProperty) VisualElement.BackgroundColorProperty, (object) new Color(0.972549021244049, 0.972549021244049, 0.972549021244049, 1.0));
        ((BindableObject) webView).SetValue((BindableProperty) VisualElement.HeightRequestProperty, (object) 300.0);
        ((BindableObject) webView).SetValue((BindableProperty) View.HorizontalOptionsProperty, (object) (LayoutOptions) LayoutOptions.FillAndExpand);
        webView.add_Navigating(new EventHandler<WebNavigatingEventArgs>(messageDetailPage.WebView_OnNavigating));
        bindingExtension7.set_Path("PostaladaElem.WebViewSource");
        BindingBase bindingBase7 = ((IMarkupExtension<BindingBase>) bindingExtension7).ProvideValue((IServiceProvider) null);
        ((BindableObject) webView).SetBinding((BindableProperty) WebView.SourceProperty, bindingBase7);
        ((BindableObject) webView).SetValue((BindableProperty) View.VerticalOptionsProperty, (object) (LayoutOptions) LayoutOptions.FillAndExpand);
        ((ICollection<View>) ((Layout<View>) stackLayout2).get_Children()).Add((View) webView);
        ((ICollection<View>) grid2.get_Children()).Add((View) stackLayout2);
        resourceExtension11.set_Key("OverlayColor");
        StaticResourceExtension resourceExtension23 = resourceExtension11;
        XamlServiceProvider xamlServiceProvider18 = new XamlServiceProvider();
        Type type35 = typeof (IProvideValueTarget);
        object[] objArray18 = new object[0 + 4];
        objArray18[0] = (object) grid1;
        objArray18[1] = (object) grid2;
        objArray18[2] = (object) scrollView;
        objArray18[3] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider18;
        object obj35 = (object) (valueTargetProvider18 = new SimpleValueTargetProvider(objArray18, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope));
        xamlServiceProvider18.Add(type35, (object) valueTargetProvider18);
        xamlServiceProvider18.Add(typeof (IReferenceProvider), obj35);
        Type type36 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver18 = new XmlNamespaceResolver();
        namespaceResolver18.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver18.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver18.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver18.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver18.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver18.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver18.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver18.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver18.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver18.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver18 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver18, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider18.Add(type36, (object) xamlTypeResolver18);
        xamlServiceProvider18.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(75, 19)));
        object obj36 = ((IMarkupExtension) resourceExtension23).ProvideValue((IServiceProvider) xamlServiceProvider18);
        ((VisualElement) grid1).set_BackgroundColor((Color) obj36);
        bindingExtension8.set_Path("IsLoading");
        BindingBase bindingBase8 = ((IMarkupExtension<BindingBase>) bindingExtension8).ProvideValue((IServiceProvider) null);
        ((BindableObject) grid1).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase8);
        ((BindableObject) circleImage).SetValue((BindableProperty) CircleImage.FillColorProperty, (object) (Color) Color.White);
        resourceExtension12.set_Key("ListItemIconStyle");
        StaticResourceExtension resourceExtension24 = resourceExtension12;
        XamlServiceProvider xamlServiceProvider19 = new XamlServiceProvider();
        Type type37 = typeof (IProvideValueTarget);
        object[] objArray19 = new object[0 + 5];
        objArray19[0] = (object) circleImage;
        objArray19[1] = (object) grid1;
        objArray19[2] = (object) grid2;
        objArray19[3] = (object) scrollView;
        objArray19[4] = (object) messageDetailPage;
        SimpleValueTargetProvider valueTargetProvider19;
        object obj37 = (object) (valueTargetProvider19 = new SimpleValueTargetProvider(objArray19, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider19.Add(type37, (object) valueTargetProvider19);
        xamlServiceProvider19.Add(typeof (IReferenceProvider), obj37);
        Type type38 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver19 = new XmlNamespaceResolver();
        namespaceResolver19.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver19.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver19.Add("controls", "clr-namespace:Ekreta.Mobile.Core.Controls;assembly=Ekreta.Mobile.Core");
        namespaceResolver19.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver19.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver19.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver19.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver19.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver19.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver19.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver19 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver19, typeof (MessageDetailPage).GetTypeInfo().Assembly);
        xamlServiceProvider19.Add(type38, (object) xamlTypeResolver19);
        xamlServiceProvider19.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(76, 60)));
        object obj38 = ((IMarkupExtension) resourceExtension24).ProvideValue((IServiceProvider) xamlServiceProvider19);
        ((NavigableElement) circleImage).set_Style((Style) obj38);
        ((ICollection<View>) grid1.get_Children()).Add((View) circleImage);
        bindingExtension9.set_Path("IsLoading");
        BindingBase bindingBase9 = ((IMarkupExtension<BindingBase>) bindingExtension9).ProvideValue((IServiceProvider) null);
        ((BindableObject) activityIndicator).SetBinding((BindableProperty) ActivityIndicator.IsRunningProperty, bindingBase9);
        ((ICollection<View>) grid1.get_Children()).Add((View) activityIndicator);
        ((ICollection<View>) grid2.get_Children()).Add((View) grid1);
        scrollView.set_Content((View) grid2);
        ((BindableObject) messageDetailPage).SetValue((BindableProperty) ContentPage.ContentProperty, (object) scrollView);
      }
    }

    private void __InitComponentRuntime()
    {
      Xamarin.Forms.Xaml.Extensions.LoadFromXaml<MessageDetailPage>((M0) this, typeof (MessageDetailPage));
      this.CsatolmanyokLabel = (Label) NameScopeExtensions.FindByName<Label>((Element) this, "CsatolmanyokLabel");
      this.CsatolmanyokBox = (StackLayout) NameScopeExtensions.FindByName<StackLayout>((Element) this, "CsatolmanyokBox");
    }
  }
}
