// Decompiled with JetBrains decompiler
// Type: Ekreta.Mobile.Core.Views.SettingsPage
// Assembly: Ekreta.Mobile.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5AA13053-CF9F-480D-A76A-8A5D6C4EE194
// Assembly location: C:\fakepath\\Desktop\Ekreta.Mobile.Core.dll

using Ekreta.Mobile.Core.Extensions;
using Ekreta.Mobile.Core.ViewModels;
using ImageCircle.Forms.Plugin.Abstractions;
using MvvmCross.Forms.Presenters.Attributes;
using MvvmCross.Forms.Views;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Reflection;
using System.Xml;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Internals;
using Xamarin.RangeSlider.Common;

namespace Ekreta.Mobile.Core.Views
{
  [XamlCompilation]
  [MvxMasterDetailPagePresentation]
  [XamlFilePath("Views/SettingsPage.xaml")]
  public class SettingsPage : MvxContentPage<SettingsViewModel>
  {
    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private MvxContentPage<SettingsViewModel> Page;
    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private Xamarin.RangeSlider.Forms.RangeSlider DashboardItemCountSlider;

    public SettingsPage()
    {
      base.\u002Ector();
      this.InitializeComponent();
      this.DashboardItemCountSlider.set_FormatLabel(new Func<Thumb, float, string>(this.FormatLabel));
    }

    private string FormatLabel(Thumb thumb, float val)
    {
      double num = Math.Floor((double) val);
      return num == 0.0 ? "Mai nap" : num.ToString() + " nap";
    }

    private void ChangeDashboardItemCount(object sender, EventArgs e)
    {
      this.get_ViewModel().DashboardDayRange = (int) Math.Floor((double) this.DashboardItemCountSlider.get_UpperValue());
    }

    [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
    private void InitializeComponent()
    {
      ResourceLoader.ResourceLoadingQuery resourceLoadingQuery = new ResourceLoader.ResourceLoadingQuery();
      resourceLoadingQuery.set_AssemblyName(typeof (SettingsPage).GetTypeInfo().Assembly.GetName());
      resourceLoadingQuery.set_ResourcePath("Views/SettingsPage.xaml");
      resourceLoadingQuery.set_Instance((object) this);
      if (ResourceLoader.CanProvideContentFor(resourceLoadingQuery))
        this.__InitComponentRuntime();
      else if (XamlLoader.get_XamlFileProvider() != null && XamlLoader.get_XamlFileProvider()(((object) this).GetType()) != null)
      {
        this.__InitComponentRuntime();
      }
      else
      {
        TranslateExtension translateExtension1 = new TranslateExtension();
        StaticResourceExtension resourceExtension1 = new StaticResourceExtension();
        StaticResourceExtension resourceExtension2 = new StaticResourceExtension();
        RowDefinition rowDefinition1 = new RowDefinition();
        RowDefinition rowDefinition2 = new RowDefinition();
        StaticResourceExtension resourceExtension3 = new StaticResourceExtension();
        ColumnDefinition columnDefinition1 = new ColumnDefinition();
        ColumnDefinition columnDefinition2 = new ColumnDefinition();
        RowDefinition rowDefinition3 = new RowDefinition();
        RowDefinition rowDefinition4 = new RowDefinition();
        RowDefinition rowDefinition5 = new RowDefinition();
        StaticResourceExtension resourceExtension4 = new StaticResourceExtension();
        TranslateExtension translateExtension2 = new TranslateExtension();
        Label label1 = new Label();
        BindingExtension bindingExtension1 = new BindingExtension();
        BindingExtension bindingExtension2 = new BindingExtension();
        Switch @switch = new Switch();
        StaticResourceExtension resourceExtension5 = new StaticResourceExtension();
        TranslateExtension translateExtension3 = new TranslateExtension();
        Label label2 = new Label();
        BindingExtension bindingExtension3 = new BindingExtension();
        TranslateExtension translateExtension4 = new TranslateExtension();
        Label label3 = new Label();
        Grid grid1 = new Grid();
        Frame frame1 = new Frame();
        StaticResourceExtension resourceExtension6 = new StaticResourceExtension();
        StaticResourceExtension resourceExtension7 = new StaticResourceExtension();
        TranslateExtension translateExtension5 = new TranslateExtension();
        Label label4 = new Label();
        StaticResourceExtension resourceExtension8 = new StaticResourceExtension();
        TranslateExtension translateExtension6 = new TranslateExtension();
        Label label5 = new Label();
        BindingExtension bindingExtension4 = new BindingExtension();
        Xamarin.RangeSlider.Forms.RangeSlider rangeSlider1 = new Xamarin.RangeSlider.Forms.RangeSlider();
        StackLayout stackLayout = new StackLayout();
        Frame frame2 = new Frame();
        Grid grid2 = new Grid();
        StaticResourceExtension resourceExtension9 = new StaticResourceExtension();
        BindingExtension bindingExtension5 = new BindingExtension();
        StaticResourceExtension resourceExtension10 = new StaticResourceExtension();
        CircleImage circleImage = new CircleImage();
        BindingExtension bindingExtension6 = new BindingExtension();
        BindingExtension bindingExtension7 = new BindingExtension();
        ActivityIndicator activityIndicator = new ActivityIndicator();
        Grid grid3 = new Grid();
        Grid grid4 = new Grid();
        SettingsPage settingsPage;
        NameScope nameScope = (NameScope) (NameScope.GetNameScope((BindableObject) (settingsPage = this)) ?? (INameScope) new NameScope());
        NameScope.SetNameScope((BindableObject) settingsPage, (INameScope) nameScope);
        ((INameScope) nameScope).RegisterName("Page", (object) settingsPage);
        if (((Element) settingsPage).get_StyleId() == null)
          ((Element) settingsPage).set_StyleId("Page");
        ((INameScope) nameScope).RegisterName("DashboardItemCountSlider", (object) rangeSlider1);
        if (((Element) rangeSlider1).get_StyleId() == null)
          ((Element) rangeSlider1).set_StyleId("DashboardItemCountSlider");
        this.Page = (MvxContentPage<SettingsViewModel>) settingsPage;
        this.DashboardItemCountSlider = rangeSlider1;
        translateExtension1.Text = "Settings_Page_Title";
        TranslateExtension translateExtension7 = translateExtension1;
        XamlServiceProvider xamlServiceProvider1 = new XamlServiceProvider();
        Type type1 = typeof (IProvideValueTarget);
        object[] objArray1 = new object[0 + 1];
        objArray1[0] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider1;
        object obj1 = (object) (valueTargetProvider1 = new SimpleValueTargetProvider(objArray1, (object) Xamarin.Forms.Page.TitleProperty, (INameScope) nameScope));
        xamlServiceProvider1.Add(type1, (object) valueTargetProvider1);
        xamlServiceProvider1.Add(typeof (IReferenceProvider), obj1);
        Type type2 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver1 = new XmlNamespaceResolver();
        namespaceResolver1.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver1.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver1.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver1.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver1.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver1.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver1.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver1.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver1.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver1.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver1 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver1, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider1.Add(type2, (object) xamlTypeResolver1);
        xamlServiceProvider1.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(15, 5)));
        object obj2 = ((IMarkupExtension) translateExtension7).ProvideValue((IServiceProvider) xamlServiceProvider1);
        ((Xamarin.Forms.Page) settingsPage).set_Title((string) obj2);
        ((BindableObject) settingsPage).SetValue((BindableProperty) Xamarin.Forms.PlatformConfiguration.iOSSpecific.Page.UseSafeAreaProperty, (object) true);
        resourceExtension1.set_Key("PageBackgroundColor");
        StaticResourceExtension resourceExtension11 = resourceExtension1;
        XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
        Type type3 = typeof (IProvideValueTarget);
        object[] objArray2 = new object[0 + 1];
        objArray2[0] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider2;
        object obj3 = (object) (valueTargetProvider2 = new SimpleValueTargetProvider(objArray2, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope));
        xamlServiceProvider2.Add(type3, (object) valueTargetProvider2);
        xamlServiceProvider2.Add(typeof (IReferenceProvider), obj3);
        Type type4 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver2 = new XmlNamespaceResolver();
        namespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver2.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver2.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver2.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver2.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver2.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver2.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver2.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver2.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver2 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver2, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider2.Add(type4, (object) xamlTypeResolver2);
        xamlServiceProvider2.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(18, 5)));
        object obj4 = ((IMarkupExtension) resourceExtension11).ProvideValue((IServiceProvider) xamlServiceProvider2);
        ((VisualElement) settingsPage).set_BackgroundColor((Color) obj4);
        resourceExtension2.set_Key("ContentPadding");
        StaticResourceExtension resourceExtension12 = resourceExtension2;
        XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
        Type type5 = typeof (IProvideValueTarget);
        object[] objArray3 = new object[0 + 3];
        objArray3[0] = (object) grid2;
        objArray3[1] = (object) grid4;
        objArray3[2] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider3;
        object obj5 = (object) (valueTargetProvider3 = new SimpleValueTargetProvider(objArray3, (object) View.MarginProperty, (INameScope) nameScope));
        xamlServiceProvider3.Add(type5, (object) valueTargetProvider3);
        xamlServiceProvider3.Add(typeof (IReferenceProvider), obj5);
        Type type6 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver3 = new XmlNamespaceResolver();
        namespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver3.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver3.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver3.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver3.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver3.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver3.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver3.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver3.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver3 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver3, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider3.Add(type6, (object) xamlTypeResolver3);
        xamlServiceProvider3.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(24, 15)));
        object obj6 = ((IMarkupExtension) resourceExtension12).ProvideValue((IServiceProvider) xamlServiceProvider3);
        ((View) grid2).set_Margin((Thickness) obj6);
        ((BindableObject) grid2).SetValue((BindableProperty) View.VerticalOptionsProperty, (object) (LayoutOptions) LayoutOptions.FillAndExpand);
        ((BindableObject) rowDefinition1).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid2).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition1);
        ((BindableObject) rowDefinition2).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid2).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition2);
        ((BindableObject) frame1).SetValue((BindableProperty) Grid.RowProperty, (object) 0);
        ((BindableObject) frame1).SetValue((BindableProperty) Layout.PaddingProperty, (object) new Thickness(6.0));
        resourceExtension3.set_Key("AccentContrastColor");
        StaticResourceExtension resourceExtension13 = resourceExtension3;
        XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
        Type type7 = typeof (IProvideValueTarget);
        object[] objArray4 = new object[0 + 4];
        objArray4[0] = (object) frame1;
        objArray4[1] = (object) grid2;
        objArray4[2] = (object) grid4;
        objArray4[3] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider4;
        object obj7 = (object) (valueTargetProvider4 = new SimpleValueTargetProvider(objArray4, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope));
        xamlServiceProvider4.Add(type7, (object) valueTargetProvider4);
        xamlServiceProvider4.Add(typeof (IReferenceProvider), obj7);
        Type type8 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver4 = new XmlNamespaceResolver();
        namespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver4.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver4.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver4.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver4.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver4.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver4.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver4.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver4.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver4 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver4, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider4.Add(type8, (object) xamlTypeResolver4);
        xamlServiceProvider4.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(32, 17)));
        object obj8 = ((IMarkupExtension) resourceExtension13).ProvideValue((IServiceProvider) xamlServiceProvider4);
        ((VisualElement) frame1).set_BackgroundColor((Color) obj8);
        ((BindableObject) frame1).SetValue((BindableProperty) Frame.HasShadowProperty, (object) true);
        ((BindableObject) grid1).SetValue((BindableProperty) View.VerticalOptionsProperty, (object) (LayoutOptions) LayoutOptions.Center);
        ((BindableObject) columnDefinition1).SetValue((BindableProperty) ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
        ((DefinitionCollection<ColumnDefinition>) ((BindableObject) grid1).GetValue((BindableProperty) Grid.ColumnDefinitionsProperty)).Add(columnDefinition1);
        ((BindableObject) columnDefinition2).SetValue((BindableProperty) ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<ColumnDefinition>) ((BindableObject) grid1).GetValue((BindableProperty) Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
        ((BindableObject) rowDefinition3).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid1).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition3);
        ((BindableObject) rowDefinition4).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid1).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition4);
        ((BindableObject) rowDefinition5).SetValue((BindableProperty) RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
        ((DefinitionCollection<RowDefinition>) ((BindableObject) grid1).GetValue((BindableProperty) Grid.RowDefinitionsProperty)).Add(rowDefinition5);
        ((BindableObject) label1).SetValue((BindableProperty) Grid.RowProperty, (object) 0);
        ((BindableObject) label1).SetValue((BindableProperty) Grid.ColumnProperty, (object) 0);
        resourceExtension4.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension14 = resourceExtension4;
        XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
        Type type9 = typeof (IProvideValueTarget);
        object[] objArray5 = new object[0 + 6];
        objArray5[0] = (object) label1;
        objArray5[1] = (object) grid1;
        objArray5[2] = (object) frame1;
        objArray5[3] = (object) grid2;
        objArray5[4] = (object) grid4;
        objArray5[5] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider5;
        object obj9 = (object) (valueTargetProvider5 = new SimpleValueTargetProvider(objArray5, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider5.Add(type9, (object) valueTargetProvider5);
        xamlServiceProvider5.Add(typeof (IReferenceProvider), obj9);
        Type type10 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver5 = new XmlNamespaceResolver();
        namespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver5.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver5.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver5.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver5.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver5.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver5.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver5.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver5.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver5 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver5, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider5.Add(type10, (object) xamlTypeResolver5);
        xamlServiceProvider5.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(47, 25)));
        object obj10 = ((IMarkupExtension) resourceExtension14).ProvideValue((IServiceProvider) xamlServiceProvider5);
        ((NavigableElement) label1).set_Style((Style) obj10);
        translateExtension2.Text = "Settings_Notification_Title";
        TranslateExtension translateExtension8 = translateExtension2;
        XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
        Type type11 = typeof (IProvideValueTarget);
        object[] objArray6 = new object[0 + 6];
        objArray6[0] = (object) label1;
        objArray6[1] = (object) grid1;
        objArray6[2] = (object) frame1;
        objArray6[3] = (object) grid2;
        objArray6[4] = (object) grid4;
        objArray6[5] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider6;
        object obj11 = (object) (valueTargetProvider6 = new SimpleValueTargetProvider(objArray6, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider6.Add(type11, (object) valueTargetProvider6);
        xamlServiceProvider6.Add(typeof (IReferenceProvider), obj11);
        Type type12 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver6 = new XmlNamespaceResolver();
        namespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver6.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver6.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver6.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver6.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver6.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver6.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver6.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver6.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver6 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver6, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider6.Add(type12, (object) xamlTypeResolver6);
        xamlServiceProvider6.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(48, 25)));
        object obj12 = ((IMarkupExtension) translateExtension8).ProvideValue((IServiceProvider) xamlServiceProvider6);
        label1.set_Text((string) obj12);
        ((ICollection<View>) grid1.get_Children()).Add((View) label1);
        ((BindableObject) @switch).SetValue((BindableProperty) Grid.RowProperty, (object) 0);
        ((BindableObject) @switch).SetValue((BindableProperty) Grid.ColumnProperty, (object) 1);
        ((BindableObject) @switch).SetValue((BindableProperty) View.HorizontalOptionsProperty, (object) (LayoutOptions) LayoutOptions.End);
        bindingExtension1.set_Path("HasInternetConnection");
        BindingBase bindingBase1 = ((IMarkupExtension<BindingBase>) bindingExtension1).ProvideValue((IServiceProvider) null);
        ((BindableObject) @switch).SetBinding((BindableProperty) VisualElement.IsEnabledProperty, bindingBase1);
        bindingExtension2.set_Path("IsPushNotificationEnabled");
        BindingBase bindingBase2 = ((IMarkupExtension<BindingBase>) bindingExtension2).ProvideValue((IServiceProvider) null);
        ((BindableObject) @switch).SetBinding((BindableProperty) Switch.IsToggledProperty, bindingBase2);
        ((BindableObject) @switch).SetValue((BindableProperty) View.VerticalOptionsProperty, (object) (LayoutOptions) LayoutOptions.Start);
        ((ICollection<View>) grid1.get_Children()).Add((View) @switch);
        ((BindableObject) label2).SetValue((BindableProperty) Grid.RowProperty, (object) 1);
        ((BindableObject) label2).SetValue((BindableProperty) Grid.ColumnProperty, (object) 0);
        resourceExtension5.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension15 = resourceExtension5;
        XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
        Type type13 = typeof (IProvideValueTarget);
        object[] objArray7 = new object[0 + 6];
        objArray7[0] = (object) label2;
        objArray7[1] = (object) grid1;
        objArray7[2] = (object) frame1;
        objArray7[3] = (object) grid2;
        objArray7[4] = (object) grid4;
        objArray7[5] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider7;
        object obj13 = (object) (valueTargetProvider7 = new SimpleValueTargetProvider(objArray7, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider7.Add(type13, (object) valueTargetProvider7);
        xamlServiceProvider7.Add(typeof (IReferenceProvider), obj13);
        Type type14 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver7 = new XmlNamespaceResolver();
        namespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver7.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver7.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver7.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver7.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver7.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver7.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver7.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver7.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver7 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver7, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider7.Add(type14, (object) xamlTypeResolver7);
        xamlServiceProvider7.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(59, 25)));
        object obj14 = ((IMarkupExtension) resourceExtension15).ProvideValue((IServiceProvider) xamlServiceProvider7);
        ((NavigableElement) label2).set_Style((Style) obj14);
        translateExtension3.Text = "Settings_Notification_Description";
        TranslateExtension translateExtension9 = translateExtension3;
        XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
        Type type15 = typeof (IProvideValueTarget);
        object[] objArray8 = new object[0 + 6];
        objArray8[0] = (object) label2;
        objArray8[1] = (object) grid1;
        objArray8[2] = (object) frame1;
        objArray8[3] = (object) grid2;
        objArray8[4] = (object) grid4;
        objArray8[5] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider8;
        object obj15 = (object) (valueTargetProvider8 = new SimpleValueTargetProvider(objArray8, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider8.Add(type15, (object) valueTargetProvider8);
        xamlServiceProvider8.Add(typeof (IReferenceProvider), obj15);
        Type type16 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver8 = new XmlNamespaceResolver();
        namespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver8.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver8.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver8.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver8.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver8.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver8.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver8.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver8.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver8 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver8, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider8.Add(type16, (object) xamlTypeResolver8);
        xamlServiceProvider8.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(60, 25)));
        object obj16 = ((IMarkupExtension) translateExtension9).ProvideValue((IServiceProvider) xamlServiceProvider8);
        label2.set_Text((string) obj16);
        ((ICollection<View>) grid1.get_Children()).Add((View) label2);
        ((BindableObject) label3).SetValue((BindableProperty) Grid.RowProperty, (object) 2);
        ((BindableObject) label3).SetValue((BindableProperty) Grid.ColumnProperty, (object) 0);
        ((BindableObject) label3).SetValue((BindableProperty) Grid.ColumnSpanProperty, (object) 2);
        bindingExtension3.set_Path("IsPushNotificationDisabledByDevice");
        BindingBase bindingBase3 = ((IMarkupExtension<BindingBase>) bindingExtension3).ProvideValue((IServiceProvider) null);
        ((BindableObject) label3).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase3);
        translateExtension4.Text = "Push_NeedEnable";
        TranslateExtension translateExtension10 = translateExtension4;
        XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
        Type type17 = typeof (IProvideValueTarget);
        object[] objArray9 = new object[0 + 6];
        objArray9[0] = (object) label3;
        objArray9[1] = (object) grid1;
        objArray9[2] = (object) frame1;
        objArray9[3] = (object) grid2;
        objArray9[4] = (object) grid4;
        objArray9[5] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider9;
        object obj17 = (object) (valueTargetProvider9 = new SimpleValueTargetProvider(objArray9, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider9.Add(type17, (object) valueTargetProvider9);
        xamlServiceProvider9.Add(typeof (IReferenceProvider), obj17);
        Type type18 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver9 = new XmlNamespaceResolver();
        namespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver9.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver9.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver9.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver9.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver9.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver9.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver9.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver9.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver9 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver9, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider9.Add(type18, (object) xamlTypeResolver9);
        xamlServiceProvider9.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(66, 25)));
        object obj18 = ((IMarkupExtension) translateExtension10).ProvideValue((IServiceProvider) xamlServiceProvider9);
        label3.set_Text((string) obj18);
        ((BindableObject) label3).SetValue((BindableProperty) Label.TextColorProperty, (object) (Color) Color.Red);
        ((ICollection<View>) grid1.get_Children()).Add((View) label3);
        ((BindableObject) frame1).SetValue((BindableProperty) ContentView.ContentProperty, (object) grid1);
        ((ICollection<View>) grid2.get_Children()).Add((View) frame1);
        ((BindableObject) frame2).SetValue((BindableProperty) Grid.RowProperty, (object) 1);
        ((BindableObject) frame2).SetValue((BindableProperty) Layout.PaddingProperty, (object) new Thickness(6.0));
        resourceExtension6.set_Key("AccentContrastColor");
        StaticResourceExtension resourceExtension16 = resourceExtension6;
        XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
        Type type19 = typeof (IProvideValueTarget);
        object[] objArray10 = new object[0 + 4];
        objArray10[0] = (object) frame2;
        objArray10[1] = (object) grid2;
        objArray10[2] = (object) grid4;
        objArray10[3] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider10;
        object obj19 = (object) (valueTargetProvider10 = new SimpleValueTargetProvider(objArray10, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope));
        xamlServiceProvider10.Add(type19, (object) valueTargetProvider10);
        xamlServiceProvider10.Add(typeof (IReferenceProvider), obj19);
        Type type20 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver10 = new XmlNamespaceResolver();
        namespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver10.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver10.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver10.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver10.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver10.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver10.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver10.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver10.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver10 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver10, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider10.Add(type20, (object) xamlTypeResolver10);
        xamlServiceProvider10.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(73, 17)));
        object obj20 = ((IMarkupExtension) resourceExtension16).ProvideValue((IServiceProvider) xamlServiceProvider10);
        ((VisualElement) frame2).set_BackgroundColor((Color) obj20);
        ((BindableObject) frame2).SetValue((BindableProperty) Frame.HasShadowProperty, (object) true);
        ((BindableObject) stackLayout).SetValue((BindableProperty) View.VerticalOptionsProperty, (object) (LayoutOptions) LayoutOptions.Center);
        resourceExtension7.set_Key("DetailDataStyle");
        StaticResourceExtension resourceExtension17 = resourceExtension7;
        XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
        Type type21 = typeof (IProvideValueTarget);
        object[] objArray11 = new object[0 + 6];
        objArray11[0] = (object) label4;
        objArray11[1] = (object) stackLayout;
        objArray11[2] = (object) frame2;
        objArray11[3] = (object) grid2;
        objArray11[4] = (object) grid4;
        objArray11[5] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider11;
        object obj21 = (object) (valueTargetProvider11 = new SimpleValueTargetProvider(objArray11, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider11.Add(type21, (object) valueTargetProvider11);
        xamlServiceProvider11.Add(typeof (IReferenceProvider), obj21);
        Type type22 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver11 = new XmlNamespaceResolver();
        namespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver11.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver11.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver11.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver11.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver11.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver11.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver11.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver11.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver11 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver11, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider11.Add(type22, (object) xamlTypeResolver11);
        xamlServiceProvider11.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(76, 28)));
        object obj22 = ((IMarkupExtension) resourceExtension17).ProvideValue((IServiceProvider) xamlServiceProvider11);
        ((NavigableElement) label4).set_Style((Style) obj22);
        translateExtension5.Text = "Settings_Dashboard_Title";
        TranslateExtension translateExtension11 = translateExtension5;
        XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
        Type type23 = typeof (IProvideValueTarget);
        object[] objArray12 = new object[0 + 6];
        objArray12[0] = (object) label4;
        objArray12[1] = (object) stackLayout;
        objArray12[2] = (object) frame2;
        objArray12[3] = (object) grid2;
        objArray12[4] = (object) grid4;
        objArray12[5] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider12;
        object obj23 = (object) (valueTargetProvider12 = new SimpleValueTargetProvider(objArray12, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider12.Add(type23, (object) valueTargetProvider12);
        xamlServiceProvider12.Add(typeof (IReferenceProvider), obj23);
        Type type24 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver12 = new XmlNamespaceResolver();
        namespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver12.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver12.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver12.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver12.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver12.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver12.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver12.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver12.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver12 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver12, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider12.Add(type24, (object) xamlTypeResolver12);
        xamlServiceProvider12.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(76, 69)));
        object obj24 = ((IMarkupExtension) translateExtension11).ProvideValue((IServiceProvider) xamlServiceProvider12);
        label4.set_Text((string) obj24);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label4);
        resourceExtension8.set_Key("DetailDataLabelStyle");
        StaticResourceExtension resourceExtension18 = resourceExtension8;
        XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
        Type type25 = typeof (IProvideValueTarget);
        object[] objArray13 = new object[0 + 6];
        objArray13[0] = (object) label5;
        objArray13[1] = (object) stackLayout;
        objArray13[2] = (object) frame2;
        objArray13[3] = (object) grid2;
        objArray13[4] = (object) grid4;
        objArray13[5] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider13;
        object obj25 = (object) (valueTargetProvider13 = new SimpleValueTargetProvider(objArray13, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider13.Add(type25, (object) valueTargetProvider13);
        xamlServiceProvider13.Add(typeof (IReferenceProvider), obj25);
        Type type26 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver13 = new XmlNamespaceResolver();
        namespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver13.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver13.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver13.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver13.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver13.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver13.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver13.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver13.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver13 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver13, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider13.Add(type26, (object) xamlTypeResolver13);
        xamlServiceProvider13.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(77, 28)));
        object obj26 = ((IMarkupExtension) resourceExtension18).ProvideValue((IServiceProvider) xamlServiceProvider13);
        ((NavigableElement) label5).set_Style((Style) obj26);
        translateExtension6.Text = "Settings_Dashboard_Description";
        TranslateExtension translateExtension12 = translateExtension6;
        XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
        Type type27 = typeof (IProvideValueTarget);
        object[] objArray14 = new object[0 + 6];
        objArray14[0] = (object) label5;
        objArray14[1] = (object) stackLayout;
        objArray14[2] = (object) frame2;
        objArray14[3] = (object) grid2;
        objArray14[4] = (object) grid4;
        objArray14[5] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider14;
        object obj27 = (object) (valueTargetProvider14 = new SimpleValueTargetProvider(objArray14, (object) Label.TextProperty, (INameScope) nameScope));
        xamlServiceProvider14.Add(type27, (object) valueTargetProvider14);
        xamlServiceProvider14.Add(typeof (IReferenceProvider), obj27);
        Type type28 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver14 = new XmlNamespaceResolver();
        namespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver14.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver14.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver14.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver14.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver14.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver14.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver14.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver14.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver14 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver14, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider14.Add(type28, (object) xamlTypeResolver14);
        xamlServiceProvider14.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(77, 74)));
        object obj28 = ((IMarkupExtension) translateExtension12).ProvideValue((IServiceProvider) xamlServiceProvider14);
        label5.set_Text((string) obj28);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) label5);
        ((BindableObject) rangeSlider1).SetValue((BindableProperty) View.MarginProperty, (object) new Thickness(6.0, 6.0, 6.0, 0.0));
        rangeSlider1.add_DragCompleted(new EventHandler(settingsPage.ChangeDashboardItemCount));
        ((BindableObject) rangeSlider1).SetValue((BindableProperty) Xamarin.RangeSlider.Forms.RangeSlider.MaximumValueProperty, (object) 14f);
        ((BindableObject) rangeSlider1).SetValue((BindableProperty) Xamarin.RangeSlider.Forms.RangeSlider.MinThumbHiddenProperty, (object) true);
        ((BindableObject) rangeSlider1).SetValue((BindableProperty) Xamarin.RangeSlider.Forms.RangeSlider.MinimumValueProperty, (object) 0.0f);
        ((BindableObject) rangeSlider1).SetValue((BindableProperty) Xamarin.RangeSlider.Forms.RangeSlider.ShowTextAboveThumbsProperty, (object) true);
        ((BindableObject) rangeSlider1).SetValue((BindableProperty) Xamarin.RangeSlider.Forms.RangeSlider.StepValueProperty, (object) 0.0f);
        ((BindableObject) rangeSlider1).SetValue((BindableProperty) Xamarin.RangeSlider.Forms.RangeSlider.StepValueContinuouslyProperty, (object) false);
        Xamarin.RangeSlider.Forms.RangeSlider rangeSlider2 = rangeSlider1;
        // ISSUE: variable of the null type
        __Null textSizeProperty = Xamarin.RangeSlider.Forms.RangeSlider.TextSizeProperty;
        FontSizeConverter fontSizeConverter = new FontSizeConverter();
        XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
        Type type29 = typeof (IProvideValueTarget);
        object[] objArray15 = new object[0 + 6];
        objArray15[0] = (object) rangeSlider1;
        objArray15[1] = (object) stackLayout;
        objArray15[2] = (object) frame2;
        objArray15[3] = (object) grid2;
        objArray15[4] = (object) grid4;
        objArray15[5] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider15;
        object obj29 = (object) (valueTargetProvider15 = new SimpleValueTargetProvider(objArray15, (object) Xamarin.RangeSlider.Forms.RangeSlider.TextSizeProperty, (INameScope) nameScope));
        xamlServiceProvider15.Add(type29, (object) valueTargetProvider15);
        xamlServiceProvider15.Add(typeof (IReferenceProvider), obj29);
        Type type30 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver15 = new XmlNamespaceResolver();
        namespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver15.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver15.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver15.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver15.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver15.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver15.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver15.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver15.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver15 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver15, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider15.Add(type30, (object) xamlTypeResolver15);
        xamlServiceProvider15.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(88, 25)));
        object obj30 = ((IExtendedTypeConverter) fontSizeConverter).ConvertFromInvariantString("14", (IServiceProvider) xamlServiceProvider15);
        ((BindableObject) rangeSlider2).SetValue((BindableProperty) textSizeProperty, obj30);
        bindingExtension4.set_Path("DashboardDayRange");
        BindingBase bindingBase4 = ((IMarkupExtension<BindingBase>) bindingExtension4).ProvideValue((IServiceProvider) null);
        ((BindableObject) rangeSlider1).SetBinding((BindableProperty) Xamarin.RangeSlider.Forms.RangeSlider.UpperValueProperty, bindingBase4);
        ((ICollection<View>) ((Layout<View>) stackLayout).get_Children()).Add((View) rangeSlider1);
        ((BindableObject) frame2).SetValue((BindableProperty) ContentView.ContentProperty, (object) stackLayout);
        ((ICollection<View>) grid2.get_Children()).Add((View) frame2);
        ((ICollection<View>) grid4.get_Children()).Add((View) grid2);
        resourceExtension9.set_Key("OverlayColor");
        StaticResourceExtension resourceExtension19 = resourceExtension9;
        XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
        Type type31 = typeof (IProvideValueTarget);
        object[] objArray16 = new object[0 + 3];
        objArray16[0] = (object) grid3;
        objArray16[1] = (object) grid4;
        objArray16[2] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider16;
        object obj31 = (object) (valueTargetProvider16 = new SimpleValueTargetProvider(objArray16, (object) VisualElement.BackgroundColorProperty, (INameScope) nameScope));
        xamlServiceProvider16.Add(type31, (object) valueTargetProvider16);
        xamlServiceProvider16.Add(typeof (IReferenceProvider), obj31);
        Type type32 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver16 = new XmlNamespaceResolver();
        namespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver16.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver16.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver16.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver16.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver16.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver16.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver16.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver16.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver16 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver16, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider16.Add(type32, (object) xamlTypeResolver16);
        xamlServiceProvider16.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(94, 13)));
        object obj32 = ((IMarkupExtension) resourceExtension19).ProvideValue((IServiceProvider) xamlServiceProvider16);
        ((VisualElement) grid3).set_BackgroundColor((Color) obj32);
        bindingExtension5.set_Path("IsLoading");
        BindingBase bindingBase5 = ((IMarkupExtension<BindingBase>) bindingExtension5).ProvideValue((IServiceProvider) null);
        ((BindableObject) grid3).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase5);
        ((BindableObject) grid3).SetValue((BindableProperty) View.VerticalOptionsProperty, (object) (LayoutOptions) LayoutOptions.FillAndExpand);
        ((BindableObject) circleImage).SetValue((BindableProperty) CircleImage.FillColorProperty, (object) (Color) Color.White);
        resourceExtension10.set_Key("ListItemIconStyle");
        StaticResourceExtension resourceExtension20 = resourceExtension10;
        XamlServiceProvider xamlServiceProvider17 = new XamlServiceProvider();
        Type type33 = typeof (IProvideValueTarget);
        object[] objArray17 = new object[0 + 4];
        objArray17[0] = (object) circleImage;
        objArray17[1] = (object) grid3;
        objArray17[2] = (object) grid4;
        objArray17[3] = (object) settingsPage;
        SimpleValueTargetProvider valueTargetProvider17;
        object obj33 = (object) (valueTargetProvider17 = new SimpleValueTargetProvider(objArray17, (object) VisualElement.StyleProperty, (INameScope) nameScope));
        xamlServiceProvider17.Add(type33, (object) valueTargetProvider17);
        xamlServiceProvider17.Add(typeof (IReferenceProvider), obj33);
        Type type34 = typeof (IXamlTypeResolver);
        XmlNamespaceResolver namespaceResolver17 = new XmlNamespaceResolver();
        namespaceResolver17.Add("", "http://xamarin.com/schemas/2014/forms");
        namespaceResolver17.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
        namespaceResolver17.Add("d", "http://xamarin.com/schemas/2014/forms/design");
        namespaceResolver17.Add("extensions", "clr-namespace:Ekreta.Mobile.Core.Extensions;assembly=Ekreta.Mobile.Core");
        namespaceResolver17.Add("forms", "clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms");
        namespaceResolver17.Add("ios", "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core");
        namespaceResolver17.Add("mc", "http://schemas.openxmlformats.org/markup-compatibility/2006");
        namespaceResolver17.Add("mvvmcross", "clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms");
        namespaceResolver17.Add("pluginImage", "clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions");
        namespaceResolver17.Add("viewModels", "clr-namespace:Ekreta.Mobile.Core.ViewModels;assembly=Ekreta.Mobile.Core");
        XamlTypeResolver xamlTypeResolver17 = new XamlTypeResolver((IXmlNamespaceResolver) namespaceResolver17, typeof (SettingsPage).GetTypeInfo().Assembly);
        xamlServiceProvider17.Add(type34, (object) xamlTypeResolver17);
        xamlServiceProvider17.Add(typeof (IXmlLineInfoProvider), (object) new XmlLineInfoProvider((IXmlLineInfo) new XmlLineInfo(97, 56)));
        object obj34 = ((IMarkupExtension) resourceExtension20).ProvideValue((IServiceProvider) xamlServiceProvider17);
        ((NavigableElement) circleImage).set_Style((Style) obj34);
        ((ICollection<View>) grid3.get_Children()).Add((View) circleImage);
        bindingExtension6.set_Path("IsLoading");
        BindingBase bindingBase6 = ((IMarkupExtension<BindingBase>) bindingExtension6).ProvideValue((IServiceProvider) null);
        ((BindableObject) activityIndicator).SetBinding((BindableProperty) ActivityIndicator.IsRunningProperty, bindingBase6);
        bindingExtension7.set_Path("IsLoading");
        BindingBase bindingBase7 = ((IMarkupExtension<BindingBase>) bindingExtension7).ProvideValue((IServiceProvider) null);
        ((BindableObject) activityIndicator).SetBinding((BindableProperty) VisualElement.IsVisibleProperty, bindingBase7);
        ((ICollection<View>) grid3.get_Children()).Add((View) activityIndicator);
        ((ICollection<View>) grid4.get_Children()).Add((View) grid3);
        ((BindableObject) settingsPage).SetValue((BindableProperty) ContentPage.ContentProperty, (object) grid4);
      }
    }

    private void __InitComponentRuntime()
    {
      Xamarin.Forms.Xaml.Extensions.LoadFromXaml<SettingsPage>((M0) this, typeof (SettingsPage));
      this.Page = (MvxContentPage<SettingsViewModel>) NameScopeExtensions.FindByName<MvxContentPage<SettingsViewModel>>((Element) this, "Page");
      this.DashboardItemCountSlider = (Xamarin.RangeSlider.Forms.RangeSlider) NameScopeExtensions.FindByName<Xamarin.RangeSlider.Forms.RangeSlider>((Element) this, "DashboardItemCountSlider");
    }
  }
}
