package p289hu.ekreta.ellenorzo.parceler;

import android.os.Parcel;
import java.math.BigDecimal;
import java.math.BigInteger;
import kotlin.Metadata;
import kotlin.NotImplementedError;
import kotlin.jvm.internal.Intrinsics;
import p197d.p202b.p203a.C3152a;

@Metadata(mo17461bv = {1, 0, 3}, mo17462d1 = {"\u0000\"\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0010\b\n\u0000\bÆ\u0002\u0018\u00002\n\u0012\u0006\u0012\u0004\u0018\u00010\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0003J\u0012\u0010\u0004\u001a\u0004\u0018\u00010\u00022\u0006\u0010\u0005\u001a\u00020\u0006H\u0016J\u001e\u0010\u0007\u001a\u00020\b*\u0004\u0018\u00010\u00022\u0006\u0010\u0005\u001a\u00020\u00062\u0006\u0010\t\u001a\u00020\nH\u0016¨\u0006\u000b"}, mo17463d2 = {"Lhu/ekreta/ellenorzo/parceler/BigDecimalParceler;", "Lkotlinx/android/parcel/Parceler;", "Ljava/math/BigDecimal;", "()V", "create", "parcel", "Landroid/os/Parcel;", "write", "", "flags", "", "app_studentProdRelease"}, mo17464k = 1, mo17465mv = {1, 1, 15})
/* renamed from: hu.ekreta.ellenorzo.parceler.BigDecimalParceler */
/* compiled from: Parcelers.kt */
public final class BigDecimalParceler implements C3152a<BigDecimal> {
    public static final BigDecimalParceler INSTANCE = new BigDecimalParceler();

    /* renamed from: a */
    public void mo14007a(BigDecimal bigDecimal, Parcel parcel) {
        Intrinsics.checkParameterIsNotNull(parcel, "parcel");
        if (bigDecimal != null) {
            parcel.writeInt(1);
            parcel.writeByteArray(bigDecimal.unscaledValue().toByteArray());
            parcel.writeInt(bigDecimal.scale());
            return;
        }
        parcel.writeInt(0);
    }

    public /* bridge */ /* synthetic */ void write(Object obj, Parcel parcel, int i) {
        mo14007a((BigDecimal) obj, parcel);
    }

    public BigDecimal create(Parcel parcel) {
        Intrinsics.checkParameterIsNotNull(parcel, "parcel");
        if (parcel.readInt() != 0) {
            return new BigDecimal(new BigInteger(parcel.createByteArray()), parcel.readInt());
        }
        return null;
    }

    public BigDecimal[] newArray(int i) {
        throw new NotImplementedError("Generated by Android Extensions automatically");
    }
}
