using Ekreta.Mobile.Core;
using Ekreta.Mobile.Core.Controls;
using Ekreta.Mobile.Core.Views;
using System.Reflection;
using System.Runtime.CompilerServices;
using Xamarin.Forms.Xaml;

[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.HomeWorkEditPage.xaml", "Views/HomeWorkEditPage.xaml", typeof (HomeWorkEditPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.HomeWorkDetailPage.xaml", "Views/HomeWorkDetailPage.xaml", typeof (HomeWorkDetailPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.FormTeacherPage.xaml", "Views/FormTeacherPage.xaml", typeof (FormTeacherPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.ExamsPage.xaml", "Views/ExamsPage.xaml", typeof (ExamsPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.ExamsDetailPage.xaml", "Views/ExamsDetailPage.xaml", typeof (ExamsDetailPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.EventsPage.xaml", "Views/EventsPage.xaml", typeof (EventsPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.EventDetailPage.xaml", "Views/EventDetailPage.xaml", typeof (EventDetailPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.EvaluationsPage.xaml", "Views/EvaluationsPage.xaml", typeof (EvaluationsPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.EvaluationDetailPage.xaml", "Views/EvaluationDetailPage.xaml", typeof (EvaluationDetailPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.HomeWorksPage.xaml", "Views/HomeWorksPage.xaml", typeof (HomeWorksPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.DatabaseErrorPage.xaml", "Views/DatabaseErrorPage.xaml", typeof (DatabaseErrorPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.AbsenceDetailPage.xaml", "Views/AbsenceDetailPage.xaml", typeof (AbsenceDetailPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Styles.xaml", "Styles.xaml", null)]
[assembly: XamlResourceId("Ekreta.Mobile.Core.FormsApp.xaml", "FormsApp.xaml", typeof (FormsApp))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Controls.ErrorView.xaml", "Controls/ErrorView.xaml", typeof (ErrorView))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Controls.EmptyView.xaml", "Controls/EmptyView.xaml", typeof (EmptyView))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.AbsencesPage.xaml", "Views/AbsencesPage.xaml", typeof (AbsencesPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.HomeWorkStudentDetailPage.xaml", "Views/HomeWorkStudentDetailPage.xaml", typeof (HomeWorkStudentDetailPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.InformationPage.xaml", "Views/InformationPage.xaml", typeof (InformationPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.InstitutePickerPage.xaml", "Views/InstitutePickerPage.xaml", typeof (InstitutePickerPage))]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCompany("Ekreta.Mobile.Core")]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.StatisticsPage.xaml", "Views/StatisticsPage.xaml", typeof (StatisticsPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.SettingsPage.xaml", "Views/SettingsPage.xaml", typeof (SettingsPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.RootedDevicePage.xaml", "Views/RootedDevicePage.xaml", typeof (RootedDevicePage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.RootContentPage.xaml", "Views/RootContentPage.xaml", typeof (RootContentPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.RatingPopupPage.xaml", "Views/RatingPopupPage.xaml", typeof (RatingPopupPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.RatingChooser.xaml", "Views/RatingChooser.xaml", typeof (RatingChooser))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.ProfilesPage.xaml", "Views/ProfilesPage.xaml", typeof (ProfilesPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.PersonalDataSheetPage.xaml", "Views/PersonalDataSheetPage.xaml", typeof (PersonalDataSheetPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.NotesPage.xaml", "Views/NotesPage.xaml", typeof (NotesPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.NoteDetailPage.xaml", "Views/NoteDetailPage.xaml", typeof (NoteDetailPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.NewProfilePage.xaml", "Views/NewProfilePage.xaml", typeof (NewProfilePage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.NeedUpdatePage.xaml", "Views/NeedUpdatePage.xaml", typeof (NeedUpdatePage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.MessagesPage.xaml", "Views/MessagesPage.xaml", typeof (MessagesPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.MessageDetailPage.xaml", "Views/MessageDetailPage.xaml", typeof (MessageDetailPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.MasterPage.xaml", "Views/MasterPage.xaml", typeof (MasterPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.LoginPage.xaml", "Views/LoginPage.xaml", typeof (LoginPage))]
[assembly: XamlResourceId("Ekreta.Mobile.Core.Views.LessonsPage.xaml", "Views/LessonsPage.xaml", typeof (LessonsPage))]
[assembly: Extension]
[assembly: AssemblyProduct("Ekreta.Mobile.Core")]
[assembly: AssemblyTitle("Ekreta.Mobile.Core")]
[assembly: AssemblyVersion("1.0.0.0")]
